import type { Metadata } from "next";
import "./frameworks-cpra.css";
import { FrameworksCpraSnapshot } from "./_snapshot/FrameworksCpraSnapshot";
import { WebflowInteractions } from "../../_shared/WebflowInteractions";

export const metadata: Metadata = {
  title: "Mycroft Frameworks | CPRA compliance, built on CCPA, ready for what’s next",
  description: "Mycroft’s Risk Operations Center removes the operational burden, helping you meet CPRA requirements and manage consumer data with confidence.",
  openGraph: {
    title: "Mycroft Frameworks | CPRA compliance, built on CCPA, ready for what’s next",
    description: "Mycroft’s Risk Operations Center removes the operational burden, helping you meet CPRA requirements and manage consumer data with confidence.",
    type: "website",
    images: ["/assets/frameworks-crpa-meta-v2.jpg"],
  },
  twitter: {
    card: "summary_large_image",
    title: "Mycroft Frameworks | CPRA compliance, built on CCPA, ready for what’s next",
    description: "Mycroft’s Risk Operations Center removes the operational burden, helping you meet CPRA requirements and manage consumer data with confidence.",
    images: ["/assets/frameworks-crpa-meta-v2.jpg"],
  },
};

/**
 * /frameworks/cpra: a faithful React rebuild of the Webflow page.
 * Generated by the Webflow Cloner agent from https://mycroft.io/frameworks/cpra.
 */
export default function FrameworksCpraPage() {
  return (
    <>
      <FrameworksCpraSnapshot />
      <WebflowInteractions />
    </>
  );
}
