import { SiteNav } from "../../_shared/SiteNav";
import { SiteFooter } from "../../_shared/SiteFooter";
import { TermsSection1 } from "./TermsSection1";
import { TermsSection2 } from "./TermsSection2";

/**
 * Faithful React port of the Webflow https://www.mycroft.io/terms page. DOM + classes mirror
 * the original 1:1; global styling is in webflow-shared.css, page CSS
 * in terms.css. Generated by the Webflow Cloner agent.
 */
export function TermsSnapshot() {
  return (
    <div className="page-wrapper u-minh-100vh">
      <div className="styles__global-embed-code w-embed"></div>
      <SiteNav />
      <main id="main" className="page-main nav_v2">
        <TermsSection1 />
        <TermsSection2 />
        <SiteFooter />
      </main>
    </div>
  );
}
