import { ButtonLarge } from "@/app/_shared/ButtonLarge";
import { ResourcesCollection1List } from "./ResourcesCollection1List";
/** Section 2 of /resources. Generated by the Webflow Cloner agent. */
export function ResourcesSection2() {
  return (
    <section id="about-mycroft" className="section_v2 earl40">
      <div className="page-padding">
        <div className="container-large">
          <div className="padding-top large">
            <div className="container-flex vertical">
              <h2 className="h3_v2 color_rg text_center">
                Featured blog
              </h2>
              <div className="padding-top xxs">
                <div className="text-dek-m text_center">
                  Gain insights, updates, and best practices to strengthen your security posture! To see our full Diogenes Club blog selection, click here:
                </div>
              </div>
              <div className="padding-top small text-center">
                <ButtonLarge href="https://diogenesclub.ca/" shine>
                  Diogenes Club
                </ButtonLarge>
              </div>
            </div>
          </div>
          <div className="padding-top medium">
            <div className="padding-btm xl">
              <div className="blog-container">
                <div className="blog-wrapper w-dyn-list">
                  <ResourcesCollection1List />
                  <div className="w-dyn-empty" style={{"display": "none"}}>
                    <div>
                      No items found.
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
