import type { ResourcesCollection2Item } from "./ResourcesCollection2";

/** Data for the ResourcesCollection2 collection, parsed from the Webflow CMS items. Generated by the Webflow Cloner agent. */
export const resourcesCollection2Data: ResourcesCollection2Item[] = [
  {
    "href_0": "/case-studies/smashsend",
    "image_1": "/assets/smashsendcover-2.webp",
    "image_2": "/assets/smashsendcover-2-p-500.webp 500w, /assets/smashsendcover-2-p-800.webp 800w, /assets/smashsendcover-2-p-1080.webp 1080w, /assets/smashsendcover-2-p-1600.webp 1600w, /assets/smashsendcover-2-p-2000.webp 2000w, /assets/smashsendcover-2.webp 2400w",
    "h6_3": "How SMASHSEND achieved enterprise compliance with Mycroft",
    "image_4": "/assets/jorge-cs.webp",
    "text_5": "Jorge Ferreiro",
    "div_6": "CEO of SMASHSEND",
    "href_7": "/case-studies/smashsend"
  },
  {
    "href_0": "/case-studies/wisedocs",
    "image_1": "/assets/wisedocscs-meta.jpg",
    "image_2": "/assets/wisedocscs-meta-p-500.jpg 500w, /assets/wisedocscs-meta-p-800.jpg 800w, /assets/wisedocscs-meta-p-1080.jpg 1080w, /assets/wisedocscs-meta-p-1600.jpg 1600w, /assets/wisedocscs-meta-p-2000.jpg 2000w, /assets/wisedocscs-meta.jpg 2400w",
    "h6_3": "From security uncertainty to 100% ROI: the Wisedocs journey",
    "image_4": "/assets/pq-jenna.webp",
    "text_5": "Jenna Earnshaw",
    "div_6": "COO at Wisedocs",
    "href_7": "/case-studies/wisedocs"
  },
  {
    "href_0": "/case-studies/unified",
    "image_1": "/assets/unifiedcs-meta.jpg",
    "image_2": "/assets/unifiedcs-meta-p-500.jpg 500w, /assets/unifiedcs-meta-p-800.jpg 800w, /assets/unifiedcs-meta-p-1080.jpg 1080w, /assets/unifiedcs-meta-p-1600.jpg 1600w, /assets/unifiedcs-meta-p-2000.jpg 2000w, /assets/unifiedcs-meta.jpg 2400w",
    "h6_3": "How Unified cut SOC 2 time by 90% and made security a revenue driver",
    "image_4": "/assets/pq-roy.webp",
    "text_5": "Roy Pereira",
    "div_6": "CEO of Unified.to",
    "href_7": "/case-studies/unified"
  },
  {
    "href_0": "/case-studies/weave",
    "image_1": "/assets/weavecs-meta.jpg",
    "image_2": "/assets/weavecs-meta-p-500.jpg 500w, /assets/weavecs-meta-p-800.jpg 800w, /assets/weavecs-meta-p-1080.jpg 1080w, /assets/weavecs-meta-p-1600.jpg 1600w, /assets/weavecs-meta-p-2000.jpg 2000w, /assets/weavecs-meta.jpg 2400w",
    "h6_3": "How Weave went from zero to SOC 2 in under 30 days",
    "image_4": "/assets/pq-adam.webp",
    "text_5": "Adam Cohen",
    "div_6": "CEO of Weave",
    "href_7": "/case-studies/weave"
  }
];
