import { SiteNav23 } from "../../_shared/SiteNav23";
import { SiteFooter } from "../../_shared/SiteFooter";
import { ResourcesSection1 } from "./ResourcesSection1";
import { ResourcesSection2 } from "./ResourcesSection2";
import { ResourcesSection3 } from "./ResourcesSection3";
import { ResourcesSection4 } from "./ResourcesSection4";
import { ResourcesSection5 } from "./ResourcesSection5";

/**
 * Faithful React port of the Webflow https://www.mycroft.io/resources page. DOM + classes mirror
 * the original 1:1; global styling is in webflow-shared.css, page CSS
 * in resources.css. Generated by the Webflow Cloner agent.
 */
export function ResourcesSnapshot() {
  return (
    <div className="page-wrapper u-minh-100vh">
      <div className="styles__global-embed-code w-embed"></div>
      <SiteNav23 />
      <main id="main" className="page-content">
        <ResourcesSection1 />
        <ResourcesSection2 />
        <ResourcesSection3 />
        <div className="overlap-top">
          <div className="overlap-block"></div>
          <div className="container-large">
            <div className="overlap-block top_block"></div>
          </div>
          <div className="overlap-block transparent"></div>
        </div>
        <ResourcesSection4 />
        <ResourcesSection5 />
      </main>
      <SiteFooter />
    </div>
  );
}
