"use client";

import { useState } from "react";
import { ResourcesCollection1 } from "./ResourcesCollection1";
import { resourcesCollection1Data } from "./ResourcesCollection1.data";

/**
 * Client-side Load More for the ResourcesCollection1 collection: the original
 * page only served 4 item(s) per ?page=N round-trip; the clone
 * folded all 18 item(s) into the data array and reveals them in
 * page-size steps. Generated by the Webflow Cloner agent.
 */
export function ResourcesCollection1List() {
  const [visible, setVisible] = useState(4);
  return (
    <>
      <div role="list" className="blog-list w-dyn-items">
        {resourcesCollection1Data.slice(0, visible).map((item, i) => (
          <ResourcesCollection1 item={item} key={i} />
        ))}
      </div>
      {visible < resourcesCollection1Data.length ? (
        <div
          role="navigation"
          aria-label="List"
          className="w-pagination-wrapper padding-top medium"
        >
          <button
            type="button"
            aria-label="Next Page"
            className="w-pagination-next btn-large"
            onClick={() => setVisible((v) => v + 4)}
          >
            <div className="btn-text-large w-inline-block">{"More"}</div>
            <img
              src="/assets/arrow-icon-v2.svg"
              loading="lazy"
              alt=""
              className="btn-arrow-large"
            />
          </button>
        </div>
      ) : null}
    </>
  );
}
