import { SiteNav } from "../../_shared/SiteNav";
import { SiteFooter3 } from "../../_shared/SiteFooter3";
import { PrivacySection1 } from "./PrivacySection1";
import { PrivacySection2 } from "./PrivacySection2";

/**
 * Faithful React port of the Webflow https://www.mycroft.io/privacy page. DOM + classes mirror
 * the original 1:1; global styling is in webflow-shared.css, page CSS
 * in privacy.css. Generated by the Webflow Cloner agent.
 */
export function PrivacySnapshot() {
  return (
    <div className="page-wrapper u-minh-100vh">
      <div className="styles__global-embed-code w-embed"></div>
      <SiteNav />
      <main id="main" className="page-main nav_v2">
        <PrivacySection1 />
        <PrivacySection2 />
        <SiteFooter3 />
      </main>
    </div>
  );
}
