/** Section 1 of /privacy. Generated by the Webflow Cloner agent. */
export function PrivacySection1() {
  return (
    <section style={{"transform": "translate3d(0px, 0px, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg)", "opacity": "1", "transformStyle": "preserve-3d"}} className="section u-bg-primary nav_v2">
      <div className="w-layout-blockcontainer container w-container">
        <div className="row">
          <div className="col u-text-center">
            <h1 className="h1 u-text-white">
              Mycroft's Privacy Policy
            </h1>
            <div className="u-text-white is-italics">
              Last revised: May 19, 2026
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
