/** Section 2 of /privacy. Generated by the Webflow Cloner agent. */
export function PrivacySection2() {
  return (
    <section style={{"transform": "translate3d(0px, 0px, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg)", "opacity": "1", "transformStyle": "preserve-3d"}} className="section">
      <div className="w-layout-blockcontainer container w-container">
        <div className="row">
          <div className="col">
            <div className="rich-text w-richtext">
              <p>
                <strong>
                  Introduction
                </strong>
                <br />
                Mycroft Technologies Inc. is committed to protecting your privacy. This Privacy Policy outlines how we collect, use, and share information collected through our services ("Services"). By using our Services, you consent to the practices described in this policy.
                <br />
                <br />
                <strong>
                  Information We Collect
                </strong>
                ‍
              </p>
              <ul role="list">
                <li>
                  Personal Information: We may collect personal information such as name, email address, IP address, and payment details when you use our Services.
                </li>
              </ul>
              <ul role="list">
                <li>
                  Non-Personal Information: We collect non-personal data such as usage statistics and demographic information to improve our Services.
                </li>
              </ul>
              <p>
                ‍
                <strong>
                  Use of Information
                </strong>
                <br />
                We may use the information collected to:
              </p>
              <ul role="list">
                <li>
                  Provide and improve our Services
                </li>
                <li>
                  Process transactions and send related information
                </li>
                <li>
                  Communicate with you, including sending promotional materials
                </li>
                <li>
                  Prevent fraud and ensure the security of our Services
                </li>
              </ul>
              <p>
                As part of our organization’s philosophy in meeting the highest standards of privacy and security standards, we will utilize all commercially viable means to reduce the storage and processing of personal information.
                <br />
                <br />
                <strong>
                  Sharing of Information
                </strong>
                <br />
                We do not share your personal information with third parties except:
              </p>
              <ul role="list">
                <li>
                  With your consent
                </li>
                <li>
                  For processing transactions (e.g., payment processors)
                </li>
                <li>
                  For legal reasons (e.g., to comply with laws, regulations, or legal requests)
                </li>
              </ul>
              <p>
                No mobile information will be shared with third parties/affiliates for marketing or promotional purposes. All the above categories exclude text messaging originator opt-in data and consent; this information will not be shared with any third parties.
              </p>
              <p>
                ‍
                <strong>
                  Cookies
                </strong>
                <br />
                We may use cookies to:
              </p>
              <ul role="list">
                <li>
                  Enhance your experience on our website
                </li>
                <li>
                  Understand website usage and improve functionality
                </li>
              </ul>
              <p>
                You can control cookies through your browser settings.
                <br />
                <br />
                <strong>
                  Data Security
                </strong>
                <br />
                We implement industry-standard security measures to protect your data. However, no method of transmission over the internet or electronic storage is completely secure. Our security program achieves compliance based on SOC 2 and NIST CSF powered by our own platform.
              </p>
              <p>
                <strong>
                  Data Subprocessors
                </strong>
                <br />
                Mycroft uses the following subprocessors that handle data to deliver our platform are:
              </p>
              <ul role="list">
                <li>
                  <strong>
                    Google Cloud Platform:
                  </strong>
                  Platform and Infrastructure, United States
                </li>
                <li>
                  <strong>
                    Google Workspace:
                  </strong>
                  Email and Productivity, United States
                </li>
                <li>
                  <strong>
                    Github:
                  </strong>
                  Code Repository, United States
                </li>
                <li>
                  <strong>
                    Unified:
                  </strong>
                  Unified API Platform, Canada and United States
                </li>
                <li>
                  <strong>
                    Hubspot:
                  </strong>
                  Customer Relationship Management, United States
                </li>
                <li>
                  <strong>
                    Twilio Sendgrid:
                  </strong>
                  Transactional email service, United States
                </li>
              </ul>
              <p>
                <strong>
                  Data Retention
                </strong>
                <br />
                We retain personal information for as long as necessary to fulfill the purposes for which it was collected, comply with legal obligations, and enforce our agreements.
                <br />
                <br />
                <strong>
                  Your Privacy Rights
                </strong>
                <br />
                As a firm believer of privacy rights for our customers, you have the following rights regarding your personal data:
                <br />
              </p>
              <ul role="list">
                <li>
                  <strong>
                    Right to Access:
                  </strong>
                  You can request access to your personal data.
                </li>
                <li>
                  ‍
                  <strong>
                    Right to Correct:
                  </strong>
                  You can request correction of inaccurate or incomplete data.
                  <strong>
                    ‍
                  </strong>
                </li>
                <li>
                  <strong>
                    Right to Delete:
                  </strong>
                  You can request deletion of your personal data.
                  <strong>
                    ‍
                  </strong>
                </li>
                <li>
                  <strong>
                    Right to Processing:
                  </strong>
                  You can request to limit the processing of your data.
                  <strong>
                    ‍
                  </strong>
                </li>
                <li>
                  <strong>
                    Right to Portability:
                  </strong>
                  You can request a copy of your data in a structured, machine-readable format.
                  <strong>
                    ‍
                  </strong>
                </li>
                <li>
                  <strong>
                    Right to Object:
                  </strong>
                  You can object to the processing of your data for certain purposes.
                  <strong>
                    ‍
                  </strong>
                </li>
                <li>
                  <strong>
                    Right to Non-Discrimination:
                  </strong>
                  You have the right not to be discriminated against for exercising any of your CCPA rights.
                  <strong>
                    ‍
                  </strong>
                </li>
                <li>
                  <strong>
                    Right to Consent:
                  </strong>
                  You can withdraw your consent to data processing at any time.
                </li>
              </ul>
              <p>
                To exercise these rights, contact us at{" "}
                <a href="mailto:privacy@mycroft.io">
                  privacy@mycroft.io
                </a>
                .
                <br />
                <br />
                <strong>
                  Legal Basis for Processing Personal Data
                </strong>
                <br />
                We process personal data based on:
              </p>
              <ul role="list">
                <li>
                  Your consent
                </li>
                <li>
                  Performance of a contract
                </li>
                <li>
                  Compliance with legal obligations
                </li>
                <li>
                  Our legitimate interests, which include improving our services and ensuring security
                </li>
              </ul>
              <p>
                ‍
                <strong>
                  International Data Transfers
                </strong>
                <br />
                We may transfer your personal data outside the EEA. When we do so, we ensure appropriate safeguards are in place to protect your data, such as standard contractual clauses or other legal mechanisms.
                <br />
                <br />
                <strong>
                  Data Protection Officer (DPO)
                </strong>
                <br />
                We have appointed a Data Protection Officer (DPO) to oversee our data protection strategy and ensure compliance with GDPR requirements. If you have any questions or concerns about how we handle your personal data, you can contact our DPO at:
                <br />
                <br />
                Mike Kim
                <br />
                <a href="mailto:privacy@mycroft.io">
                  privacy@mycroft.io
                </a>
                <br />
                <br />
                <strong>
                  Data Processing Agreement (DPA)
                </strong>
                <br />
                For more detailed information on how we handle data processing and/or to execute a Data Processing Agreement (DPA) please reach out to{" "}
                <a href="mailto:privacy@mycroft.io">
                  privacy@mycroft.io
                </a>
                .
              </p>
              <p>
                <strong>
                  Google API Services User Data Policy / Limited Use Disclosure
                </strong>
                <br />
                Mycroft's use and transfer to any other app of information received from Google APIs will adhere to the Google API Services User Data Policy, including the Limited Use requirements.Specifically, Mycroft affirms that data obtained through Google APIs is:
              </p>
              <ul role="list">
                <li>
                  Used only to provide or improve user-facing features that are prominent in the Mycroft application's user interface
                </li>
                <li>
                  Not transferred to third parties except as necessary to provide or improve those features, to comply with applicable law, or as part of a merger, acquisition, or sale of assets with user notice
                </li>
                <li>
                  Not used or transferred for serving advertisements, including retargeting, personalized, or interest-based advertising
                </li>
              </ul>
              <p>
                ‍
                <br />
                <strong>
                  Changes to This Policy
                </strong>
                <br />
                We may update this Privacy Policy from time to time. We will notify you of any changes by posting the new policy on our website. Your continued use of the Services after changes are made indicates your acceptance of the new policy.
                <br />
                <br />
                <strong>
                  Contact Us
                </strong>
                <br />
                If you have any questions about this Privacy Policy, please contact us at{" "}
                <a href="mailto:privacy@mycroft.io">
                  privacy@mycroft.io
                </a>
                .
              </p>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
