import { FaqItem } from "@/app/_shared/Accordion";

/** Section 5 of /frameworks/cpra. Generated by the Webflow Cloner agent. */
export function FrameworksCpraSection5() {
  return (
    <section className="section_v2 color_smoke">
      <div className="page-padding">
        <div className="container-medium">
          <div className="padding-top medium">
            <div className="padding-btm large">
              <img src="/assets/faq-notchlabel-desktop.svg" loading="lazy" alt="" className="faq-notch-desktop" />
              <img src="/assets/faq-notchlabel-mobile.svg" loading="lazy" alt="" className="faq-notch-mobile" />
              <div className="container-flex faq_container">
                <div className="faq-hed-flex">
                  <h3 className="h3_v2 color_white">
                    Frequently asked questions
                  </h3>
                  <div className="text-dek-l text_40eg">
                    Answers that help customers with{" "}
                    <span className="no-wrap">
                      CPRA/CCPA
                    </span>{" "}
                    compliance
                  </div>
                </div>
                <FaqItem question="What is CPRA?" first>
                  CPRA (California Privacy Rights Act) expands on CCPA by introducing stronger privacy protections and new consumer rights.
                </FaqItem>
                <FaqItem question="What is the difference between CPRA and CCPA?">
                  CCPA established baseline privacy rights, while CPRA enhances them with additional requirements like data correction rights, limits on sensitive data use, and stronger enforcement.
                </FaqItem>
                <FaqItem question="Who needs to comply with CPRA?">
                  Businesses that collect or process personal data of California residents and meet certain revenue or data thresholds.
                </FaqItem>
                <FaqItem question="What are consumer rights under CPRA?">
                  Consumers can access, delete, correct, and limit the use of their personal and sensitive information.
                </FaqItem>
                <FaqItem question="How does Mycroft help with CPRA?" last>
                  Mycroft helps you operationalize both CCPA and CPRA by managing data rights, policies, and compliance processes in one platform.
                </FaqItem>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
