import { CtaSection } from "@/app/_shared/CtaSection";
import { SiteNav } from "../../../_shared/SiteNav";
import { SiteFooter } from "../../../_shared/SiteFooter";
import { FrameworksCpraSection1 } from "./FrameworksCpraSection1";
import { FrameworksCpraSection2 } from "./FrameworksCpraSection2";
import { FrameworksCpraSection3 } from "./FrameworksCpraSection3";
import { FrameworksCpraSection4 } from "./FrameworksCpraSection4";
import { FrameworksCpraSection5 } from "./FrameworksCpraSection5";
import { UnlockFrameworksSection } from "@/app/_shared/UnlockFrameworksSection";

/**
 * Faithful React port of the Webflow https://mycroft.io/frameworks/cpra page. DOM + classes mirror
 * the original 1:1; global styling is in webflow-shared.css, page CSS
 * in frameworks-cpra.css. Generated by the Webflow Cloner agent.
 */
export function FrameworksCpraSnapshot() {
  return (
    <div className="page-wrapper u-minh-100vh color_rg">
      <div className="styles__global-embed-code w-embed"></div>
      <SiteNav />
      <main id="main" className="page-content">
        <FrameworksCpraSection1 />
        <FrameworksCpraSection2 />
        <FrameworksCpraSection3 />
        <FrameworksCpraSection4 />
        <UnlockFrameworksSection
          blurb="Achieve CPRA compliance with Mycroft and take advantage of the head start gained in other industry frameworks."
          dials={[
            { href: "/frameworks/gdpr", label: "GDPR", lottie: "/lottie/6a024debde8e8bdd03fd4005_Compliance-Dial_75.json" },
            { href: "/frameworks/pipeda", label: "PIPEDA", lottie: "/lottie/6a024deb01ab375d7de27c3b_Compliance-Dial_85.json" },
            { href: "/frameworks/iso27001", label: "ISO 27001", lottie: "/lottie/6a024deb9a47cda7c321c5a3_Compliance-Dial_45.json" },
          ]}
        />
        <FrameworksCpraSection5 />
        <CtaSection variant="fireplace" />
      </main>
      <SiteFooter />
    </div>
  );
}
