import type { Metadata } from "next";
import "./frameworks-iso42001.css";
import { FrameworksIso42001Snapshot } from "./_snapshot/FrameworksIso42001Snapshot";
import { WebflowInteractions } from "../../_shared/WebflowInteractions";

export const metadata: Metadata = {
  title: "Mycroft Frameworks | ISO 42001 compliance, built for AI governance",
  description: "Mycroft’s Risk Operations Center removes the operational burden, helping you implement responsible AI practices and meet ISO 42001 requirements.",
  openGraph: {
    title: "Mycroft Frameworks | ISO 42001 compliance, built for AI governance",
    description: "Mycroft’s Risk Operations Center removes the operational burden, helping you implement responsible AI practices and meet ISO 42001 requirements.",
    type: "website",
    images: ["/assets/frameworks-iso42001-meta-v1.jpg"],
  },
  twitter: {
    card: "summary_large_image",
    title: "Mycroft Frameworks | ISO 42001 compliance, built for AI governance",
    description: "Mycroft’s Risk Operations Center removes the operational burden, helping you implement responsible AI practices and meet ISO 42001 requirements.",
    images: ["/assets/frameworks-iso42001-meta-v1.jpg"],
  },
};

/**
 * /frameworks/iso42001: a faithful React rebuild of the Webflow page.
 * Generated by the Webflow Cloner agent from https://mycroft.io/frameworks/iso42001.
 */
export default function FrameworksIso42001Page() {
  return (
    <>
      <FrameworksIso42001Snapshot />
      <WebflowInteractions />
    </>
  );
}
