/** Section 1 of /partnerships. Generated by the Webflow Cloner agent. */
export function PartnershipsSection1() {
  return (
    <section id="hero" className="section-hero">
      <div className="page-padding">
        <div className="container-xl">
          <div className="hero-demo-container demo_page">
            <div className="hero-demo-full">
              <div className="partnerships-col-left">
                <div className="eyebrow-label-medium">
                  <div className="eyebrow-large demo_cta">
                    PARTNERSHIPS
                  </div>
                </div>
                <div className="padding-top">
                  <h3 className="h3_v2 color_rg">
                    Empower security together.
                  </h3>
                  <div className="padding-top xsmall">
                    <div className="body-text-medium">
                      Partner with Mycroft on the mission to revolutionize security and compliance for every industry.
                    </div>
                  </div>
                </div>
              </div>
              <div className="demo-col-right">
                <div className="demo-form-container">
                  <h5 className="h5">
                    Talk to our team!
                  </h5>
                  <div className="w-embed w-script">
                    <div id="hbspt-form-67f61335-6dca-4671-bbfe-8a7e7b52f473" className="hbspt-form" data-hs-forms-root="true">
                      <iframe id="hs-form-iframe-0" className="hs-form-iframe" title="Form 0" scrolling="no" width="100%" style={{"position": "static", "borderWidth": "medium", "borderStyle": "none", "borderColor": "currentcolor", "borderImage": "initial", "display": "block", "overflow": "hidden", "width": "100%", "height": "444px"}} height="444"></iframe>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div className="hero-background color_integrations"></div>
      <div className="hero-background color_overlay_aubergine"></div>
      <div className="hero-background pattern_pixels brighter"></div>
    </section>
  );
}
