import { PartnershipsCollection1 } from "./PartnershipsCollection1";
import { partnershipsCollection1Data } from "./PartnershipsCollection1.data";
import { SiteNav } from "../../_shared/SiteNav";
import { SiteFooter } from "../../_shared/SiteFooter";
import { PartnershipsSection1 } from "./PartnershipsSection1";
import { PartnershipsSection2 } from "./PartnershipsSection2";

/**
 * Faithful React port of the Webflow https://www.mycroft.io/partnerships page. DOM + classes mirror
 * the original 1:1; global styling is in webflow-shared.css, page CSS
 * in partnerships.css. Generated by the Webflow Cloner agent.
 */
export function PartnershipsSnapshot() {
  return (
    <div className="page-wrapper u-minh-100vh color_rg">
      <div className="styles__global-embed-code w-embed"></div>
      <SiteNav />
      <main id="main" className="page-content">
        <PartnershipsSection1 />
        <PartnershipsSection2 />
        <div className="scroll-container-outer">
          <div className="scroll-container-inner">
            <section id="product-features" className="section_v2 split_background rg_40smoke">
              <div className="page-padding">
                <div className="container-xl">
                  <div className="padding-btm medium">
                    <div className="scroll-slider-outer">
                      <section id="audit-compliance" className="scroll-slider-inner">
                        <div className="enumeration-container">
                          <div className="enumeration-counter">
                            <div className="enumeration-absolute">
                              <div className="body-text-medium _75_rg enumeration1" style={{"willChange": "opacity", "opacity": "1"}}>
                                1
                                <br />
                              </div>
                            </div>
                            <div className="enumeration-absolute">
                              <div className="body-text-medium _75_rg enumeration2" style={{"willChange": "opacity", "opacity": "0"}}>
                                2
                                <br />
                              </div>
                            </div>
                            <div className="enumeration-absolute">
                              <div className="body-text-medium _75_rg enumeration3" style={{"willChange": "opacity", "opacity": "0"}}>
                                3
                              </div>
                            </div>
                          </div>
                          <div className="body-text-medium _75_rg">
                            /
                          </div>
                          <div className="body-text-medium _75_rg">
                            3
                          </div>
                        </div>
                        <div className="features-row static" style={{"willChange": "opacity", "opacity": "0"}}>
                          <div className="features-text">
                            <h4 className="h4_v2 color_rg">
                              Remote device wipe
                            </h4>
                            <div className="body-text-large smaller_tablet">
                              Partnering with Mycroft positions you at the forefront of the cybersecurity landscape. With our cutting-edge technology and comprehensive suite of security solutions, you can enhance your offerings and deliver unparalleled protection to your clients.
                            </div>
                          </div>
                          <div className="features-img-container">
                            <img src="/assets/msp-partners.webp" loading="lazy" width="676" sizes="(max-width: 479px) 100vw, 676px" alt="" srcSet="/assets/msp-partners-p-500.webp 500w, /assets/msp-partners-p-800.webp 800w, /assets/msp-partners-p-1080.webp 1080w, /assets/msp-partners.webp 1320w" className="features-img" />
                          </div>
                        </div>
                        <div className="features-row absolute slide1">
                          <div className="features-text slide1" style={{"willChange": "transform, opacity", "transform": "translate3d(0px, 0px, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg)", "transformStyle": "preserve-3d", "opacity": "1"}}>
                            <h4 className="h4_v2 color_rg">
                              MSP partners
                            </h4>
                            <div className="body-text-large smaller_tablet">
                              Partnering with Mycroft positions you at the forefront of the cybersecurity landscape. With our cutting-edge technology and comprehensive suite of security solutions, you can enhance your offerings and deliver unparalleled protection to your clients.
                            </div>
                          </div>
                          <div className="features-img-container slide1" style={{"willChange": "transform, opacity", "transform": "translate3d(0px, 0px, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg)", "transformStyle": "preserve-3d", "opacity": "1"}}>
                            <img src="/assets/msp-partners.webp" loading="lazy" width="676" sizes="(max-width: 479px) 100vw, 676px" alt="" srcSet="/assets/msp-partners-p-500.webp 500w, /assets/msp-partners-p-800.webp 800w, /assets/msp-partners-p-1080.webp 1080w, /assets/msp-partners.webp 1320w" className="features-img" />
                          </div>
                        </div>
                        <div className="features-row absolute slide2">
                          <div className="features-text slide2 wf-reveal" style={{"willChange": "transform, opacity", "transform": "translate3d(0px, 40px, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg)", "transformStyle": "preserve-3d", "opacity": "0", "--wf-op-dur": "1000ms", "--wf-op-delay": "0ms", "--wf-op-ease": "cubic-bezier(0.165,0.84,0.44,1)", "--wf-tr-dur": "1000ms", "--wf-tr-delay": "0ms", "--wf-tr-ease": "cubic-bezier(0.165,0.84,0.44,1)"}}>
                            <h4 className="h4_v2 color_rg">
                              Tech partners
                            </h4>
                            <div className="body-text-large smaller_tablet">
                              Collaborate with leading tech providers and leverage complementary strengths, streamline processes, and innovate faster. Tech partnerships with Mycroft enable seamless integration of diverse tools and platforms.
                            </div>
                          </div>
                          <div className="features-img-container slide2 wf-reveal" style={{"willChange": "transform, opacity", "transform": "translate3d(-40px, 0px, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg)", "transformStyle": "preserve-3d", "opacity": "0", "--wf-op-dur": "1000ms", "--wf-op-delay": "0ms", "--wf-op-ease": "cubic-bezier(0.165,0.84,0.44,1)", "--wf-tr-dur": "1000ms", "--wf-tr-delay": "0ms", "--wf-tr-ease": "cubic-bezier(0.165,0.84,0.44,1)"}}>
                            <img src="/assets/tech-partners.webp" loading="lazy" width="676" sizes="(max-width: 479px) 100vw, 676px" alt="" srcSet="/assets/tech-partners-p-500.webp 500w, /assets/tech-partners-p-800.webp 800w, /assets/tech-partners-p-1080.webp 1080w, /assets/tech-partners.webp 1320w" className="features-img" />
                          </div>
                        </div>
                        <div className="features-row absolute slide3">
                          <div className="features-text slide3 wf-reveal" style={{"willChange": "transform, opacity", "transform": "translate3d(0px, 40px, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg)", "transformStyle": "preserve-3d", "opacity": "0", "--wf-op-dur": "1000ms", "--wf-op-delay": "0ms", "--wf-op-ease": "cubic-bezier(0.165,0.84,0.44,1)", "--wf-tr-dur": "1000ms", "--wf-tr-delay": "0ms", "--wf-tr-ease": "cubic-bezier(0.165,0.84,0.44,1)"}}>
                            <h4 className="h4_v2 color_rg">
                              Auditors
                            </h4>
                            <div className="body-text-large smaller_tablet">
                              Join Mycroft’s network of verified auditors and work with customers that value real compliance and security an exceed industry standards. With Mycroft, you gain a strategic ally committed to safeguarding long-term resilience in an increasingly complex digital landscape.
                            </div>
                          </div>
                          <div className="features-img-container slide3 wf-reveal" style={{"willChange": "transform, opacity", "transform": "translate3d(-40px, 0px, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg)", "transformStyle": "preserve-3d", "opacity": "0", "--wf-op-dur": "1000ms", "--wf-op-delay": "0ms", "--wf-op-ease": "cubic-bezier(0.165,0.84,0.44,1)", "--wf-tr-dur": "1000ms", "--wf-tr-delay": "0ms", "--wf-tr-ease": "cubic-bezier(0.165,0.84,0.44,1)"}}>
                            <img src="/assets/auditors.webp" loading="lazy" width="676" sizes="(max-width: 479px) 100vw, 676px" alt="" srcSet="/assets/auditors-p-500.webp 500w, /assets/auditors-p-800.webp 800w, /assets/auditors-p-1080.webp 1080w, /assets/auditors.webp 1320w" className="features-img" />
                          </div>
                        </div>
                        <a href="#hero" className="btn-large color_velvet w-inline-block w--current">
                          <div className="btn-text-large color_mint">
                            Talk to our team
                          </div>
                          <img src="/assets/arrow-icon-mint-v1.svg" loading="lazy" style={{"transform": "translate3d(0px, 0px, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg)", "transformStyle": "preserve-3d"}} alt="" className="btn-arrow-large" />
                          <div className="hero-btn-shine darker" style={{"transform": "translate3d(-100%, 0px, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg)", "transformStyle": "preserve-3d"}}></div>
                        </a>
                      </section>
                      <div className="btm-tab">
                        <div className="shape-triangle _75_eg flipped mirrored smaller_mobile w-embed">
                          <svg version="1.1" baseProfile="basic" id="Triangle" xmlns="http://www.w3.org/2000/svg" xmlnsXlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 34 38" xmlSpace="preserve">
                            <path fill="currentColor" d="M0,0l34,38H0V0z"></path>
                          </svg>
                        </div>
                        <div className="tab-filler"></div>
                        <div className="shape-triangle _75_eg flipped smaller_mobile w-embed">
                          <svg version="1.1" baseProfile="basic" id="Triangle" xmlns="http://www.w3.org/2000/svg" xmlnsXlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 34 38" xmlSpace="preserve">
                            <path fill="currentColor" d="M0,0l34,38H0V0z"></path>
                          </svg>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </section>
            <section id="Features" className="section_v2 color_smoke">
              <div className="page-padding">
                <div className="padding-top xl">
                  <div className="container-medium">
                    <div className="container-small narrower_desktop">
                      <div className="container-flex vertical">
                        <h3 className="h3_v2 color_white text_center">
                          Read the latest insights from our experts
                        </h3>
                        <div className="padding-top xxxs">
                          <div className="text-dek-s text_40_grey text_center">
                            Stay secure with expert, data-driven resources to strengthen your security knowledge and ensure compliance confidence.
                          </div>
                        </div>
                      </div>
                    </div>
                    <div className="padding-top small">
                      <div className="padding-btm large">
                        <div className="container-flex space-between _3up_blog">
                          <div className="_3up-blog-wrapper w-dyn-list">
                            <div role="list" className="_3up-blog-grid w-dyn-items">
                              {partnershipsCollection1Data.map((item, i) => (
                                <PartnershipsCollection1 item={item} key={i} />
                              ))}
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </section>
          </div>
        </div>
      </main>
      <SiteFooter />
    </div>
  );
}
