import { ButtonLarge } from "@/app/_shared/ButtonLarge";
import { PartnershipsCollection1 } from "./PartnershipsCollection1";
import { partnershipsCollection1Data } from "./PartnershipsCollection1.data";
import { SiteNav } from "../../_shared/SiteNav";
import { SiteFooter } from "../../_shared/SiteFooter";
import { PartnershipsSection1 } from "./PartnershipsSection1";
import { PartnershipsSection2 } from "./PartnershipsSection2";
import { ScrollFeatureSlider, type ScrollFeatureSlide } from "../../_shared/ScrollFeatureSlider";

const partnerSlides: ScrollFeatureSlide[] = [
  {
    heading: "MSP partners",
    body: "Partnering with Mycroft positions you at the forefront of the cybersecurity landscape. With our cutting-edge technology and comprehensive suite of security solutions, you can enhance your offerings and deliver unparalleled protection to your clients.",
    image: {
      src: "/assets/msp-partners.webp",
      srcSet:
        "/assets/msp-partners-p-500.webp 500w, /assets/msp-partners-p-800.webp 800w, /assets/msp-partners-p-1080.webp 1080w, /assets/msp-partners.webp 1320w",
      sizes: "(max-width: 479px) 100vw, 676px",
      width: 676,
    },
  },
  {
    heading: "Tech partners",
    body: "Collaborate with leading tech providers and leverage complementary strengths, streamline processes, and innovate faster. Tech partnerships with Mycroft enable seamless integration of diverse tools and platforms.",
    image: {
      src: "/assets/tech-partners.webp",
      srcSet:
        "/assets/tech-partners-p-500.webp 500w, /assets/tech-partners-p-800.webp 800w, /assets/tech-partners-p-1080.webp 1080w, /assets/tech-partners.webp 1320w",
      sizes: "(max-width: 479px) 100vw, 676px",
      width: 676,
    },
  },
  {
    heading: "Auditors",
    body: "Join Mycroft’s network of verified auditors and work with customers that value real compliance and security an exceed industry standards. With Mycroft, you gain a strategic ally committed to safeguarding long-term resilience in an increasingly complex digital landscape.",
    image: {
      src: "/assets/auditors.webp",
      srcSet:
        "/assets/auditors-p-500.webp 500w, /assets/auditors-p-800.webp 800w, /assets/auditors-p-1080.webp 1080w, /assets/auditors.webp 1320w",
      sizes: "(max-width: 479px) 100vw, 676px",
      width: 676,
    },
  },
];

/**
 * Faithful React port of the Webflow https://www.mycroft.io/partnerships page. DOM + classes mirror
 * the original 1:1; global styling is in webflow-shared.css, page CSS
 * in partnerships.css. Generated by the Webflow Cloner agent.
 */
export function PartnershipsSnapshot() {
  return (
    <div className="page-wrapper u-minh-100vh color_rg">
      <div className="styles__global-embed-code w-embed"></div>
      <SiteNav />
      <main id="main" className="page-content">
        <PartnershipsSection1 />
        <PartnershipsSection2 />
        <div className="scroll-container-outer">
          <div className="scroll-container-inner">
            <section id="product-features" className="section_v2 split_background rg_40smoke">
              <div className="page-padding">
                <div className="container-xl">
                  <div className="padding-btm medium">
                    <div className="scroll-slider-outer">
                      <ScrollFeatureSlider id="audit-compliance" slides={partnerSlides}>
                        <ButtonLarge href="#hero" velvet shine current>
                          Talk to our team
                        </ButtonLarge>
                      </ScrollFeatureSlider>
                      <div className="btm-tab">
                        <div className="shape-triangle _75_eg flipped mirrored smaller_mobile w-embed">
                          <svg version="1.1" baseProfile="basic" id="Triangle" xmlns="http://www.w3.org/2000/svg" xmlnsXlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 34 38" xmlSpace="preserve">
                            <path fill="currentColor" d="M0,0l34,38H0V0z"></path>
                          </svg>
                        </div>
                        <div className="tab-filler"></div>
                        <div className="shape-triangle _75_eg flipped smaller_mobile w-embed">
                          <svg version="1.1" baseProfile="basic" id="Triangle" xmlns="http://www.w3.org/2000/svg" xmlnsXlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 34 38" xmlSpace="preserve">
                            <path fill="currentColor" d="M0,0l34,38H0V0z"></path>
                          </svg>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </section>
            <section id="Features" className="section_v2 color_smoke">
              <div className="page-padding">
                <div className="padding-top xl">
                  <div className="container-medium">
                    <div className="container-small narrower_desktop">
                      <div className="container-flex vertical">
                        <h3 className="h3_v2 color_white text_center">
                          Read the latest insights from our experts
                        </h3>
                        <div className="padding-top xxxs">
                          <div className="text-dek-s text_40_grey text_center">
                            Stay secure with expert, data-driven resources to strengthen your security knowledge and ensure compliance confidence.
                          </div>
                        </div>
                      </div>
                    </div>
                    <div className="padding-top small">
                      <div className="padding-btm large">
                        <div className="container-flex space-between _3up_blog">
                          <div className="_3up-blog-wrapper w-dyn-list">
                            <div role="list" className="_3up-blog-grid w-dyn-items">
                              {partnershipsCollection1Data.map((item, i) => (
                                <PartnershipsCollection1 item={item} key={i} />
                              ))}
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </section>
          </div>
        </div>
      </main>
      <SiteFooter />
    </div>
  );
}
