import { CtaSection } from "@/app/_shared/CtaSection";
import { SiteNav } from "../../../_shared/SiteNav";
import { SiteFooter } from "../../../_shared/SiteFooter";
import { FrameworksPipedaSection1 } from "./FrameworksPipedaSection1";
import { FrameworksPipedaSection2 } from "./FrameworksPipedaSection2";
import { FrameworksPipedaSection3 } from "./FrameworksPipedaSection3";
import { FrameworksPipedaSection4 } from "./FrameworksPipedaSection4";
import { FrameworksPipedaSection5 } from "./FrameworksPipedaSection5";
import { UnlockFrameworksSection } from "@/app/_shared/UnlockFrameworksSection";

/**
 * Faithful React port of the Webflow https://mycroft.io/frameworks/pipeda page. DOM + classes mirror
 * the original 1:1; global styling is in webflow-shared.css, page CSS
 * in frameworks-pipeda.css. Generated by the Webflow Cloner agent.
 */
export function FrameworksPipedaSnapshot() {
  return (
    <div className="page-wrapper u-minh-100vh color_rg">
      <div className="styles__global-embed-code w-embed"></div>
      <SiteNav />
      <main id="main" className="page-content">
        <FrameworksPipedaSection1 />
        <FrameworksPipedaSection2 />
        <FrameworksPipedaSection3 />
        <FrameworksPipedaSection4 />
        <UnlockFrameworksSection
          blurb="Achieve PIPEDA compliance with Mycroft and take advantage of the head start gained in other industry frameworks."
          dials={[
            { href: "/frameworks/gdpr", label: "GDPR", lottie: "/lottie/6a024deb258a325bf770f90a_Compliance-Dial_80.json" },
            { href: "/frameworks/soc2", label: "SOC 2", lottie: "/lottie/6a024deb4cd221655fea0562_Compliance-Dial_70.json" },
            { href: "/frameworks/iso27001", label: "ISO 27001", lottie: "/lottie/6a024deb6496e3c316c4eb82_Compliance-Dial_30.json" },
          ]}
        />
        <FrameworksPipedaSection5 />
        <CtaSection variant="lamp" />
      </main>
      <SiteFooter />
    </div>
  );
}
