import { ArrowTextLink } from "@/app/_shared/ArrowTextLink";

/** Section 2 of /frameworks/pipeda. Generated by the Webflow Cloner agent. */
export function FrameworksPipedaSection2() {
  return (
    <section id="fw-features" className="section_v2 tint_60eg overflow_hidden">
      <div className="pr-(--sizing--rem--2rem) pl-(--sizing--rem--2rem) ml-auto mr-auto relative max-portrait:pr-(--sizing--rem--1-25rem) max-portrait:pl-(--sizing--rem--1-25rem)">
        <div className="w-full max-w-156 ml-auto mr-auto max-tablet:w-[80%] max-tablet:max-w-128 max-landscape:w-[92%] max-portrait:w-full">
          <div className="w-full pt-(--sizing--rem--6rem) max-tablet:pt-(--sizing--rem--5rem) max-landscape:pt-(--sizing--rem--3-5rem) max-portrait:pt-(--sizing--rem--2-5rem)">
            <div className="container-flex vertical">
              <div className="eyebrow-label-small product">
                <div className="eyebrow-small color_rg">
                  Features
                </div>
              </div>
              <h2 className="h2_v2 color_rg text_center">
                Mycroft’s AI platform solutions for PIPEDA
              </h2>
              <div className="w-full pt-(--sizing--rem--1-25rem) max-tablet:pt-(--sizing--rem--1rem) max-landscape:pt-(--sizing--rem--0-75rem) max-portrait:pt-(--sizing--rem--0-5rem)">
                <div className="text-dek-l text_center">
                  A unified platform designed to operationalize PIPEDA requirements without adding internal workload.
                </div>
              </div>
            </div>
          </div>
        </div>
        <div className="w-full max-w-300 ml-auto mr-auto">
          <div className="w-full pt-(--sizing--rem--4-5rem) max-tablet:pt-(--sizing--rem--3-5rem) max-landscape:pt-(--sizing--rem--2-5rem) max-portrait:pt-(--sizing--rem--1-5rem)">
            <div className="w-full pb-(--sizing--rem--6rem) max-tablet:pb-(--sizing--rem--5rem) max-landscape:pb-(--sizing--rem--3-5rem) max-portrait:pb-(--sizing--rem--2-5rem)">
              <div className="product-container">
                <section id="app-security" className="product-feature">
                  <div className="product-text wf-reveal" style={{"willChange": "opacity, transform", "opacity": "0", "transform": "translate3d(-100px, 0px, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg)", "transformStyle": "preserve-3d", "--wf-op-dur": "1000ms", "--wf-op-delay": "0ms", "--wf-op-ease": "cubic-bezier(0.165,0.84,0.44,1)", "--wf-tr-dur": "1000ms", "--wf-tr-delay": "0ms", "--wf-tr-ease": "cubic-bezier(0.165,0.84,0.44,1)"}}>
                    <h4 className="h4_v2 color_rg">
                      App security
                    </h4>
                    <div className="body-text-medium">
                      Improve application security by identifying vulnerabilities, monitoring configurations, and supporting secure development practices across your software environment.
                    </div>
                    <ArrowTextLink href="/demo">
                      Book a demo
                    </ArrowTextLink>
                  </div>
                  <div className="product-feature-img wf-reveal" style={{"willChange": "opacity, transform", "opacity": "0", "transform": "translate3d(100px, 0px, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg)", "transformStyle": "preserve-3d", "--wf-op-dur": "1000ms", "--wf-op-delay": "0ms", "--wf-op-ease": "cubic-bezier(0.165,0.84,0.44,1)", "--wf-tr-dur": "1000ms", "--wf-tr-delay": "0ms", "--wf-tr-ease": "cubic-bezier(0.165,0.84,0.44,1)"}}>
                    <img src="/assets/app-security.webp" loading="lazy" width="680" sizes="(max-width: 479px) 100vw, 680px" alt="" srcSet="/assets/app-security-p-500.webp 500w, /assets/app-security-p-800.webp 800w, /assets/app-security-p-1080.webp 1080w, /assets/app-security.webp 1360w" className="fw-features-img" />
                  </div>
                </section>
                <section id="threat-management" className="product-feature even-child">
                  <div className="product-feature-img img-left wf-reveal" style={{"willChange": "opacity, transform", "opacity": "0", "transform": "translate3d(-100px, 0px, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg)", "transformStyle": "preserve-3d", "--wf-op-dur": "1000ms", "--wf-op-delay": "0ms", "--wf-op-ease": "cubic-bezier(0.165,0.84,0.44,1)", "--wf-tr-dur": "1000ms", "--wf-tr-delay": "0ms", "--wf-tr-ease": "cubic-bezier(0.165,0.84,0.44,1)"}}>
                    <img src="/assets/support-and-live-chat.webp" loading="lazy" width="680" sizes="(max-width: 479px) 100vw, 680px" alt="" srcSet="/assets/support-and-live-chat-p-500.webp 500w, /assets/support-and-live-chat-p-800.webp 800w, /assets/support-and-live-chat-p-1080.webp 1080w, /assets/support-and-live-chat.webp 1360w" className="fw-features-img" />
                  </div>
                  <div className="product-text text-right wf-reveal" style={{"willChange": "opacity, transform", "opacity": "0", "transform": "translate3d(100px, 0px, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg)", "transformStyle": "preserve-3d", "--wf-op-dur": "1000ms", "--wf-op-delay": "0ms", "--wf-op-ease": "cubic-bezier(0.165,0.84,0.44,1)", "--wf-tr-dur": "1000ms", "--wf-tr-delay": "0ms", "--wf-tr-ease": "cubic-bezier(0.165,0.84,0.44,1)"}}>
                    <h4 className="h4_v2 color_rg">
                      Support and live chat
                    </h4>
                    <div className="body-text-medium">
                      Access live support and hands-on guidance from compliance and security specialists to resolve issues quickly and keep your compliance program moving forward.
                    </div>
                    <ArrowTextLink href="/demo">
                      Book a demo
                    </ArrowTextLink>
                  </div>
                </section>
                <section id="agentic-ai" className="product-feature last-child">
                  <div className="product-text wf-reveal" style={{"willChange": "opacity, transform", "opacity": "0", "transform": "translate3d(-100px, 0px, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg)", "transformStyle": "preserve-3d", "--wf-op-dur": "1000ms", "--wf-op-delay": "0ms", "--wf-op-ease": "cubic-bezier(0.165,0.84,0.44,1)", "--wf-tr-dur": "1000ms", "--wf-tr-delay": "0ms", "--wf-tr-ease": "cubic-bezier(0.165,0.84,0.44,1)"}}>
                    <h4 className="h4_v2 color_rg">
                      Security training
                    </h4>
                    <div className="body-text-medium">
                      Deliver security awareness and compliance training programs that help employees reduce human risk while supporting audit and regulatory requirements.
                    </div>
                    <ArrowTextLink href="/demo">
                      Book a demo
                    </ArrowTextLink>
                  </div>
                  <div className="product-feature-img wf-reveal" style={{"willChange": "opacity, transform", "opacity": "0", "transform": "translate3d(100px, 0px, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg)", "transformStyle": "preserve-3d", "--wf-op-dur": "1000ms", "--wf-op-delay": "0ms", "--wf-op-ease": "cubic-bezier(0.165,0.84,0.44,1)", "--wf-tr-dur": "1000ms", "--wf-tr-delay": "0ms", "--wf-tr-ease": "cubic-bezier(0.165,0.84,0.44,1)"}}>
                    <img src="/assets/security-training.webp" loading="lazy" sizes="(max-width: 1360px) 100vw, 1360px" srcSet="/assets/security-training-p-500.webp 500w, /assets/security-training-p-800.webp 800w, /assets/security-training-p-1080.webp 1080w, /assets/security-training.webp 1360w" alt="" className="fw-features-img" />
                  </div>
                </section>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
