import type { Metadata } from "next";
import "./faqs.css";
import { FaqsSnapshot } from "./_snapshot/FaqsSnapshot";
import { WebflowInteractions } from "../_shared/WebflowInteractions";

export const metadata: Metadata = {
  title: "Mycroft FAQs | Answers to all of your frequently asked cybersecurity questions",
  description: "Find clear answers to common cybersecurity questions—best practices, threat prevention, compliance tips, and incident response guidance to help your team stay secure and confident.",
  openGraph: {
    title: "Mycroft FAQs | Answers to all of your frequently asked cybersecurity questions",
    description: "Find clear answers to common cybersecurity questions—best practices, threat prevention, compliance tips, and incident response guidance to help your team stay secure and confident.",
    type: "website",
    images: ["https://cdn.prod.website-files.com/6696985a1d3e81308169d89c/691377b9a58a0e8d017747d9_8668c63d464849b83c4205cc4c66f2dd_Mycroft%E2%80%93META-img%20faqs.webp"],
  },
  twitter: {
    card: "summary_large_image",
    title: "Mycroft FAQs | Answers to all of your frequently asked cybersecurity questions",
    description: "Find clear answers to common cybersecurity questions—best practices, threat prevention, compliance tips, and incident response guidance to help your team stay secure and confident.",
    images: ["https://cdn.prod.website-files.com/6696985a1d3e81308169d89c/691377b9a58a0e8d017747d9_8668c63d464849b83c4205cc4c66f2dd_Mycroft%E2%80%93META-img%20faqs.webp"],
  },
};

/**
 * /faqs: a faithful React rebuild of the Webflow page.
 * Generated by the Webflow Cloner agent from https://www.mycroft.io/faqs.
 */
export default function FaqsPage() {
  return (
    <>
      <FaqsSnapshot />
      <WebflowInteractions />
    </>
  );
}
