import type { Metadata } from "next";
import { FaqsPageContent } from "./_sections/FaqsPageContent";
import { WebflowInteractions } from "../_shared/WebflowInteractions";

export const metadata: Metadata = {
  title: "Mycroft FAQs | Answers to all of your frequently asked cybersecurity questions",
  description: "Find clear answers to common cybersecurity questions—best practices, threat prevention, compliance tips, and incident response guidance to help your team stay secure and confident.",
  openGraph: {
    title: "Mycroft FAQs | Answers to all of your frequently asked cybersecurity questions",
    description: "Find clear answers to common cybersecurity questions—best practices, threat prevention, compliance tips, and incident response guidance to help your team stay secure and confident.",
    type: "website",
    images: ["/assets/meta/mycroft-meta-img-faqs.webp"],
  },
  twitter: {
    card: "summary_large_image",
    title: "Mycroft FAQs | Answers to all of your frequently asked cybersecurity questions",
    description: "Find clear answers to common cybersecurity questions—best practices, threat prevention, compliance tips, and incident response guidance to help your team stay secure and confident.",
    images: ["/assets/meta/mycroft-meta-img-faqs.webp"],
  },
};

/**
 * /faqs: a faithful React rebuild of the Webflow page.
 * Generated by the Webflow Cloner agent from https://www.mycroft.io/faqs.
 */
export default function FaqsPage() {
  return (
    <>
      <FaqsPageContent />
      <WebflowInteractions />
    </>
  );
}
