/** Section 5 of /frameworks/hipaa. Generated by the Webflow Cloner agent. */
export function FrameworksHipaaSection5() {
  return (
    <section className="section_v2 color_smoke">
      <div className="page-padding">
        <div className="container-medium">
          <div className="padding-top medium">
            <div className="padding-btm large">
              <img src="/assets/faq-notchlabel-desktop.svg" loading="lazy" alt="" className="faq-notch-desktop" />
              <img src="/assets/faq-notchlabel-mobile.svg" loading="lazy" alt="" className="faq-notch-mobile" />
              <div className="container-flex faq_container">
                <div className="faq-hed-flex">
                  <h3 className="h3_v2 color_white">
                    Frequently asked questions
                  </h3>
                  <div className="text-dek-l text_40eg">
                    Answers that help customers with HIPAA compliance
                  </div>
                </div>
                <div className="faq-item first_child">
                  <div className="custom-dropdown">
                    <div className="top-row">
                      <div className="question-container">
                        <div className="h5 color_white">
                          What is HIPAA?
                        </div>
                      </div>
                      <div className="state-toggle">
                        <div className="plus-container" style={{"width": "24px", "height": "24px"}}>
                          <div className="plus _75_mint"></div>
                        </div>
                        <div className="minus _75_mint"></div>
                      </div>
                    </div>
                  </div>
                  <div className="answer-container">
                    <div className="body-text-medium color_40eg faq_answer" style={{"height": "0px"}}>
                      HIPAA (Health Insurance Portability and Accountability Act) is a U.S. regulation that governs the protection of protected health information (PHI).
                    </div>
                  </div>
                  <div className="faq-spacer-expand no_opacity" style={{"height": "0px"}}></div>
                  <div className="faq-item-btm-hr"></div>
                </div>
                <div className="faq-item">
                  <div className="custom-dropdown">
                    <div className="top-row">
                      <div className="question-container">
                        <div className="h5 color_white">
                          Who needs to comply with HIPAA?
                        </div>
                      </div>
                      <div className="state-toggle">
                        <div className="plus-container" style={{"width": "24px", "height": "24px"}}>
                          <div className="plus _75_mint"></div>
                        </div>
                        <div className="minus _75_mint"></div>
                      </div>
                    </div>
                  </div>
                  <div className="answer-container">
                    <div className="body-text-medium color_40eg faq_answer" style={{"height": "0px"}}>
                      Healthcare providers, payers, and any vendors or partners that handle PHI.
                    </div>
                  </div>
                  <div className="faq-spacer-expand no_opacity" style={{"height": "0px"}}></div>
                  <div className="faq-item-btm-hr"></div>
                </div>
                <div className="faq-item">
                  <div className="custom-dropdown">
                    <div className="top-row">
                      <div className="question-container">
                        <div className="h5 color_white">
                          What is PHI?
                        </div>
                      </div>
                      <div className="state-toggle">
                        <div className="plus-container" style={{"width": "24px", "height": "24px"}}>
                          <div className="plus _75_mint"></div>
                        </div>
                        <div className="minus _75_mint"></div>
                      </div>
                    </div>
                  </div>
                  <div className="answer-container">
                    <div className="body-text-medium color_40eg faq_answer" style={{"height": "0px"}}>
                      Protected health information includes any data that identifies a patient and relates to their health, treatment, or payment.
                    </div>
                  </div>
                  <div className="faq-spacer-expand no_opacity" style={{"height": "0px"}}></div>
                  <div className="faq-item-btm-hr"></div>
                </div>
                <div className="faq-item">
                  <div className="custom-dropdown">
                    <div className="top-row">
                      <div className="question-container">
                        <div className="h5 color_white">
                          What are HIPAA safeguards?
                        </div>
                      </div>
                      <div className="state-toggle">
                        <div className="plus-container" style={{"width": "24px", "height": "24px"}}>
                          <div className="plus _75_mint"></div>
                        </div>
                        <div className="minus _75_mint"></div>
                      </div>
                    </div>
                  </div>
                  <div className="answer-container">
                    <div className="body-text-medium color_40eg faq_answer" style={{"height": "0px"}}>
                      HIPAA requires administrative, physical, and technical safeguards to protect sensitive health data.
                    </div>
                  </div>
                  <div className="faq-spacer-expand no_opacity" style={{"height": "0px"}}></div>
                  <div className="faq-item-btm-hr"></div>
                </div>
                <div className="faq-item">
                  <div className="custom-dropdown">
                    <div className="top-row">
                      <div className="question-container">
                        <div className="h5 color_white">
                          How does Mycroft help with HIPAA?
                        </div>
                      </div>
                      <div className="state-toggle">
                        <div className="plus-container" style={{"width": "24px", "height": "24px"}}>
                          <div className="plus _75_mint"></div>
                        </div>
                        <div className="minus _75_mint"></div>
                      </div>
                    </div>
                  </div>
                  <div className="answer-container">
                    <div className="body-text-medium color_40eg faq_answer" style={{"height": "0px"}}>
                      Mycroft helps you implement safeguards, manage policies, and maintain audit readiness without overloading your team.
                    </div>
                  </div>
                  <div className="faq-spacer-expand no_opacity" style={{"height": "0px"}}></div>
                  <div className="faq-item-btm-hr last_child"></div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
