import { CtaSection } from "@/app/_shared/CtaSection";
import { SiteNav } from "../../../_shared/SiteNav";
import { SiteFooter } from "../../../_shared/SiteFooter";
import { FrameworksHipaaSection1 } from "./FrameworksHipaaSection1";
import { FrameworksHipaaSection2 } from "./FrameworksHipaaSection2";
import { FrameworksHipaaSection3 } from "./FrameworksHipaaSection3";
import { FrameworksHipaaSection4 } from "./FrameworksHipaaSection4";
import { FrameworksHipaaSection5 } from "./FrameworksHipaaSection5";
import { UnlockFrameworksSection } from "@/app/_shared/UnlockFrameworksSection";

/**
 * Faithful React port of the Webflow https://mycroft.io/frameworks/hipaa page. DOM + classes mirror
 * the original 1:1; global styling is in webflow-shared.css, page CSS
 * in frameworks-hipaa.css. Generated by the Webflow Cloner agent.
 */
export function FrameworksHipaaSnapshot() {
  return (
    <div className="page-wrapper u-minh-100vh color_rg">
      <div className="styles__global-embed-code w-embed"></div>
      <SiteNav />
      <main id="main" className="page-content">
        <FrameworksHipaaSection1 />
        <FrameworksHipaaSection2 />
        <FrameworksHipaaSection3 />
        <FrameworksHipaaSection4 />
        <UnlockFrameworksSection
          blurb="Achieve HIPAA compliance with Mycroft and take advantage of the head start gained in other industry frameworks."
          dials={[
            { href: "/frameworks/soc2", label: "SOC 2", lottie: "/lottie/6a024deb018a84831eff1a49_Compliance-Dial_25.json" },
            { href: "/frameworks/iso42001", label: "ISO 42001", lottie: "/lottie/69ebcb3ae646a22194c4af4d_Compliance-Dial_65.json" },
            { href: "/frameworks/cmmc", label: "CMMC", lottie: "/lottie/6a024deb473b0519f94adf43_Compliance-Dial_20.json" },
          ]}
        />
        <FrameworksHipaaSection5 />
        <CtaSection variant="lamp" />
      </main>
      <SiteFooter />
    </div>
  );
}
