import Link from "next/link";
import { DotLottiePlayer } from "../../../_shared/DotLottiePlayer";
import { SiteNav14 } from "../../../_shared/SiteNav14";
import { SiteFooter } from "../../../_shared/SiteFooter";
import { FrameworksHipaaSection1 } from "./FrameworksHipaaSection1";
import { FrameworksHipaaSection2 } from "./FrameworksHipaaSection2";
import { FrameworksHipaaSection3 } from "./FrameworksHipaaSection3";
import { FrameworksHipaaSection4 } from "./FrameworksHipaaSection4";
import { FrameworksHipaaSection5 } from "./FrameworksHipaaSection5";
import { FrameworksHipaaSection6 } from "./FrameworksHipaaSection6";

/**
 * Faithful React port of the Webflow https://mycroft.io/frameworks/hipaa page. DOM + classes mirror
 * the original 1:1; global styling is in webflow-shared.css, page CSS
 * in frameworks-hipaa.css. Generated by the Webflow Cloner agent.
 */
export function FrameworksHipaaSnapshot() {
  return (
    <div className="page-wrapper u-minh-100vh color_rg">
      <div className="styles__global-embed-code w-embed"></div>
      <SiteNav14 />
      <main id="main" className="page-content">
        <FrameworksHipaaSection1 />
        <FrameworksHipaaSection2 />
        <FrameworksHipaaSection3 />
        <FrameworksHipaaSection4 />
        <div className="negative-margin-wrapper reduce_top">
          <section id="Features" className="section_v2 color_smoke">
            <div className="page-padding">
              <div className="padding-top xl">
                <div className="container-medium tab_mob_100">
                  <div className="container-small narrower_desktop">
                    <div className="container-flex vertical">
                      <h2 className="h2_v2 color_white text_center">
                        Unlock other frameworks
                      </h2>
                      <div className="padding-top xxxs">
                        <div className="text-dek-m color_40eg text_center">
                          Achieve HIPAA compliance with Mycroft and take advantage of the head start gained in other industry frameworks.
                        </div>
                      </div>
                    </div>
                  </div>
                  <div className="padding-top small">
                    <div className="padding-btm large">
                      <div className="container-flex vertical">
                        <div className="w-layout-grid fw-dials-grid">
                          <Link href="/frameworks/soc2" className="fw-tile-link w-inline-block">
                            <div className="fw-dial-tile">
                              <div className="fw-vertical-hr"></div>
                              <div style={{"opacity": "0"}} className="dial-tile-background"></div>
                              <div style={{"opacity": "0"}} className="dial-tile-stroke"></div>
                              <div data-is-ix2-target="1" className="fw-dial-lottie" data-animation-type="lottie" data-src="https://cdn.prod.website-files.com/6696985a1d3e81308169d89c/6a024deb018a84831eff1a49_Compliance-Dial_25.json" data-loop="0" data-direction="1" data-autoplay="0" data-renderer="svg" data-default-duration="0" data-duration="0" data-loading="eager">
                                <DotLottiePlayer src="/lottie/6a024deb018a84831eff1a49_Compliance-Dial_25.json" loop={false} autoplay={false} />
                              </div>
                              <div className="body-text-small color_white font_600 underline fw_dial">
                                SOC 2 →
                              </div>
                            </div>
                          </Link>
                          <Link href="/frameworks/iso42001" className="fw-tile-link w-inline-block">
                            <div className="fw-dial-tile">
                              <div className="fw-vertical-hr"></div>
                              <div style={{"opacity": "0"}} className="dial-tile-background"></div>
                              <div style={{"opacity": "0"}} className="dial-tile-stroke"></div>
                              <div data-is-ix2-target="1" className="fw-dial-lottie" data-animation-type="lottie" data-src="https://cdn.prod.website-files.com/6696985a1d3e81308169d89c/69ebcb3ae646a22194c4af4d_Compliance-Dial_65.json" data-loop="0" data-direction="1" data-autoplay="0" data-renderer="svg" data-default-duration="0" data-duration="0" data-loading="eager">
                                <DotLottiePlayer src="/lottie/69ebcb3ae646a22194c4af4d_Compliance-Dial_65.json" loop={false} autoplay={false} />
                              </div>
                              <div className="body-text-small color_white font_600 underline fw_dial">
                                ISO 42001 →
                              </div>
                            </div>
                          </Link>
                          <Link href="/frameworks/cmmc" className="fw-tile-link w-inline-block">
                            <div className="fw-dial-tile">
                              <div style={{"opacity": "0"}} className="dial-tile-background"></div>
                              <div style={{"opacity": "0"}} className="dial-tile-stroke"></div>
                              <div data-is-ix2-target="1" className="fw-dial-lottie" data-animation-type="lottie" data-src="https://cdn.prod.website-files.com/6696985a1d3e81308169d89c/6a024deb473b0519f94adf43_Compliance-Dial_20.json" data-loop="0" data-direction="1" data-autoplay="0" data-renderer="svg" data-default-duration="0" data-duration="0" data-loading="eager">
                                <DotLottiePlayer src="/lottie/6a024deb473b0519f94adf43_Compliance-Dial_20.json" loop={false} autoplay={false} />
                              </div>
                              <div className="body-text-small color_white font_600 underline fw_dial">
                                CMMC →
                              </div>
                            </div>
                          </Link>
                        </div>
                        <div className="container-flex vertical center">
                          <div className="padding-top small flex_center">
                            <Link href="/demo" className="btn-large w-inline-block">
                              <div className="btn-text-large">
                                Book a demo
                              </div>
                              <img src="/assets/arrow-icon-v2.svg" loading="lazy" style={{"transform": "translate3d(0px, 0px, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg)", "transformStyle": "preserve-3d"}} alt="" className="btn-arrow-large" />
                              <div style={{"transform": "translate3d(-100%, 0px, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg)", "transformStyle": "preserve-3d"}} className="hero-btn-shine"></div>
                            </Link>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </section>
        </div>
        <FrameworksHipaaSection5 />
        <FrameworksHipaaSection6 />
      </main>
      <SiteFooter />
    </div>
  );
}
