import { ButtonLarge } from "@/app/_shared/ButtonLarge";

/** Section 1 of /frameworks/hipaa. Generated by the Webflow Cloner agent. */
export function FrameworksHipaaSection1() {
  return (
    <section id="fw-hero" className="section-hero white_background">
      <div className="page-padding">
        <div className="container-large">
          <div className="container-flex fw_hero">
            <div className="container-flex vertical fw_hero_left">
              <div className="eyebrow-label-medium">
                <div className="eyebrow-medium color_rg">
                  Compliance
                </div>
              </div>
              <div className="hero-copy hero_padding_med">
                <h1 className="h3_v2 color_rg">
                  HIPAA compliance, built for healthcare organizations
                </h1>
                <div className="text-dek-m">
                  Mycroft’s Risk Operations Center removes the operational burden, helping you meet HIPAA requirements and protect sensitive health information with confidence.
                </div>
              </div>
              <div className="padding-top xxs">
                <div className="container-flex center_mobile">
                  <ButtonLarge href="/demo" shine>
                    Book a demo
                  </ButtonLarge>
                </div>
              </div>
            </div>
            <div className="fw-hero-circle">
              <img src="/assets/hipaa-badge-2.svg" loading="lazy" alt="" className="fw-hero-badge-img" style={{"willChange": "transform", "transform": "translate3d(8px, 8px, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg)", "transformStyle": "preserve-3d"}} />
              <div className="fw-hero-dots" style={{"willChange": "transform", "transform": "translate3d(-4px, -4px, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg)", "transformStyle": "preserve-3d"}}></div>
            </div>
          </div>
        </div>
      </div>
      <div className="split-background">
        <div className="page-padding">
          <div className="container-xl compliance_features">
            <div className="container-small">
              <div className="padding-top large">
                <div className="padding-btm small">
                  <div className="container-flex vertical center">
                    <div className="padding-btm xsmall">
                      <div className="container-flex vertical center text_center">
                        <h3 className="h3_v2 color_white">
                          Why HIPAA matters to you
                        </h3>
                        <div className="padding-top xxs">
                          <div className="text-dek-m color_40eg">
                            HIPAA compliance ensures the protection of protected health information (PHI), reduces regulatory risk, and enables you to work with healthcare providers and partners.
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div className="container-large">
              <div className="w-layout-grid features-3up frameworks">
                <div className="feature-item frameworks" style={{"opacity": "0"}}>
                  <img src="/assets/userlock-icon.svg" loading="lazy" width="38" alt="" className="feature-icon" />
                  <div className="container-flex vertical center text_center">
                    <div className="h6 color_mint">
                      Protect sensitive health data
                    </div>
                    <div className="padding-top xxxs">
                      <div className="body-text-small color_mint smaller">
                        HIPAA establishes strict safeguards for PHI, reducing the risk of breaches and unauthorized access.
                      </div>
                    </div>
                  </div>
                </div>
                <div className="feature-item frameworks" style={{"opacity": "0"}}>
                  <img src="/assets/warning-icon.svg" loading="lazy" width="38" alt="" className="feature-icon" />
                  <div className="container-flex vertical center text_center">
                    <div className="h6 color_mint">
                      Avoid costly penalties
                    </div>
                    <div className="padding-top xxxs">
                      <div className="body-text-small color_mint smaller">
                        HIPAA violations can result in significant financial penalties and reputational damage. Strong compliance reduces exposure.
                      </div>
                    </div>
                  </div>
                </div>
                <div className="feature-item frameworks" style={{"opacity": "0"}}>
                  <img src="/assets/hands-icon.svg" loading="lazy" width="38" alt="" className="feature-icon" />
                  <div className="container-flex vertical center text_center">
                    <div className="h6 color_mint">
                      Enable healthcare partnerships
                    </div>
                    <div className="padding-top xxxs">
                      <div className="body-text-small color_mint smaller">
                        Healthcare providers, payers, and partners require HIPAA compliance before engaging with vendors and platforms.
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div className="padding-btm xsmall">
                <div className="container-flex vertical center">
                  <ButtonLarge href="/demo" shine>
                    Book a demo
                  </ButtonLarge>
                </div>
              </div>
            </div>
          </div>
          <div className="btm-tab narrower">
            <div className="shape-triangle color_rg flipped mirrored smaller_mobile w-embed">
              <svg version="1.1" baseProfile="basic" id="Triangle" xmlns="http://www.w3.org/2000/svg" xmlnsXlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 34 38" xmlSpace="preserve">
                <path fill="currentColor" d="M0,0l34,38H0V0z"></path>
              </svg>
            </div>
            <div className="tab-filler color_rg"></div>
            <div className="shape-triangle color_rg flipped smaller_mobile w-embed">
              <svg version="1.1" baseProfile="basic" id="Triangle" xmlns="http://www.w3.org/2000/svg" xmlnsXlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 34 38" xmlSpace="preserve">
                <path fill="currentColor" d="M0,0l34,38H0V0z"></path>
              </svg>
            </div>
          </div>
        </div>
      </div>
      <div className="hero-background fw_grid"></div>
      <div className="hero-background cs_noise"></div>
    </section>
  );
}
