import type { Metadata } from "next";
import { ThankYouPageContent } from "./_sections/thank-you-page-content";
import { WebflowInteractions } from "@/components/webflow-interactions";

export const metadata: Metadata = {
  title: "Thank you",
  openGraph: {
    title: "Thank you",
  },
  twitter: {
    title: "Thank you",
  },
};

/**
 * /thank-you: a faithful React rebuild of the Webflow page.
 * Generated by the Webflow Cloner agent from https://www.mycroft.io/thank-you.
 */
export default function ThankYouPage() {
  return (
    <>
      <ThankYouPageContent />
      <WebflowInteractions />
    </>
  );
}
