import { ProductSlider } from "../_shared/ProductSlider";
import type { ProductSlide } from "../_shared/ProductSlideCard";

const SLIDES: ProductSlide[] = [
  {
    title: "Audit & compliance agents",
    body: "Mycroft AI Agents continuously monitor your compliance posture against enterprise requirements for SOC 2, ISO 27001, GDPR, HIPAA, CMMC, FedRAMP, FedRAMP 20X and more. All integrated and cross-mapped to reduce unnecessary overhead.",
    href: "/product",
    lottieSrc: "/lottie/68cb8abc1880145b8880ee64_AuditCompliance_v2.lottie",
    image: 1,
  },
  {
    title: "Cloud security",
    body: "Gain deeper insights into your cloud security, focusing on key areas such as identity and access management, misconfigurations, secrets management, and database architecture – empowering you to scale with confidence.",
    href: "/product",
    lottieSrc: "/lottie/68cb8bf5fbee380cfd1cc505_CloudSecurity_v2.lottie",
    image: 2,
  },
  {
    title: "Application security",
    body: "Monitor your application attack surface through Mycroft to find what hackers are looking for to exploit your application. Identify, triage, and continually monitor your potential threats to ensure your application is protected from threats 24/7.",
    href: "/product",
    lottieSrc: "/lottie/68cb8c56ad76da070bd27894_AppSecurity_v2.lottie",
    image: 3,
  },
  {
    title: "Device management",
    body: "Monitor and manage your endpoints to ensure security and compliance stays strong across all devices through managing your encryption, malware, and more.",
    href: "/product",
    lottieSrc: "/lottie/68cb8c6691e1f0cbbf1d9550_ThreatManagement_v2.lottie",
    image: 4,
  },
  {
    title: "Third-Party Risk Management",
    body: "Our platform provides visibility and control over external vulnerabilities, helping your organization stay secure, compliant, and protected from outside threats.",
    href: "/product",
    lottieSrc: "/lottie/68cb8c8fe1d100b0bcefb3d1_AgenticAI_v2.lottie",
    image: 5,
  },
];

/** Section 7 of /home. Generated by the Webflow Cloner agent. */
export function HomeSection7() {
  return (
    <section id="platform" className="section_v2 tint_40eg overflow_hidden">
      <div className="page-padding">
        <div className="container-medium product_cta">
          <div className="padding-top xxl">
            <div className="container-flex vertical">
              <h2 className="h2_v2 color_rg text_center">
                Mycroft’s versatility:
                <br />
                your security stack in
                <span className="no-wrap">
                  5 pillars
                </span>
              </h2>
              <div className="padding-top xxs">
                <div className="text-dek-s text_center">
                  Mycroft is the only platform that combines your entire security stack and gets you compliant while automating your workflows. All powered by your AI Security and Compliance Officer.
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div className="padding-top medium">
        <div className="padding-btm xl">
          <div className="custom-page-padding">
            <div className="container-large">
              <ProductSlider slides={SLIDES} />
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
