import { ComplianceSection } from "../_shared/ComplianceSection";

/** Section 6 of /home. Generated by the Webflow Cloner agent. */
export function HomeSection6() {
  return (
    <section id="compliance" className="section_v2">
      <div className="overlap-top">
        <div className="overlap-block"></div>
        <div className="container-large">
          <div className="overlap-block top_block"></div>
        </div>
        <div className="overlap-block transparent"></div>
      </div>
      <div className="section-overlap">
        <ComplianceSection />
      </div>
      <div className="overlap-btm">
        <div className="overlap-block transparent"></div>
        <div className="container-large">
          <div className="overlap-block btm_block"></div>
        </div>
        <div className="overlap-block"></div>
      </div>
    </section>
  );
}
