import { SiteNav } from "../_shared/SiteNav";
import { SiteFooter } from "../_shared/SiteFooter";
import { HomeSection1 } from "./HomeSection1";
import { HomeSection2 } from "./HomeSection2";
import { HomeSection3 } from "./HomeSection3";
import { HomeSection4 } from "./HomeSection4";
import { HomeSection5 } from "./HomeSection5";
import { HomeSection6 } from "./HomeSection6";
import { HomeSection7 } from "./HomeSection7";
import { HomeSection8 } from "./HomeSection8";
import { HomeSection9 } from "./HomeSection9";
import { HomeSection10 } from "./HomeSection10";

/**
 * Faithful React port of the Webflow https://www.mycroft.io page. DOM + classes mirror
 * the original 1:1; global styling is in webflow-shared.css, page CSS
 * in home.css. Generated by the Webflow Cloner agent.
 */
export function HomeSnapshot() {
  return (
    <div className="page-wrapper u-minh-100vh">
      <div className="styles__global-embed-code w-embed"></div>
      <div className="navigation-trim_container">
        <div>
          Announcing our Seed raise of $XMM USD
        </div>
        <a href="#">
          View article -{'>'}
        </a>
      </div>
      <SiteNav />
      <main id="main" className="page-content">
        <HomeSection1 />
        <HomeSection2 />
        <HomeSection3 />
        <HomeSection4 />
        <HomeSection5 />
        <HomeSection6 />
        <HomeSection7 />
        <HomeSection8 />
        <HomeSection9 />
        <HomeSection10 />
      </main>
      <SiteFooter />
    </div>
  );
}
