import { HomeCollection1 } from "./HomeCollection1";
import { homeCollection1Data } from "./HomeCollection1.data";
/** Section 9 of /home. Generated by the Webflow Cloner agent. */
export function HomeSection9() {
  return (
    <section id="Features" className="section_v2 color_smoke">
      <div className="page-padding">
        <div className="padding-top xl">
          <div className="container-medium">
            <div className="container-small narrower_desktop">
              <div className="container-flex vertical">
                <h3 className="h3_v2 color_white text_center">
                  Read the latest insights from our experts
                </h3>
                <div className="padding-top xxxs">
                  <div className="text-dek-s text_40_grey text_center">
                    Stay secure with expert, data-driven resources to strengthen your security knowledge and ensure compliance confidence.
                  </div>
                </div>
              </div>
            </div>
            <div className="padding-top small">
              <div className="padding-btm large">
                <div className="container-flex space-between _3up_blog">
                  <div className="_3up-blog-wrapper w-dyn-list">
                    <div role="list" className="_3up-blog-grid w-dyn-items">
                      {homeCollection1Data.map((item, i) => (
                        <HomeCollection1 item={item} key={i} />
                      ))}
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
