import Link from "next/link";
import { DotLottiePlayer } from "../_shared/DotLottiePlayer";

/** Section 7 of /home. Generated by the Webflow Cloner agent. */
export function HomeSection7() {
  return (
    <section id="platform" className="section_v2 tint_40eg overflow_hidden">
      <div className="page-padding">
        <div className="container-medium product_cta">
          <div className="padding-top xxl">
            <div className="container-flex vertical">
              <h2 className="h2_v2 color_rg text_center">
                Mycroft’s versatility:
                <br />
                your security stack in
                <span className="no-wrap">
                  5 pillars
                </span>
              </h2>
              <div className="padding-top xxs">
                <div className="text-dek-s text_center">
                  Mycroft is the only platform that combines your entire security stack and gets you compliant while automating your workflows. All powered by your AI Security and Compliance Officer.
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div className="padding-top medium">
        <div className="padding-btm xl">
          <div className="custom-page-padding">
            <div className="container-large">
              <div className="product-slider-wrapper">
                <div data-delay="8000" data-animation="fade" className="product-slider disable-pointer w-slider" data-autoplay="true" data-easing="ease" data-hide-arrows="false" data-disable-swipe="false" data-autoplay-limit="0" data-nav-spacing="3" data-duration="750" data-infinite="true" role="region" aria-label="carousel">
                  <div className="slider-mask w-slider-mask" id="w-slider-mask-0">
                    <div className="w-slide" aria-label="1 of 5" role="group" style={{"transition": "all", "transform": "translateX(0px)", "opacity": "1"}}>
                      <div className="slide__wrapper">
                        <div className="slider__left-pane">
                          <div className="slide-text-wrapper">
                            <h4 className="h4_v2">
                              <strong>
                                Audit & compliance agents
                              </strong>
                            </h4>
                            <div className="body-text-medium">
                              Mycroft AI Agents continuously monitor your compliance posture against enterprise requirements for SOC 2, ISO 27001, GDPR, HIPAA, CMMC, FedRAMP, FedRAMP 20X and more. All integrated and cross-mapped to reduce unnecessary overhead.
                            </div>
                            <div className="padding-top xxs">
                              <div className="container-flex">
                                <Link href="/product" className="btn-large w-inline-block">
                                  <div className="btn-text-large">
                                    Learn more
                                  </div>
                                  <img src="/assets/arrow-icon-v2.svg" loading="lazy" style={{"transform": "translate3d(0px, 0px, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg)", "transformStyle": "preserve-3d"}} alt="" className="btn-arrow-large" />
                                </Link>
                              </div>
                            </div>
                          </div>
                        </div>
                        <div className="slider__right-pane image-1">
                          <div className="slider__image-cover" style={{"width": "600px", "height": "0%"}}></div>
                          <div className="slider-lottie" data-animation-type="lottie" data-src="https://cdn.prod.website-files.com/6696985a1d3e81308169d89c/68cb8abc1880145b8880ee64_AuditCompliance_v2.lottie" data-loop="1" data-direction="1" data-autoplay="1" data-is-ix2-target="0" data-renderer="svg" data-default-duration="0" data-duration="0" data-loading="eager" style={{"opacity": "1"}}>
                            <DotLottiePlayer src="/lottie/68cb8abc1880145b8880ee64_AuditCompliance_v2.lottie" loop={true} autoplay={true} />
                          </div>
                        </div>
                      </div>
                    </div>
                    <div className="w-slide" aria-label="2 of 5" role="group" aria-hidden="true" style={{"transition": "all", "transform": "translateX(0px)", "opacity": "1", "visibility": "hidden"}}>
                      <div className="slide__wrapper" aria-hidden="true">
                        <div className="slider__left-pane" aria-hidden="true">
                          <div className="slide-text-wrapper" aria-hidden="true">
                            <h4 className="h4_v2" aria-hidden="true">
                              <strong aria-hidden="true">
                                Cloud security
                              </strong>
                            </h4>
                            <div className="body-text-medium" aria-hidden="true">
                              Gain deeper insights into your cloud security, focusing on key areas such as identity and access management, misconfigurations, secrets management, and database architecture – empowering you to scale with confidence.
                            </div>
                            <div className="padding-top xxs" aria-hidden="true">
                              <div className="container-flex" aria-hidden="true">
                                <Link href="/product" className="btn-large w-inline-block" tabIndex={-1} aria-hidden="true">
                                  <div className="btn-text-large" aria-hidden="true">
                                    Learn more
                                  </div>
                                  <img src="/assets/arrow-icon-v2.svg" loading="lazy" style={{"transform": "translate3d(0px, 0px, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg)", "transformStyle": "preserve-3d"}} alt="" className="btn-arrow-large" aria-hidden="true" />
                                </Link>
                              </div>
                            </div>
                          </div>
                        </div>
                        <div className="slider__right-pane image-2" aria-hidden="true">
                          <div className="slider__image-cover" aria-hidden="true" style={{"width": "600px", "height": "100%"}}></div>
                          <div className="slider-lottie" data-animation-type="lottie" data-src="https://cdn.prod.website-files.com/6696985a1d3e81308169d89c/68cb8bf5fbee380cfd1cc505_CloudSecurity_v2.lottie" data-loop="1" data-direction="1" data-autoplay="1" data-is-ix2-target="0" data-renderer="svg" data-default-duration="0" data-duration="0" data-loading="eager" style={{"opacity": "0"}} aria-hidden="true">
                            <DotLottiePlayer src="/lottie/68cb8bf5fbee380cfd1cc505_CloudSecurity_v2.lottie" loop={true} autoplay={true} />
                          </div>
                        </div>
                      </div>
                    </div>
                    <div className="w-slide" aria-label="3 of 5" role="group" aria-hidden="true" style={{"transition": "all", "transform": "translateX(0px)", "opacity": "1", "visibility": "hidden"}}>
                      <div className="slide__wrapper" aria-hidden="true">
                        <div className="slider__left-pane" aria-hidden="true">
                          <div className="slide-text-wrapper" aria-hidden="true">
                            <h4 className="h4_v2" aria-hidden="true">
                              <strong aria-hidden="true">
                                Application security
                              </strong>
                            </h4>
                            <div className="body-text-medium" aria-hidden="true">
                              Monitor your application attack surface through Mycroft to find what hackers are looking for to exploit your application. Identify, triage, and continually monitor your potential threats to ensure your application is protected from threats 24/7.
                            </div>
                            <div className="padding-top xxs" aria-hidden="true">
                              <div className="container-flex" aria-hidden="true">
                                <Link href="/product" className="btn-large w-inline-block" tabIndex={-1} aria-hidden="true">
                                  <div className="btn-text-large" aria-hidden="true">
                                    Learn more
                                  </div>
                                  <img src="/assets/arrow-icon-v2.svg" loading="lazy" style={{"transform": "translate3d(0px, 0px, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg)", "transformStyle": "preserve-3d"}} alt="" className="btn-arrow-large" aria-hidden="true" />
                                </Link>
                              </div>
                            </div>
                          </div>
                        </div>
                        <div className="slider__right-pane image-3" aria-hidden="true">
                          <div className="slider__image-cover" aria-hidden="true" style={{"width": "600px", "height": "100%"}}></div>
                          <div className="slider-lottie" data-animation-type="lottie" data-src="https://cdn.prod.website-files.com/6696985a1d3e81308169d89c/68cb8c56ad76da070bd27894_AppSecurity_v2.lottie" data-loop="1" data-direction="1" data-autoplay="1" data-is-ix2-target="0" data-renderer="svg" data-default-duration="0" data-duration="0" data-loading="eager" style={{"opacity": "0"}} aria-hidden="true">
                            <DotLottiePlayer src="/lottie/68cb8c56ad76da070bd27894_AppSecurity_v2.lottie" loop={true} autoplay={true} />
                          </div>
                        </div>
                      </div>
                    </div>
                    <div className="w-slide" aria-label="4 of 5" role="group" aria-hidden="true" style={{"transition": "all", "transform": "translateX(0px)", "opacity": "1", "visibility": "hidden"}}>
                      <div className="slide__wrapper" aria-hidden="true">
                        <div className="slider__left-pane" aria-hidden="true">
                          <div className="slide-text-wrapper" aria-hidden="true">
                            <h4 className="h4_v2" aria-hidden="true">
                              <strong aria-hidden="true">
                                Device management
                              </strong>
                            </h4>
                            <div className="body-text-medium" aria-hidden="true">
                              Monitor and manage your endpoints to ensure security and compliance stays strong across all devices through managing your encryption, malware, and more.
                            </div>
                            <div className="padding-top xxs" aria-hidden="true">
                              <div className="container-flex" aria-hidden="true">
                                <Link href="/product" className="btn-large w-inline-block" tabIndex={-1} aria-hidden="true">
                                  <div className="btn-text-large" aria-hidden="true">
                                    Learn more
                                  </div>
                                  <img src="/assets/arrow-icon-v2.svg" loading="lazy" style={{"transform": "translate3d(0px, 0px, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg)", "transformStyle": "preserve-3d"}} alt="" className="btn-arrow-large" aria-hidden="true" />
                                </Link>
                              </div>
                            </div>
                          </div>
                        </div>
                        <div className="slider__right-pane image-4" aria-hidden="true">
                          <div className="slider__image-cover" aria-hidden="true" style={{"width": "600px", "height": "100%"}}></div>
                          <div className="slider-lottie" data-animation-type="lottie" data-src="https://cdn.prod.website-files.com/6696985a1d3e81308169d89c/68cb8c6691e1f0cbbf1d9550_ThreatManagement_v2.lottie" data-loop="1" data-direction="1" data-autoplay="1" data-is-ix2-target="0" data-renderer="svg" data-default-duration="0" data-duration="0" data-loading="eager" style={{"opacity": "0"}} aria-hidden="true">
                            <DotLottiePlayer src="/lottie/68cb8c6691e1f0cbbf1d9550_ThreatManagement_v2.lottie" loop={true} autoplay={true} />
                          </div>
                        </div>
                      </div>
                    </div>
                    <div className="w-slide" aria-label="5 of 5" role="group" aria-hidden="true" style={{"transition": "all", "transform": "translateX(0px)", "opacity": "1", "visibility": "hidden"}}>
                      <div className="slide__wrapper" aria-hidden="true">
                        <div className="slider__left-pane" aria-hidden="true">
                          <div className="slide-text-wrapper" aria-hidden="true">
                            <h4 className="h4_v2" aria-hidden="true">
                              <strong aria-hidden="true">
                                Third-Party Risk Management
                              </strong>
                            </h4>
                            <div className="body-text-medium" aria-hidden="true">
                              Our platform provides visibility and control over external vulnerabilities, helping your organization stay secure, compliant, and protected from outside threats.
                            </div>
                            <div className="padding-top xxs" aria-hidden="true">
                              <div className="container-flex" aria-hidden="true">
                                <Link href="/product" className="btn-large w-inline-block" tabIndex={-1} aria-hidden="true">
                                  <div className="btn-text-large" aria-hidden="true">
                                    Learn more
                                  </div>
                                  <img src="/assets/arrow-icon-v2.svg" loading="lazy" style={{"transform": "translate3d(0px, 0px, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg)", "transformStyle": "preserve-3d"}} alt="" className="btn-arrow-large" aria-hidden="true" />
                                </Link>
                              </div>
                            </div>
                          </div>
                        </div>
                        <div className="slider__right-pane image-5" aria-hidden="true">
                          <div className="slider__image-cover" aria-hidden="true" style={{"width": "600px", "height": "100%"}}></div>
                          <div className="slider-lottie" data-animation-type="lottie" data-src="https://cdn.prod.website-files.com/6696985a1d3e81308169d89c/68cb8c8fe1d100b0bcefb3d1_AgenticAI_v2.lottie" data-loop="1" data-direction="1" data-autoplay="1" data-is-ix2-target="0" data-renderer="svg" data-default-duration="0" data-duration="0" data-loading="eager" style={{"opacity": "0"}} aria-hidden="true">
                            <DotLottiePlayer src="/lottie/68cb8c8fe1d100b0bcefb3d1_AgenticAI_v2.lottie" loop={true} autoplay={true} />
                          </div>
                        </div>
                      </div>
                    </div>
                    <div aria-live="off" aria-atomic="true" className="w-slider-aria-label" data-wf-ignore=""></div>
                  </div>
                  <div className="slider__nav w-slider-nav w-round">
                    <div className="w-slider-dot w-active" data-wf-ignore="" aria-label="Show slide 1 of 5" aria-pressed="true" role="button" tabIndex={0} style={{"marginLeft": "3px", "marginRight": "3px"}}></div>
                    <div className="w-slider-dot" data-wf-ignore="" aria-label="Show slide 2 of 5" aria-pressed="false" role="button" tabIndex={-1} style={{"marginLeft": "3px", "marginRight": "3px"}}></div>
                    <div className="w-slider-dot" data-wf-ignore="" aria-label="Show slide 3 of 5" aria-pressed="false" role="button" tabIndex={-1} style={{"marginLeft": "3px", "marginRight": "3px"}}></div>
                    <div className="w-slider-dot" data-wf-ignore="" aria-label="Show slide 4 of 5" aria-pressed="false" role="button" tabIndex={-1} style={{"marginLeft": "3px", "marginRight": "3px"}}></div>
                    <div className="w-slider-dot" data-wf-ignore="" aria-label="Show slide 5 of 5" aria-pressed="false" role="button" tabIndex={-1} style={{"marginLeft": "3px", "marginRight": "3px"}}></div>
                  </div>
                  <div className="slider__control-wrapper">
                    <div id="slider-control-wrap-1" className="slider__control enable-pointer">
                      <div id="slider-control-1" className="slider__arrow-wrapper w-slider-arrow-left" role="button" tabIndex={0} aria-controls="w-slider-mask-0" aria-label="previous slide">
                        <div className="slider__left-icon w-icon-slider-left"></div>
                      </div>
                    </div>
                    <div id="slider-control-wrap-2" className="slider__control enable-pointer">
                      <div id="slider-control-2" className="slider__arrow-wrapper w-slider-arrow-right" role="button" tabIndex={0} aria-controls="w-slider-mask-0" aria-label="next slide">
                        <div className="slider__right-icon w-icon-slider-right"></div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
