"use client";

import { useEffect, useState } from "react";
import { DotLottieReact, type DotLottie } from "@lottiefiles/dotlottie-react";

type Props = {
  src: string;
  loop?: boolean;
  autoplay?: boolean;
  /**
   * The animation's intrinsic pixel size (the lottie JSON's `w`/`h`). Webflow's
   * SVG renderer puts these on the <svg> as width/height attributes, so the
   * element has a real intrinsic size: containers with no height of their own
   * derive it from the animation's aspect ratio, and flex items stretch to the
   * animation's width. The canvas renderer defaults to 300x150, so pass these
   * for lotties whose Webflow container relies on intrinsic sizing.
   */
  width?: number;
  height?: number;
  /**
   * Play once the first time the element scrolls into view, starting after
   * this many ms (the stagger delay from the IX2 SCROLL_INTO_VIEW lottie
   * actions, e.g. the frameworks compliance dials, a-122/125/126), then hold
   * the final frame — leaving view does NOT rewind, so later passes show the
   * finished state. (The original site replayed on every pass; play-once is
   * deliberate.) Reduced-motion users see the final frame immediately.
   */
  playOnView?: number;
};

/**
 * Re-animates the Webflow Lottie blocks that were frozen to a static SVG in the
 * capture. Fills its parent wrapper so the surrounding Webflow layout still
 * drives sizing. Generated by the Webflow Cloner agent.
 */
export function DotLottiePlayer({ src, loop = false, autoplay = true, width, height, playOnView }: Props) {
  const [instance, setInstance] = useState<DotLottie | null>(null);

  useEffect(() => {
    if (playOnView === undefined || !instance) return;
    const whenLoaded = (fn: () => void) => {
      if (instance.isLoaded) fn();
      else instance.addEventListener("load", fn);
    };
    if (window.matchMedia("(prefers-reduced-motion: reduce)").matches) {
      whenLoaded(() => instance.setFrame(Math.max(0, instance.totalFrames - 1)));
      return;
    }
    const canvas = instance.canvas;
    if (!(canvas instanceof HTMLCanvasElement)) return;
    let timer: ReturnType<typeof setTimeout> | null = null;
    const io = new IntersectionObserver(([entry]) => {
      if (entry.isIntersecting) {
        if (timer) clearTimeout(timer);
        timer = setTimeout(() => {
          io.disconnect();
          whenLoaded(() => instance.play());
        }, playOnView);
      } else if (timer) {
        // left view before the stagger delay elapsed: try again next pass
        clearTimeout(timer);
        timer = null;
      }
    });
    io.observe(canvas);
    return () => {
      io.disconnect();
      if (timer) clearTimeout(timer);
    };
  }, [instance, playOnView]);

  return (
    <DotLottieReact
      src={src}
      loop={loop}
      autoplay={autoplay}
      dotLottieRefCallback={playOnView !== undefined ? setInstance : undefined}
      // width/height land on the <canvas> as attributes, giving it the same
      // intrinsic size the original SVG had
      width={width}
      height={height}
      style={{
        width: "100%",
        height: "100%",
        aspectRatio: width && height ? `${width} / ${height}` : undefined,
      }}
    />
  );
}
