"use client";

import { DotLottieReact } from "@lottiefiles/dotlottie-react";

type Props = {
  src: string;
  loop?: boolean;
  autoplay?: boolean;
};

/**
 * Re-animates the Webflow Lottie blocks that were frozen to a static SVG in the
 * capture. Fills its parent wrapper so the surrounding Webflow layout still
 * drives sizing. Generated by the Webflow Cloner agent.
 */
export function DotLottiePlayer({ src, loop = false, autoplay = true }: Props) {
  return (
    <DotLottieReact
      src={src}
      loop={loop}
      autoplay={autoplay}
      style={{ width: "100%", height: "100%" }}
    />
  );
}
