import Link from "next/link";

/** Shared site footer, reused across pages. Generated by the Webflow Cloner agent. */
export function SiteFooter3() {
  return (
    <footer className="section-footer_v2">
      <div className="container-large">
        <div className="container-flex space-between footer-content">
          <div className="container-flex vertical space-between">
            <div className="container-flex footer-menu">
              <img loading="lazy" src="/assets/mycroft-lockup-white-v3.svg" alt="Mycroft logotype" className="footer-img" />
              <div className="container-flex footer-menu-items">
                <Link href="/terms" target="_blank" className="footer-link_v2">
                  Terms
                </Link>
                <Link href="/privacy" target="_blank" aria-current="page" className="footer-link_v2 w--current">
                  Privacy
                </Link>
                <a href="https://status.mycroft.io/" target="_blank" className="footer-link_v2">
                  Status
                </a>
                <Link href="/ai-disclosure" target="_blank" className="footer-link_v2">
                  AI Disclosure
                </Link>
              </div>
            </div>
          </div>
          <div className="container-flex footer-badges">
            <img loading="lazy" src="/assets/footer-badge-soc2-v2.svg" alt="" className="footer-badge_v2" />
            <img loading="lazy" src="/assets/footer-badge-gdpr-v2.svg" alt="" className="footer-badge_v2" />
            <img loading="lazy" src="/assets/footer-badge-hipaa-v2.svg" alt="" className="footer-badge_v2" />
            <img loading="lazy" src="/assets/footer-badge-pipeda-v2.svg" alt="" className="footer-badge_v2" />
          </div>
        </div>
        <div className="footer-text-mice">
          © 2026 Mycroft Technologies Inc. All rights reserved.
        </div>
      </div>
    </footer>
  );
}
