import Link from "next/link";

/** Shared site nav, reused across pages. Generated by the Webflow Cloner agent. */
export function SiteNav4() {
  return (
    <div data-animation="default" data-collapse="medium" data-duration="400" data-easing="ease" data-easing2="ease" role="banner" className="navbar_v3 w-nav">
      <div className="nav-submenu-mobile">
        <div className="submenu-mobile scrollable-submenu">
          <div className="nav-menu-links_v3">
            <div data-delay="0" data-hover="false" className="nav-link-dropdown w-dropdown">
              <div className="dropdown-trigger w-dropdown-toggle" id="w-dropdown-toggle-0" aria-controls="w-dropdown-list-0" aria-haspopup="menu" aria-expanded="false" role="button" tabIndex={0}>
                <div className="nav-link_v3 dropdown">
                  Product
                  <br />
                </div>
                <div className="dropdown-icon w-icon-dropdown-toggle" aria-hidden="true" style={{"transform": "translate3d(0px, 0px, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg)", "transformStyle": "preserve-3d"}}></div>
              </div>
              <nav className="nav-submenu w-dropdown-list" id="w-dropdown-list-0" aria-labelledby="w-dropdown-toggle-0" style={{"display": "none", "opacity": "0"}}>
                <div className="submenu-product scrollable-submenu">
                  <div className="label-wrapper desktop_only">
                    <div className="submenu-label">
                      Product
                    </div>
                  </div>
                  <div className="w-layout-grid sub-product-grid">
                    <Link href="/product" className="sub-product-tile overview w-inline-block" tabIndex={0} style={{"transform": "translate3d(0px, 20px, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg)", "transformStyle": "preserve-3d", "opacity": "0"}}>
                      <div className="product-tile-hed text_white">
                        Product overview
                      </div>
                      <div className="eyebrow-small color_charcoal z_10 text_white">
                        Learn more
                      </div>
                      <div className="product-tile-hov overview" style={{"opacity": "0", "transform": "translate3d(0px, 100%, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg)", "transformStyle": "preserve-3d"}}></div>
                    </Link>
                    <Link href="/product/audit-and-compliance" className="sub-product-tile w-inline-block" tabIndex={0} style={{"transform": "translate3d(0px, 20px, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg)", "transformStyle": "preserve-3d", "opacity": "0"}}>
                      <div className="product-tile-hed">
                        Audit & compliance
                      </div>
                      <div className="eyebrow-small color_charcoal z_10">
                        Learn more
                      </div>
                      <div className="product-tile-hov" style={{"opacity": "0", "transform": "translate3d(0px, 100%, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg)", "transformStyle": "preserve-3d"}}></div>
                    </Link>
                    <Link href="/product/cloud-security" aria-current="page" className="sub-product-tile cloud w-inline-block w--current" tabIndex={0} style={{"transform": "translate3d(0px, 20px, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg)", "transformStyle": "preserve-3d", "opacity": "0"}}>
                      <div className="product-tile-hed">
                        Cloud security
                      </div>
                      <div className="eyebrow-small color_charcoal z_10">
                        Learn more
                      </div>
                      <div className="product-tile-hov cloud" style={{"opacity": "0", "transform": "translate3d(0px, 100%, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg)", "transformStyle": "preserve-3d"}}></div>
                    </Link>
                    <Link href="/product/app-security" className="sub-product-tile appsec w-inline-block" tabIndex={0} style={{"transform": "translate3d(0px, 20px, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg)", "transformStyle": "preserve-3d", "opacity": "0"}}>
                      <div className="product-tile-hed">
                        App security
                      </div>
                      <div className="eyebrow-small color_charcoal z_10">
                        Learn more
                      </div>
                      <div className="product-tile-hov appsec" style={{"opacity": "0", "transform": "translate3d(0px, 100%, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg)", "transformStyle": "preserve-3d"}}></div>
                    </Link>
                    <Link href="/product/device-management" className="sub-product-tile device w-inline-block" tabIndex={0} style={{"transform": "translate3d(0px, 20px, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg)", "transformStyle": "preserve-3d", "opacity": "0"}}>
                      <div className="product-tile-hed">
                        Device management
                      </div>
                      <div className="eyebrow-small color_charcoal z_10">
                        Learn more
                      </div>
                      <div className="product-tile-hov device" style={{"opacity": "0", "transform": "translate3d(0px, 100%, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg)", "transformStyle": "preserve-3d"}}></div>
                    </Link>
                    <Link href="/product/third-party-risk-management" className="sub-product-tile tprm w-inline-block" tabIndex={0} style={{"transform": "translate3d(0px, 20px, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg)", "transformStyle": "preserve-3d", "opacity": "0"}}>
                      <div className="product-tile-hed">
                        Third-party risk management
                      </div>
                      <div className="eyebrow-small color_charcoal z_10">
                        Learn more
                      </div>
                      <div className="product-tile-hov tprm" style={{"opacity": "0", "transform": "translate3d(0px, 100%, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg)", "transformStyle": "preserve-3d"}}></div>
                    </Link>
                  </div>
                </div>
              </nav>
            </div>
            <div data-delay="0" data-hover="false" className="nav-link-dropdown w-dropdown">
              <div className="dropdown-trigger w-dropdown-toggle" id="w-dropdown-toggle-1" aria-controls="w-dropdown-list-1" aria-haspopup="menu" aria-expanded="false" role="button" tabIndex={0}>
                <div className="nav-link_v3 dropdown">
                  Solutions
                </div>
                <div className="dropdown-icon w-icon-dropdown-toggle" aria-hidden="true" style={{"transform": "translate3d(0px, 0px, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg)", "transformStyle": "preserve-3d"}}></div>
              </div>
              <nav className="nav-submenu w-dropdown-list" id="w-dropdown-list-1" aria-labelledby="w-dropdown-toggle-1" style={{"display": "none", "opacity": "0"}}>
                <div className="submenu-product scrollable-submenu">
                  <div className="label-wrapper desktop_only">
                    <div className="submenu-label">
                      Frameworks
                    </div>
                  </div>
                  <div className="w-layout-grid sub-solutions-grid">
                    <Link href="/frameworks/soc2" className="solution-tile w-inline-block" tabIndex={0} style={{"opacity": "0", "transform": "translate3d(0px, 20px, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg)", "transformStyle": "preserve-3d"}}>
                      <img src="/assets/soc-2-badge.svg" loading="lazy" width="Auto" alt="" className="solution-icon" />
                      <div>
                        SOC 2
                      </div>
                    </Link>
                    <Link href="/frameworks/gdpr" className="solution-tile w-inline-block" tabIndex={0} style={{"opacity": "0", "transform": "translate3d(0px, 20px, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg)", "transformStyle": "preserve-3d"}}>
                      <img src="/assets/gdpr-badge.svg" loading="lazy" width="Auto" alt="" className="solution-icon" />
                      <div>
                        GDPR
                      </div>
                    </Link>
                    <Link href="/frameworks/pipeda" className="solution-tile row_child w-inline-block" tabIndex={0} style={{"opacity": "0", "transform": "translate3d(0px, 20px, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg)", "transformStyle": "preserve-3d"}}>
                      <img src="/assets/pipeda-badge.svg" loading="lazy" width="Auto" alt="" className="solution-icon" />
                      <div>
                        PIPEDA
                      </div>
                    </Link>
                    <div id="w-node-_1202cf2e-6549-af6f-7a6b-50d1b7f45e02-e51a302e" className="mobile-hr"></div>
                    <Link href="/frameworks/cmmc" className="solution-tile w-inline-block" tabIndex={0} style={{"opacity": "0", "transform": "translate3d(0px, 20px, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg)", "transformStyle": "preserve-3d"}}>
                      <img src="/assets/cmmc-badge.svg" loading="lazy" width="Auto" alt="" className="solution-icon" />
                      <div>
                        CMMC
                      </div>
                    </Link>
                    <Link href="/frameworks/fedramp" className="solution-tile w-inline-block" tabIndex={0} style={{"opacity": "0", "transform": "translate3d(0px, 20px, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg)", "transformStyle": "preserve-3d"}}>
                      <img src="/assets/fedramp-badge.svg" loading="lazy" width="Auto" alt="" className="solution-icon" />
                      <div>
                        FedRAMP
                      </div>
                    </Link>
                    <Link href="/frameworks/iso27001" className="solution-tile row_child w-inline-block" tabIndex={0} style={{"opacity": "0", "transform": "translate3d(0px, 20px, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg)", "transformStyle": "preserve-3d"}}>
                      <img src="/assets/iso-27001-badge.svg" loading="lazy" width="Auto" alt="" className="solution-icon" />
                      <div>
                        ISO 27001
                      </div>
                    </Link>
                    <div id="w-node-_091afdd5-dbdf-64fe-4376-a4c1cb784ddd-e51a302e" className="mobile-hr"></div>
                    <Link href="/frameworks/hipaa" className="solution-tile w-inline-block" tabIndex={0} style={{"opacity": "0", "transform": "translate3d(0px, 20px, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg)", "transformStyle": "preserve-3d"}}>
                      <img src="/assets/hipaa-badge.svg" loading="lazy" width="Auto" alt="" className="solution-icon" />
                      <div>
                        HIPAA
                      </div>
                    </Link>
                    <Link href="/frameworks/cpra" className="solution-tile w-inline-block" tabIndex={0} style={{"opacity": "0", "transform": "translate3d(0px, 20px, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg)", "transformStyle": "preserve-3d"}}>
                      <img src="/assets/crpa-badge.svg" loading="lazy" width="Auto" alt="" className="solution-icon" />
                      <div>
                        CPRA/CCPA
                      </div>
                    </Link>
                    <Link href="/frameworks/iso42001" className="solution-tile last_child w-inline-block" tabIndex={0} style={{"opacity": "0", "transform": "translate3d(0px, 20px, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg)", "transformStyle": "preserve-3d"}}>
                      <img src="/assets/iso-42001-badge.svg" loading="lazy" width="Auto" alt="" className="solution-icon" />
                      <div>
                        ISO42001
                      </div>
                    </Link>
                  </div>
                  <div className="sub-link-wrapper">
                    <a href="https://trust.mycroft.io/" target="_blank" className="text-link xs_link w-inline-block" tabIndex={0}>
                      <div>
                        Trust center
                      </div>
                      <div className="arrow-icon-small xs_link w-embed" style={{"transform": "translate3d(0px, 0px, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg)", "transformStyle": "preserve-3d"}}>
                        <svg id="a" data-name="mycroft-arrow_icon" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 10">
                          <path d="M14.04,3.46c-1.33-1-2.19-2.62-2.58-3.46l-1.49.54c.39.92,1.17,2.46,2.5,3.69H0v1.54h12.48c-1.33,1.15-2.11,2.77-2.5,3.69l1.49.54c.39-.92,1.25-2.46,2.58-3.46.39-.31,1.17-.77,1.96-.92v-1.23c-.78-.15-1.57-.54-1.96-.92Z" style={{"fill": "currentColor"}}></path>
                        </svg>
                      </div>
                    </a>
                  </div>
                </div>
              </nav>
            </div>
            <div className="nav-link-item v3">
              <Link href="/partnerships" className="nav-link_v3 w-nav-link">
                Partnerships
              </Link>
              <div className="nav-text-highlight" style={{"transform": "translate3d(-100%, 0px, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg)", "transformStyle": "preserve-3d"}}></div>
            </div>
            <div className="nav-link-item v3">
              <Link href="/resources" className="nav-link_v3 w-nav-link">
                Resources
              </Link>
              <div className="nav-text-highlight" style={{"transform": "translate3d(-100%, 0px, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg)", "transformStyle": "preserve-3d"}}></div>
            </div>
            <div className="nav-link-item v3">
              <Link href="/pricing" className="nav-link_v3 w-nav-link">
                Pricing
              </Link>
              <div className="nav-text-highlight" style={{"transform": "translate3d(-100%, 0px, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg)", "transformStyle": "preserve-3d"}}></div>
            </div>
            <div className="nav-link-item v3 last_child">
              <Link href="/about" className="nav-link_v3 w-nav-link">
                About
              </Link>
              <div className="nav-text-highlight" style={{"transform": "translate3d(-100%, 0px, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg)", "transformStyle": "preserve-3d"}}></div>
            </div>
          </div>
          <div className="nav-menu-ctas full_width">
            <Link href="/demo" className="btn-nav full_width w-inline-block">
              <div className="nav-btn-text">
                Book a demo
              </div>
              <img src="/assets/arrow-icon-white.svg" loading="lazy" alt="" className="nav-btn-arrow" style={{"transform": "translate3d(0px, 0px, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg)", "transformStyle": "preserve-3d"}} />
            </Link>
            <a href="https://app.mycroft.io" target="_blank" className="btn-nav full_width grey w-inline-block">
              <div className="nav-btn-text color_rg">
                Login
              </div>
            </a>
            <div className="menu-gradient"></div>
          </div>
        </div>
      </div>
      <div className="nav-container_v3 desktop">
        <div className="nav-outer-wrapper">
          <div className="nav-menu-wrapper">
            <Link href="/" className="logo-lockup w-nav-brand" aria-label="home">
              <img loading="eager" src="/assets/mycroft-lockup-green-v2.svg" alt="Mycroft logo lockup" className="nav-logo-img" />
            </Link>
            <div className="nav-menu-links_v3">
              <div data-delay="0" data-hover="false" className="nav-link-dropdown w-dropdown">
                <div className="dropdown-trigger w-dropdown-toggle" id="w-dropdown-toggle-2" aria-controls="w-dropdown-list-2" aria-haspopup="menu" aria-expanded="false" role="button" tabIndex={0}>
                  <div className="nav-link_v3 dropdown">
                    Product
                    <br />
                  </div>
                  <div className="dropdown-icon w-icon-dropdown-toggle" style={{"transform": "translate3d(0px, 0px, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg)", "transformStyle": "preserve-3d"}} aria-hidden="true"></div>
                </div>
                <nav className="nav-submenu w-dropdown-list" style={{"display": "none", "opacity": "0"}} id="w-dropdown-list-2" aria-labelledby="w-dropdown-toggle-2">
                  <div className="submenu-product scrollable-submenu">
                    <div className="label-wrapper desktop_only">
                      <div className="submenu-label">
                        Product
                      </div>
                    </div>
                    <div className="w-layout-grid sub-product-grid">
                      <Link href="/product" className="sub-product-tile overview w-inline-block" tabIndex={0} style={{"transform": "translate3d(0px, 20px, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg)", "transformStyle": "preserve-3d", "opacity": "0"}}>
                        <div className="product-tile-hed text_white">
                          Product overview
                        </div>
                        <div className="eyebrow-small color_charcoal z_10 text_white">
                          Learn more
                        </div>
                        <div className="product-tile-hov overview" style={{"opacity": "0", "transform": "translate3d(0px, 100%, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg)", "transformStyle": "preserve-3d"}}></div>
                      </Link>
                      <Link href="/product/audit-and-compliance" className="sub-product-tile w-inline-block" tabIndex={0} style={{"transform": "translate3d(0px, 20px, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg)", "transformStyle": "preserve-3d", "opacity": "0"}}>
                        <div className="product-tile-hed">
                          Audit & compliance
                        </div>
                        <div className="eyebrow-small color_charcoal z_10">
                          Learn more
                        </div>
                        <div className="product-tile-hov" style={{"opacity": "0", "transform": "translate3d(0px, 100%, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg)", "transformStyle": "preserve-3d"}}></div>
                      </Link>
                      <Link href="/product/cloud-security" aria-current="page" className="sub-product-tile cloud w-inline-block w--current" tabIndex={0} style={{"transform": "translate3d(0px, 20px, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg)", "transformStyle": "preserve-3d", "opacity": "0"}}>
                        <div className="product-tile-hed">
                          Cloud security
                        </div>
                        <div className="eyebrow-small color_charcoal z_10">
                          Learn more
                        </div>
                        <div className="product-tile-hov cloud" style={{"opacity": "0", "transform": "translate3d(0px, 100%, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg)", "transformStyle": "preserve-3d"}}></div>
                      </Link>
                      <Link href="/product/app-security" className="sub-product-tile appsec w-inline-block" tabIndex={0} style={{"transform": "translate3d(0px, 20px, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg)", "transformStyle": "preserve-3d", "opacity": "0"}}>
                        <div className="product-tile-hed">
                          App security
                        </div>
                        <div className="eyebrow-small color_charcoal z_10">
                          Learn more
                        </div>
                        <div className="product-tile-hov appsec" style={{"opacity": "0", "transform": "translate3d(0px, 100%, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg)", "transformStyle": "preserve-3d"}}></div>
                      </Link>
                      <Link href="/product/device-management" className="sub-product-tile device w-inline-block" tabIndex={0} style={{"transform": "translate3d(0px, 20px, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg)", "transformStyle": "preserve-3d", "opacity": "0"}}>
                        <div className="product-tile-hed">
                          Device management
                        </div>
                        <div className="eyebrow-small color_charcoal z_10">
                          Learn more
                        </div>
                        <div className="product-tile-hov device" style={{"opacity": "0", "transform": "translate3d(0px, 100%, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg)", "transformStyle": "preserve-3d"}}></div>
                      </Link>
                      <Link href="/product/third-party-risk-management" className="sub-product-tile tprm w-inline-block" tabIndex={0} style={{"transform": "translate3d(0px, 20px, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg)", "transformStyle": "preserve-3d", "opacity": "0"}}>
                        <div className="product-tile-hed">
                          Third-party risk management
                        </div>
                        <div className="eyebrow-small color_charcoal z_10">
                          Learn more
                        </div>
                        <div className="product-tile-hov tprm" style={{"opacity": "0", "transform": "translate3d(0px, 100%, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg)", "transformStyle": "preserve-3d"}}></div>
                      </Link>
                    </div>
                  </div>
                </nav>
              </div>
              <div data-delay="0" data-hover="false" className="nav-link-dropdown w-dropdown">
                <div className="dropdown-trigger w-dropdown-toggle" id="w-dropdown-toggle-3" aria-controls="w-dropdown-list-3" aria-haspopup="menu" aria-expanded="false" role="button" tabIndex={0}>
                  <div className="nav-link_v3 dropdown">
                    Solutions
                  </div>
                  <div className="dropdown-icon w-icon-dropdown-toggle" style={{"transform": "translate3d(0px, 0px, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg)", "transformStyle": "preserve-3d"}} aria-hidden="true"></div>
                </div>
                <nav className="nav-submenu w-dropdown-list" style={{"display": "none", "opacity": "0"}} id="w-dropdown-list-3" aria-labelledby="w-dropdown-toggle-3">
                  <div className="submenu-product scrollable-submenu">
                    <div className="label-wrapper desktop_only">
                      <div className="submenu-label">
                        Frameworks
                      </div>
                    </div>
                    <div className="w-layout-grid sub-solutions-grid">
                      <Link href="/frameworks/soc2" className="solution-tile w-inline-block" tabIndex={0} style={{"opacity": "0", "transform": "translate3d(0px, 20px, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg)", "transformStyle": "preserve-3d"}}>
                        <img src="/assets/soc-2-badge.svg" loading="lazy" width="Auto" alt="" className="solution-icon" />
                        <div>
                          SOC 2
                        </div>
                      </Link>
                      <Link href="/frameworks/gdpr" className="solution-tile w-inline-block" tabIndex={0} style={{"opacity": "0", "transform": "translate3d(0px, 20px, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg)", "transformStyle": "preserve-3d"}}>
                        <img src="/assets/gdpr-badge.svg" loading="lazy" width="Auto" alt="" className="solution-icon" />
                        <div>
                          GDPR
                        </div>
                      </Link>
                      <Link href="/frameworks/pipeda" className="solution-tile row_child w-inline-block" tabIndex={0} style={{"opacity": "0", "transform": "translate3d(0px, 20px, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg)", "transformStyle": "preserve-3d"}}>
                        <img src="/assets/pipeda-badge.svg" loading="lazy" width="Auto" alt="" className="solution-icon" />
                        <div>
                          PIPEDA
                        </div>
                      </Link>
                      <div id="w-node-_1202cf2e-6549-af6f-7a6b-50d1b7f45e02-e51a302e" className="mobile-hr"></div>
                      <Link href="/frameworks/cmmc" className="solution-tile w-inline-block" tabIndex={0} style={{"opacity": "0", "transform": "translate3d(0px, 20px, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg)", "transformStyle": "preserve-3d"}}>
                        <img src="/assets/cmmc-badge.svg" loading="lazy" width="Auto" alt="" className="solution-icon" />
                        <div>
                          CMMC
                        </div>
                      </Link>
                      <Link href="/frameworks/fedramp" className="solution-tile w-inline-block" tabIndex={0} style={{"opacity": "0", "transform": "translate3d(0px, 20px, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg)", "transformStyle": "preserve-3d"}}>
                        <img src="/assets/fedramp-badge.svg" loading="lazy" width="Auto" alt="" className="solution-icon" />
                        <div>
                          FedRAMP
                        </div>
                      </Link>
                      <Link href="/frameworks/iso27001" className="solution-tile row_child w-inline-block" tabIndex={0} style={{"opacity": "0", "transform": "translate3d(0px, 20px, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg)", "transformStyle": "preserve-3d"}}>
                        <img src="/assets/iso-27001-badge.svg" loading="lazy" width="Auto" alt="" className="solution-icon" />
                        <div>
                          ISO 27001
                        </div>
                      </Link>
                      <div id="w-node-_091afdd5-dbdf-64fe-4376-a4c1cb784ddd-e51a302e" className="mobile-hr"></div>
                      <Link href="/frameworks/hipaa" className="solution-tile w-inline-block" tabIndex={0} style={{"opacity": "0", "transform": "translate3d(0px, 20px, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg)", "transformStyle": "preserve-3d"}}>
                        <img src="/assets/hipaa-badge.svg" loading="lazy" width="Auto" alt="" className="solution-icon" />
                        <div>
                          HIPAA
                        </div>
                      </Link>
                      <Link href="/frameworks/cpra" className="solution-tile w-inline-block" tabIndex={0} style={{"opacity": "0", "transform": "translate3d(0px, 20px, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg)", "transformStyle": "preserve-3d"}}>
                        <img src="/assets/crpa-badge.svg" loading="lazy" width="Auto" alt="" className="solution-icon" />
                        <div>
                          CPRA/CCPA
                        </div>
                      </Link>
                      <Link href="/frameworks/iso42001" className="solution-tile last_child w-inline-block" tabIndex={0} style={{"opacity": "0", "transform": "translate3d(0px, 20px, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg)", "transformStyle": "preserve-3d"}}>
                        <img src="/assets/iso-42001-badge.svg" loading="lazy" width="Auto" alt="" className="solution-icon" />
                        <div>
                          ISO42001
                        </div>
                      </Link>
                    </div>
                    <div className="sub-link-wrapper">
                      <a href="https://trust.mycroft.io/" target="_blank" className="text-link xs_link w-inline-block" tabIndex={0}>
                        <div>
                          Trust center
                        </div>
                        <div className="arrow-icon-small xs_link w-embed" style={{"transform": "translate3d(0px, 0px, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg)", "transformStyle": "preserve-3d"}}>
                          <svg id="a" data-name="mycroft-arrow_icon" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 10">
                            <path d="M14.04,3.46c-1.33-1-2.19-2.62-2.58-3.46l-1.49.54c.39.92,1.17,2.46,2.5,3.69H0v1.54h12.48c-1.33,1.15-2.11,2.77-2.5,3.69l1.49.54c.39-.92,1.25-2.46,2.58-3.46.39-.31,1.17-.77,1.96-.92v-1.23c-.78-.15-1.57-.54-1.96-.92Z" style={{"fill": "currentColor"}}></path>
                          </svg>
                        </div>
                      </a>
                    </div>
                  </div>
                </nav>
              </div>
              <div className="nav-link-item v3">
                <Link href="/partnerships" className="nav-link_v3 w-nav-link">
                  Partnerships
                </Link>
                <div className="nav-text-highlight" style={{"transform": "translate3d(-100%, 0px, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg)", "transformStyle": "preserve-3d"}}></div>
              </div>
              <div className="nav-link-item v3">
                <Link href="/resources" className="nav-link_v3 w-nav-link">
                  Resources
                </Link>
                <div className="nav-text-highlight" style={{"transform": "translate3d(-100%, 0px, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg)", "transformStyle": "preserve-3d"}}></div>
              </div>
              <div className="nav-link-item v3">
                <Link href="/pricing" className="nav-link_v3 w-nav-link">
                  Pricing
                </Link>
                <div className="nav-text-highlight" style={{"transform": "translate3d(-100%, 0px, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg)", "transformStyle": "preserve-3d"}}></div>
              </div>
              <div className="nav-link-item v3 last_child">
                <Link href="/about" className="nav-link_v3 w-nav-link">
                  About
                </Link>
                <div className="nav-text-highlight" style={{"transform": "translate3d(-100%, 0px, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg)", "transformStyle": "preserve-3d"}}></div>
              </div>
            </div>
            <div className="nav-menu-ctas">
              <a href="https://app.mycroft.io" target="_blank" className="nav-link_v2 login w-nav-link">
                Login
              </a>
              <Link href="/demo" className="btn-nav w-inline-block">
                <div className="nav-btn-text">
                  Book a demo
                </div>
                <img src="/assets/arrow-icon-white.svg" loading="lazy" alt="" className="nav-btn-arrow" style={{"transform": "translate3d(0px, 0px, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg)", "transformStyle": "preserve-3d"}} />
              </Link>
            </div>
          </div>
        </div>
        <div className="nav-shadow-sliver"></div>
      </div>
      <div className="nav-mobile-container">
        <div className="nav-mob-outer">
          <div className="nav-mob-inner">
            <Link href="/" className="logo-lockup mobile w-nav-brand" aria-label="home">
              <img loading="eager" src="/assets/mycroft-lockup-green-v2.svg" alt="Mycroft logo lockup" className="nav-logo-img" />
            </Link>
            <a href="#" className="hamburger-lockup w-inline-block">
              <div className="hamburger-top"></div>
              <div className="hamburger-mid"></div>
              <div className="hamburger-btm"></div>
            </a>
          </div>
        </div>
      </div>
      <div className="code-embed-nav w-embed w-script"></div>
      <div className="w-nav-overlay" data-wf-ignore="" id="w-nav-overlay-0"></div>
    </div>
  );
}
