import { NavLink } from "./NavLink";

/** Shared site footer, reused across pages. Generated by the Webflow Cloner agent. */
export function SiteFooter() {
  return (
    <footer className="section-footer_v2">
      <div className="w-full max-w-300 ml-auto mr-auto">
        <div className="container-flex space-between footer-content">
          <div className="container-flex vertical space-between">
            <div className="container-flex footer-menu">
              <img loading="lazy" src="/assets/brand/mycroft-lockup-white-v3.svg" alt="Mycroft logotype" className="footer-img" />
              <div className="container-flex footer-menu-items">
                <NavLink href="/terms" target="_blank" className="footer-link_v2">
                  Terms
                </NavLink>
                <NavLink href="/privacy" target="_blank" className="footer-link_v2">
                  Privacy
                </NavLink>
                <a href="https://status.mycroft.io/" target="_blank" className="footer-link_v2">
                  Status
                </a>
                <NavLink href="/ai-disclosure" target="_blank" className="footer-link_v2">
                  AI Disclosure
                </NavLink>
              </div>
            </div>
          </div>
          <div className="container-flex footer-badges">
            <img loading="lazy" src="/assets/badges/footer-badge-soc2-v2.svg" alt="" className="footer-badge_v2" />
            <img loading="lazy" src="/assets/badges/footer-badge-gdpr-v2.svg" alt="" className="footer-badge_v2" />
            <img loading="lazy" src="/assets/badges/footer-badge-hipaa-v2.svg" alt="" className="footer-badge_v2" />
            <img loading="lazy" src="/assets/badges/footer-badge-pipeda-v2.svg" alt="" className="footer-badge_v2" />
          </div>
        </div>
        <div className="footer-text-mice">
          © {new Date().getFullYear()} Mycroft Technologies Inc. All rights reserved.
        </div>
      </div>
    </footer>
  );
}
