import Script from "next/script";

/**
 * Third-party tags re-wired from the original Webflow site, with the
 * original IDs. Mounted once in the root layout. Remove any block you
 * don't want, or gate them behind a consent manager.
 * Generated by the Webflow Cloner agent.
 */
export function ThirdPartyScripts() {
  return (
    <>
      {/* Google Tag Manager (GTM-5PVJPRF5) */}
      <Script id="wf-gtm" strategy="afterInteractive">{`
        (function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src='https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);})(window,document,'script','dataLayer','GTM-5PVJPRF5');
      `}</Script>
      {/* Google Analytics 4 (G-FNCLGSLK7E) */}
      <Script src="https://www.googletagmanager.com/gtag/js?id=G-FNCLGSLK7E" strategy="afterInteractive" />
      <Script id="wf-ga4" strategy="afterInteractive">{`
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());
        gtag('config', 'G-FNCLGSLK7E');
      `}</Script>
      {/* Microsoft Clarity (wfseo666us) */}
      <Script id="wf-clarity" strategy="afterInteractive">{`
        (function(c,l,a,r,i,t,y){c[a]=c[a]||function(){(c[a].q=c[a].q||[]).push(arguments)};t=l.createElement(r);t.async=1;t.src="https://www.clarity.ms/tag/"+i;y=l.getElementsByTagName(r)[0];y.parentNode.insertBefore(t,y);})(window, document, "clarity", "script", "wfseo666us");
      `}</Script>
      {/* HubSpot (45783254) — tracking + forms/chat loader */}
      <Script id="hs-script-loader" src="https://js.hs-scripts.com/45783254.js" strategy="afterInteractive" />
    </>
  );
}
