import type { Metadata } from "next";
import { ResourcesSnapshot } from "./_snapshot/ResourcesSnapshot";
import { WebflowInteractions } from "../_shared/WebflowInteractions";

export const metadata: Metadata = {
  title: "Mycroft Resources | Learn how you can strengthen your security and compliance knowledge",
  description: "Explore Mycroft resources for expert insights on cybersecurity, compliance, threat trends, and practical guides to help teams protect data and improve security posture. Learn how customers have achieved security and compliance with Mycroft, unlocking enterprise opportunities.",
  openGraph: {
    title: "Mycroft Resources | Learn how you can strengthen your security and compliance knowledge",
    description: "Explore Mycroft resources for expert insights on cybersecurity, compliance, threat trends, and practical guides to help teams protect data and improve security posture. Learn how customers have achieved security and compliance with Mycroft, unlocking enterprise opportunities.",
    type: "website",
    images: ["/assets/mycroft-meta-img-resources.webp"],
  },
  twitter: {
    card: "summary_large_image",
    title: "Mycroft Resources | Learn how you can strengthen your security and compliance knowledge",
    description: "Explore Mycroft resources for expert insights on cybersecurity, compliance, threat trends, and practical guides to help teams protect data and improve security posture. Learn how customers have achieved security and compliance with Mycroft, unlocking enterprise opportunities.",
    images: ["/assets/mycroft-meta-img-resources.webp"],
  },
};

/**
 * /resources: a faithful React rebuild of the Webflow page.
 * Generated by the Webflow Cloner agent from https://www.mycroft.io/resources.
 */
export default function ResourcesPage() {
  return (
    <>
      <ResourcesSnapshot />
      <WebflowInteractions />
    </>
  );
}
