import { ButtonLarge } from "@/app/_shared/ButtonLarge";

/** Section 3 of /product/cloud-security. Generated by the Webflow Cloner agent. */
export function ProductCloudSecuritySection3() {
  return (
    <section id="compliance" className="section_v2">
      <div className="section-overlap">
        <div className="pr-(--sizing--rem--2rem) pl-(--sizing--rem--2rem) ml-auto mr-auto relative max-portrait:pr-(--sizing--rem--1-25rem) max-portrait:pl-(--sizing--rem--1-25rem)">
          <div className="w-full max-w-200 ml-auto mr-auto max-tablet:w-[80%] max-tablet:max-w-none max-landscape:w-[92%] max-portrait:w-full">
            <div className="w-full pt-(--sizing--rem--6rem) max-tablet:pt-(--sizing--rem--5rem) max-landscape:pt-(--sizing--rem--3-5rem) max-portrait:pt-(--sizing--rem--2-5rem)">
              <div className="w-full pb-(--sizing--rem--2-5rem) max-tablet:pb-(--sizing--rem--2rem) max-landscape:pb-(--sizing--rem--1-5rem) max-portrait:pb-(--sizing--rem--1rem)">
                <div className="container-flex vertical center">
                  <div className="w-full pb-(--sizing--rem--1-75rem) max-tablet:pb-(--sizing--rem--1-5rem) max-landscape:pb-(--sizing--rem--1rem) max-portrait:pb-(--sizing--rem--0-75rem)">
                    <div className="container-flex vertical center text_center">
                      <h3 className="h3_v2 color_white">
                        Why cloud security isn’t just an option — it’s essential
                      </h3>
                      <div className="w-full pt-(--sizing--rem--1-25rem) max-tablet:pt-(--sizing--rem--1rem) max-landscape:pt-(--sizing--rem--0-75rem) max-portrait:pt-(--sizing--rem--0-5rem)">
                        <div className="text-dek-m color_40eg">
                          While many solutions claim to secure your cloud environment, our product delivers true cloud security built for today’s dynamic, multi-cloud world.
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div className="w-full max-w-300 ml-auto mr-auto">
            <div className="w-full pb-(--sizing--rem--8-5rem) max-tablet:pb-(--sizing--rem--6-5rem) max-landscape:pb-(--sizing--rem--4-5rem) max-portrait:pb-(--sizing--rem--3-5rem)">
              <div className="w-layout-grid features-3up">
                <div className="feature-item">
                  <img src="/assets/checkmark-icon.svg" loading="lazy" width="38" alt="" className="feature-icon" />
                  <div className="container-flex vertical center text_center">
                    <div className="h6 color_mint">
                      Protection of sensitive data
                    </div>
                    <div className="w-full pt-(--sizing--rem--0-75rem) max-tablet:pt-[.65rem] max-portrait:pt-[.4rem]">
                      <div className="body-text-small color_mint smaller">
                        Cloud services often handle sensitive information such as customer data, intellectual property, and financial records.
                      </div>
                    </div>
                  </div>
                </div>
                <div className="feature-item">
                  <img src="/assets/warning-icon.svg" loading="lazy" width="38" alt="" className="feature-icon" />
                  <div className="container-flex vertical center text_center">
                    <div className="h6 color_mint">
                      Regulatory compliance
                    </div>
                    <div className="w-full pt-(--sizing--rem--0-75rem) max-tablet:pt-[.65rem] max-portrait:pt-[.4rem]">
                      <div className="body-text-small color_mint smaller">
                        Cloud security is essential to meet the legal requirements for industry compliance, avoiding hefty fines or legal penalties.
                      </div>
                    </div>
                  </div>
                </div>
                <div className="feature-item">
                  <img src="/assets/lock-icon.svg" loading="lazy" width="38" alt="" className="feature-icon" />
                  <div className="container-flex vertical center text_center">
                    <div className="h6 color_mint">
                      Preventing unauthorized access
                    </div>
                    <div className="w-full pt-(--sizing--rem--0-75rem) max-tablet:pt-[.65rem] max-portrait:pt-[.4rem]">
                      <div className="body-text-small color_mint smaller">
                        Adequate security controls reduce the risk of unauthorized access, data theft, or malicious activities by cybercriminals.
                        <br />
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div className="container-flex vertical center">
                <ButtonLarge href="/demo" shine>
                  Get Started
                </ButtonLarge>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
