import { TrustedBySection } from "@/app/_shared/LogoMarquee";
import { CtaSection } from "@/app/_shared/CtaSection";
import { ProductCloudSecurityCollection1 } from "./ProductCloudSecurityCollection1";
import { productCloudSecurityCollection1Data } from "./ProductCloudSecurityCollection1.data";
import { ButtonLarge } from "@/app/_shared/ButtonLarge";
import { SiteNav } from "../../../_shared/SiteNav";
import { SiteFooter } from "../../../_shared/SiteFooter";
import { ProductCloudSecuritySection1 } from "./ProductCloudSecuritySection1";
import { ProductCloudSecuritySection3 } from "./ProductCloudSecuritySection3";
import { ProductCloudSecuritySection4 } from "./ProductCloudSecuritySection4";
import { ProductCloudSecuritySection5 } from "./ProductCloudSecuritySection5";
import { ScrollFeatureSlider, type ScrollFeatureSlide } from "@/app/_shared/ScrollFeatureSlider";

const cloudSecuritySlides: ScrollFeatureSlide[] = [
  {
    heading: "Cloud scan",
    body: "Our platform continuously scans your cloud environment, delivering comprehensive security findings, providing clear insights into your security posture, allowing you to quickly identify and prioritize vulnerabilities based on their importance and scope.",
    image: {
      src: "/assets/product-automatedscan.webp",
      srcSet:
        "/assets/product-automatedscan-p-500.webp 500w, /assets/product-automatedscan-p-800.webp 800w, /assets/product-automatedscan-p-1080.webp 1080w, /assets/product-automatedscan.webp 1352w",
      sizes: "(max-width: 767px) 100vw, 676px",
      width: 676,
    },
  },
  {
    heading: "Automated scan",
    body: "Configure our platform to automatically scan your cloud security environment regularly, providing continuous oversight without manual effort. It features a customized dashboard that consolidates findings, displaying security issues, severity, and affected regions or services.",
    image: {
      src: "/assets/product-automatedscan-2.webp",
      srcSet:
        "/assets/product-automatedscan-p-500-2.webp 500w, /assets/product-automatedscan-p-800-2.webp 800w, /assets/product-automatedscan-p-1080-2.webp 1080w, /assets/product-automatedscan-2.webp 1352w",
      sizes: "(max-width: 767px) 100vw, 676px",
      width: 676,
    },
  },
  {
    heading: "Remediation",
    body: "Our platform not only identifies cloud security failed findings but also provides actionable remediation suggestions tailored to each issue. With our proactive recommendations, you can streamline your remediation process and ensure your cloud environment remains secure, compliant, and resilient.",
    image: {
      src: "/assets/product-remediation.webp",
      srcSet:
        "/assets/product-remediation-p-500.webp 500w, /assets/product-remediation-p-800.webp 800w, /assets/product-remediation-p-1080.webp 1080w, /assets/product-remediation.webp 1352w",
      sizes: "(max-width: 767px) 100vw, 676px",
      width: 676,
    },
  },
];

/**
 * Faithful React port of the Webflow https://mycroft.io/product/cloud-security page. DOM + classes mirror
 * the original 1:1; global styling is in webflow-shared.css, page CSS
 * in product-cloud-security.css. Generated by the Webflow Cloner agent.
 */
export function ProductCloudSecuritySnapshot() {
  return (
    <div className="page-wrapper u-minh-100vh color_rg">
      <div className="styles__global-embed-code w-embed"></div>
      <SiteNav />
      <main id="main" className="page-content">
        <ProductCloudSecuritySection1 />
        <TrustedBySection btm="rg" />
        <ProductCloudSecuritySection3 />
        <div className="scroll-container-outer">
          <div className="scroll-container-inner">
            <section id="product-features" className="section_v2 split_background rg_40earlgrey">
              <div className="page-padding">
                <div className="container-xl">
                  <div className="padding-btm medium">
                    <div className="scroll-slider-outer">
                      <ScrollFeatureSlider id="audit-compliance" slides={cloudSecuritySlides}>
                        <ButtonLarge href="/demo" velvet shine>
                          Book a demo
                        </ButtonLarge>
                      </ScrollFeatureSlider>
                      <div className="btm-tab">
                        <div className="shape-triangle _75_eg flipped mirrored smaller_mobile w-embed">
                          <svg version="1.1" baseProfile="basic" id="Triangle" xmlns="http://www.w3.org/2000/svg" xmlnsXlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 34 38" xmlSpace="preserve">
                            <path fill="currentColor" d="M0,0l34,38H0V0z"></path>
                          </svg>
                        </div>
                        <div className="tab-filler"></div>
                        <div className="shape-triangle _75_eg flipped smaller_mobile w-embed">
                          <svg version="1.1" baseProfile="basic" id="Triangle" xmlns="http://www.w3.org/2000/svg" xmlnsXlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 34 38" xmlSpace="preserve">
                            <path fill="currentColor" d="M0,0l34,38H0V0z"></path>
                          </svg>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </section>
            <section id="platform-features" className="section_v2 tint_40eg">
              <div className="page-padding">
                <div className="container-large">
                  <div className="padding-top small">
                    <div className="padding-btm large">
                      <div className="container-flex vertical center">
                        <div className="eyebrow-label-small product">
                          <div className="eyebrow-small color_rg">
                            Platform features
                          </div>
                        </div>
                        <div className="padding-btm small">
                          <div className="container-flex vertical center">
                            <div className="container-small">
                              <div className="narrow-text-container">
                                <div className="container-flex vertical center">
                                  <h4 className="h4_v2 color_rg">
                                    Unlock robust cloud security with our customizable features
                                  </h4>
                                  <div className="padding-top xxxs">
                                    <div className="text-dek-m">
                                      Ensure the protection of sensitive cloud data with real-time monitoring, remediation, and reporting.
                                      <br />
                                    </div>
                                  </div>
                                </div>
                              </div>
                            </div>
                            <div className="platform-grid">
                              <div className="platform-item">
                                <img src="/assets/features-img2.webp" loading="lazy" width="562.5" sizes="(max-width: 767px) 100vw, 563px" alt="" srcSet="/assets/features-img2-p-500.webp 500w, /assets/features-img2-p-800.webp 800w, /assets/features-img2-p-1080.webp 1080w, /assets/features-img2.webp 1125w" className="platform-img" />
                                <div className="platform-text">
                                  <h6 className="h6 larger_mobile">
                                    Monitoring
                                  </h6>
                                  <div className="body-text-small">
                                    Provides real-time alerts to identify and fix issues quickly, keeping you on track.
                                  </div>
                                </div>
                              </div>
                              <div className="platform-item">
                                <img src="/assets/features-img3.webp" loading="lazy" width="564" sizes="(max-width: 767px) 100vw, 564px" alt="" srcSet="/assets/features-img3-p-500.webp 500w, /assets/features-img3-p-800.webp 800w, /assets/features-img3-p-1080.webp 1080w, /assets/features-img3.webp 1128w" className="platform-img" />
                                <div className="platform-text">
                                  <h6 className="h6 larger_mobile">
                                    Remediation
                                  </h6>
                                  <div className="body-text-small">
                                    Automates issue resolution for tight cloud security without delays.
                                  </div>
                                </div>
                              </div>
                              <div className="platform-item">
                                <img src="/assets/feature-reporting-v1.webp" loading="lazy" width="564" sizes="(max-width: 767px) 100vw, 564px" alt="" srcSet="/assets/feature-reporting-v1-p-500.webp 500w, /assets/feature-reporting-v1-p-800.webp 800w, /assets/feature-reporting-v1-p-1080.webp 1080w, /assets/feature-reporting-v1.webp 1128w" className="platform-img" />
                                <div className="platform-text">
                                  <h6 className="h6 larger_mobile">
                                    Reporting
                                  </h6>
                                  <div className="body-text-small">
                                    Download scan reports for real-time updates on provider statuses and problems
                                  </div>
                                </div>
                              </div>
                            </div>
                            <ButtonLarge href="/demo" shine>
                              Book a demo
                            </ButtonLarge>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </section>
          </div>
        </div>
        <ProductCloudSecuritySection4 />
        <div className="negative-margin-wrapper reduce_top">
          <section id="Features" className="section_v2 color_smoke">
            <div className="page-padding">
              <div className="padding-top xl">
                <div className="container-medium">
                  <div className="container-small narrower_desktop">
                    <div className="container-flex vertical">
                      <h3 className="h3_v2 color_white text_center">
                        Read the latest insights from our experts
                      </h3>
                      <div className="padding-top xxxs">
                        <div className="text-dek-s text_40_grey text_center">
                          Stay secure with expert, data-driven resources to strengthen your security knowledge and ensure compliance confidence.
                        </div>
                      </div>
                    </div>
                  </div>
                  <div className="padding-top small">
                    <div className="padding-btm large">
                      <div className="container-flex space-between _3up_blog">
                        <div className="_3up-blog-wrapper w-dyn-list">
                          <div role="list" className="_3up-blog-grid w-dyn-items">
                            {productCloudSecurityCollection1Data.map((item, i) => (
                              <ProductCloudSecurityCollection1 item={item} key={i} />
                            ))}
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </section>
        </div>
        <ProductCloudSecuritySection5 />
        <CtaSection variant="fireplace" />
      </main>
      <SiteFooter />
    </div>
  );
}
