import { SiteNav } from "../../_shared/SiteNav";
import { SiteFooter } from "../../_shared/SiteFooter";
import { AiDisclosureSection1 } from "./AiDisclosureSection1";
import { AiDisclosureSection2 } from "./AiDisclosureSection2";

/**
 * Faithful React port of the Webflow https://mycroft.io/ai-disclosure page. DOM + classes mirror
 * the original 1:1; global styling is in webflow-shared.css, page CSS
 * in ai-disclosure.css. Generated by the Webflow Cloner agent.
 */
export function AiDisclosureSnapshot() {
  return (
    <div className="page-wrapper u-minh-100vh">
      <div className="styles__global-embed-code w-embed"></div>
      <SiteNav />
      <main id="main" className="page-main nav_v2">
        <AiDisclosureSection1 />
        <AiDisclosureSection2 />
        <SiteFooter />
      </main>
    </div>
  );
}
