import type { Metadata } from "next";
import "./frameworks-gdpr.css";
import { FrameworksGdprSnapshot } from "./_snapshot/FrameworksGdprSnapshot";
import { WebflowInteractions } from "../../_shared/WebflowInteractions";

export const metadata: Metadata = {
  title: "Mycroft Frameworks | GDPR compliance, built for real-world execution",
  description: "Mycroft’s Risk Operations Center removes the operational burden, helping you achieve and maintain GDPR compliance with confidence.",
  openGraph: {
    title: "Mycroft Frameworks | GDPR compliance, built for real-world execution",
    description: "Mycroft’s Risk Operations Center removes the operational burden, helping you achieve and maintain GDPR compliance with confidence.",
    type: "website",
    images: ["https://cdn.prod.website-files.com/6696985a1d3e81308169d89c/6a02510434d7890f916be899_Frameworks-GDPR-Meta_v1.jpg"],
  },
  twitter: {
    card: "summary_large_image",
    title: "Mycroft Frameworks | GDPR compliance, built for real-world execution",
    description: "Mycroft’s Risk Operations Center removes the operational burden, helping you achieve and maintain GDPR compliance with confidence.",
    images: ["https://cdn.prod.website-files.com/6696985a1d3e81308169d89c/6a02510434d7890f916be899_Frameworks-GDPR-Meta_v1.jpg"],
  },
};

/**
 * /frameworks/gdpr: a faithful React rebuild of the Webflow page.
 * Generated by the Webflow Cloner agent from https://mycroft.io/frameworks/gdpr.
 */
export default function FrameworksGdprPage() {
  return (
    <>
      <FrameworksGdprSnapshot />
      <WebflowInteractions />
    </>
  );
}
