import { FaqItem } from "@/app/_shared/Accordion";

/** Section 5 of /product/audit-and-compliance. Generated by the Webflow Cloner agent. */
export function ProductAuditAndComplianceSection5() {
  return (
    <section className="section_v2 color_smoke">
      <div className="pr-(--sizing--rem--2rem) pl-(--sizing--rem--2rem) ml-auto mr-auto relative max-portrait:pr-(--sizing--rem--1-25rem) max-portrait:pl-(--sizing--rem--1-25rem)">
        <div className="w-full max-w-240 ml-auto mr-auto max-tablet:w-[90%] max-tablet:max-w-none max-landscape:w-full max-portrait:w-full">
          <div className="w-full pt-(--sizing--rem--4-5rem) max-tablet:pt-(--sizing--rem--3-5rem) max-landscape:pt-(--sizing--rem--2-5rem) max-portrait:pt-(--sizing--rem--1-5rem)">
            <div className="w-full pb-(--sizing--rem--6rem) max-tablet:pb-(--sizing--rem--5rem) max-landscape:pb-(--sizing--rem--3-5rem) max-portrait:pb-(--sizing--rem--2-5rem)">
              <img src="/assets/faq-notchlabel-desktop.svg" loading="lazy" alt="" className="faq-notch-desktop" />
              <img src="/assets/faq-notchlabel-mobile.svg" loading="lazy" alt="" className="faq-notch-mobile" />
              <div className="container-flex faq_container">
                <h3 className="h3_v2 color_white">
                  Frequently asked questions
                </h3>
                <FaqItem question={<>What are the primary objectives of a cybersecurity audit?
                          <br /></>} first>
                  The primary objectives include assessing the effectiveness of security controls, identifying vulnerabilities, ensuring compliance with regulations and standards, and improving overall risk management practices.
                </FaqItem>
                <FaqItem question="How can our organization prepare for a cybersecurity audit?">
                  Preparation can involve conducting internal assessments, ensuring all documentation is up-to-date, training staff on security policies, and reviewing compliance with relevant regulations. It’s also helpful to ensure that all security controls are functioning and that any identified issues are addressed before the audit.
                </FaqItem>
                <FaqItem question="What is the difference between a compliance audit and a security audit?">
                  A compliance audit focuses on assessing adherence to specific laws, regulations, or standards, while a security audit examines the overall effectiveness of security measures and practices in protecting information systems and data from threats.
                </FaqItem>
                <FaqItem question="What regulations and standards should our organization be compliant with?">
                  This depends on the industry and the type of data being processed. Common standards include GDPR, HIPAA, PCI DSS, and NIST frameworks. Organizations should assess their regulatory landscape and ensure compliance with applicable requirements.
                </FaqItem>
                <FaqItem question="How can we effectively communicate audit findings to stakeholders?">
                  Effective communication involves presenting findings in a clear, concise manner, highlighting both risks and recommended actions. Use visual aids, such as charts and dashboards, to convey the state of compliance and security clearly, and tailor the message based on the audience's technical understanding and interests.
                </FaqItem>
                <FaqItem question="What steps should we take if we fail an audit?" last>
                  If an audit reveals non-compliance or vulnerabilities, organizations should develop an action plan to address the issues identified. This includes remediating the findings, implementing necessary changes to policies and controls, and scheduling follow-up reviews to ensure compliance improvements are sustained.
                </FaqItem>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
