import { TrustedBySection } from "@/app/_shared/LogoMarquee";
import { CtaSection } from "@/app/_shared/CtaSection";
import { ProductAuditAndComplianceCollection1 } from "./ProductAuditAndComplianceCollection1";
import { productAuditAndComplianceCollection1Data } from "./ProductAuditAndComplianceCollection1.data";
import { ButtonLarge } from "@/app/_shared/ButtonLarge";
import { SiteNav } from "../../../_shared/SiteNav";
import { SiteFooter } from "../../../_shared/SiteFooter";
import { ProductAuditAndComplianceSection1 } from "./ProductAuditAndComplianceSection1";
import { ProductAuditAndComplianceSection3 } from "./ProductAuditAndComplianceSection3";
import { ProductAuditAndComplianceSection4 } from "./ProductAuditAndComplianceSection4";
import { ProductAuditAndComplianceSection5 } from "./ProductAuditAndComplianceSection5";
import { ScrollFeatureSlider, type ScrollFeatureSlide } from "@/app/_shared/ScrollFeatureSlider";

const auditComplianceSlides: ScrollFeatureSlide[] = [
  {
    heading: "Frameworks dashboard",
    body: "Our security frameworks dashboard offers a clear view of various security frameworks and their completion statuses. Track progress across standards like SOC 2, GDPR, HIPAA, and ISO 27001 to ensure compliance with industry requirements.",
    image: {
      src: "/assets/product-frameworks.webp",
      srcSet:
        "/assets/product-frameworks-p-500.webp 500w, /assets/product-frameworks-p-800.webp 800w, /assets/product-frameworks-p-1080.webp 1080w, /assets/product-frameworks.webp 1352w",
      sizes: "(max-width: 479px) 100vw, 676px",
      width: 676,
    },
  },
  {
    heading: "Custom controls",
    body: "Our platform lets users create custom security controls with Mycroft AI, enabling GRC engineers to design unique security measures beyond standard compliance. This feature addresses your organization's specific risks, enhancing your security posture compared to competitors.",
    image: {
      src: "/assets/product-controls.webp",
      srcSet:
        "/assets/product-controls-p-500.webp 500w, /assets/product-controls-p-800.webp 800w, /assets/product-controls-p-1080.webp 1080w, /assets/product-controls.webp 1352w",
      sizes: "(max-width: 479px) 100vw, 676px",
      width: 676,
    },
  },
  {
    heading: "Automated tests and evidence",
    body: "Our platform automatically generates tailored tests for your custom controls and seamlessly collects evidence, simplifying compliance validation and ensuring your controls are consistently verified without manual effort.",
    image: {
      src: "/assets/product-automation.webp",
      srcSet:
        "/assets/product-automation-p-500.webp 500w, /assets/product-automation-p-800.webp 800w, /assets/product-automation-p-1080.webp 1080w, /assets/product-automation.webp 1352w",
      sizes: "(max-width: 479px) 100vw, 676px",
      width: 676,
    },
  },
];

/**
 * Faithful React port of the Webflow https://mycroft.io/product/audit-and-compliance page. DOM + classes mirror
 * the original 1:1; global styling is in webflow-shared.css, page CSS
 * in product-audit-and-compliance.css. Generated by the Webflow Cloner agent.
 */
export function ProductAuditAndComplianceSnapshot() {
  return (
    <div className="page-wrapper u-minh-100vh color_rg">
      <div className="styles__global-embed-code w-embed"></div>
      <SiteNav />
      <main id="main" className="page-content">
        <ProductAuditAndComplianceSection1 />
        <TrustedBySection btm="rg" />
        <ProductAuditAndComplianceSection3 />
        <div className="scroll-container-outer">
          <div className="scroll-container-inner">
            <section id="product-features" className="section_v2 split_background rg_40earlgrey">
              <div className="pr-(--sizing--rem--2rem) pl-(--sizing--rem--2rem) ml-auto mr-auto relative max-portrait:pr-(--sizing--rem--1-25rem) max-portrait:pl-(--sizing--rem--1-25rem)">
                <div className="container-xl">
                  <div className="w-full pb-(--sizing--rem--4-5rem) max-tablet:pb-(--sizing--rem--3-5rem) max-landscape:pb-(--sizing--rem--2-5rem) max-portrait:pb-(--sizing--rem--1-5rem)">
                    <div className="scroll-slider-outer">
                      <ScrollFeatureSlider id="audit-compliance" slides={auditComplianceSlides}>
                        <ButtonLarge href="/demo" velvet shine>
                          Book a demo
                        </ButtonLarge>
                      </ScrollFeatureSlider>
                      <div className="btm-tab">
                        <div className="shape-triangle _75_eg flipped mirrored smaller_mobile w-embed">
                          <svg version="1.1" baseProfile="basic" id="Triangle" xmlns="http://www.w3.org/2000/svg" xmlnsXlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 34 38" xmlSpace="preserve">
                            <path fill="currentColor" d="M0,0l34,38H0V0z"></path>
                          </svg>
                        </div>
                        <div className="tab-filler"></div>
                        <div className="shape-triangle _75_eg flipped smaller_mobile w-embed">
                          <svg version="1.1" baseProfile="basic" id="Triangle" xmlns="http://www.w3.org/2000/svg" xmlnsXlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 34 38" xmlSpace="preserve">
                            <path fill="currentColor" d="M0,0l34,38H0V0z"></path>
                          </svg>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </section>
            <section id="platform-features" className="section_v2 tint_40eg">
              <div className="pr-(--sizing--rem--2rem) pl-(--sizing--rem--2rem) ml-auto mr-auto relative max-portrait:pr-(--sizing--rem--1-25rem) max-portrait:pl-(--sizing--rem--1-25rem)">
                <div className="w-full max-w-300 ml-auto mr-auto">
                  <div className="w-full pt-(--sizing--rem--2-5rem) max-tablet:pt-(--sizing--rem--2rem) max-landscape:pt-(--sizing--rem--1-5rem) max-portrait:pt-(--sizing--rem--1rem)">
                    <div className="w-full pb-(--sizing--rem--6rem) max-tablet:pb-(--sizing--rem--5rem) max-landscape:pb-(--sizing--rem--3-5rem) max-portrait:pb-(--sizing--rem--2-5rem)">
                      <div className="container-flex vertical center">
                        <div className="eyebrow-label-small product">
                          <div className="eyebrow-small color_rg">
                            Platform features
                          </div>
                        </div>
                        <div className="w-full pb-(--sizing--rem--2-5rem) max-tablet:pb-(--sizing--rem--2rem) max-landscape:pb-(--sizing--rem--1-5rem) max-portrait:pb-(--sizing--rem--1rem)">
                          <div className="container-flex vertical center">
                            <div className="w-full max-w-200 ml-auto mr-auto max-tablet:w-[80%] max-tablet:max-w-none max-landscape:w-[92%] max-portrait:w-full">
                              <div className="narrow-text-container">
                                <div className="container-flex vertical center">
                                  <h4 className="h4_v2 color_rg">
                                    Accelerate your path to compliance with our advanced features
                                  </h4>
                                  <div className="w-full pt-(--sizing--rem--0-75rem) max-tablet:pt-[.65rem] max-portrait:pt-[.4rem]">
                                    <div className="text-dek-m">
                                      Our platform accelerates compliance through customizable controls, real-time dashboards, and streamlined workflows – enabling efficient and rapid growth.
                                    </div>
                                  </div>
                                </div>
                              </div>
                            </div>
                            <div className="platform-grid">
                              <div className="platform-item">
                                <img src="/assets/features-img1.webp" loading="lazy" width="564" sizes="(max-width: 479px) 100vw, 564px" alt="" srcSet="/assets/features-img1-p-500.webp 500w, /assets/features-img1-p-800.webp 800w, /assets/features-img1-p-1080.webp 1080w, /assets/features-img1.webp 1128w" className="platform-img" />
                                <div className="platform-text">
                                  <h6 className="h6 larger_mobile">
                                    Integrations
                                  </h6>
                                  <div className="body-text-small">
                                    Connects with existing tools to automate data collection and speed up compliance efforts.
                                  </div>
                                </div>
                              </div>
                              <div className="platform-item">
                                <img src="/assets/features-img2.webp" loading="lazy" width="562.5" sizes="(max-width: 479px) 100vw, 563px" alt="" srcSet="/assets/features-img2-p-500.webp 500w, /assets/features-img2-p-800.webp 800w, /assets/features-img2-p-1080.webp 1080w, /assets/features-img2.webp 1125w" className="platform-img" />
                                <div className="platform-text">
                                  <h6 className="h6 larger_mobile">
                                    Monitoring
                                  </h6>
                                  <div className="body-text-small">
                                    Provides real-time alerts to identify and fix issues quickly, keeping you on track.
                                  </div>
                                </div>
                              </div>
                              <div className="platform-item">
                                <img src="/assets/features-img3.webp" loading="lazy" width="564" sizes="(max-width: 479px) 100vw, 564px" alt="" srcSet="/assets/features-img3-p-500.webp 500w, /assets/features-img3-p-800.webp 800w, /assets/features-img3-p-1080.webp 1080w, /assets/features-img3.webp 1128w" className="platform-img" />
                                <div className="platform-text">
                                  <h6 className="h6 larger_mobile">
                                    Remediation
                                  </h6>
                                  <div className="body-text-small">
                                    Automates issue resolution for fast, efficient compliance without delays.
                                  </div>
                                </div>
                              </div>
                            </div>
                            <ButtonLarge href="/demo" shine>
                              Book a demo
                            </ButtonLarge>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </section>
          </div>
        </div>
        <ProductAuditAndComplianceSection4 />
        <div className="negative-margin-wrapper reduce_top">
          <section id="Features" className="section_v2 color_smoke">
            <div className="pr-(--sizing--rem--2rem) pl-(--sizing--rem--2rem) ml-auto mr-auto relative max-portrait:pr-(--sizing--rem--1-25rem) max-portrait:pl-(--sizing--rem--1-25rem)">
              <div className="w-full pt-(--sizing--rem--8-5rem) max-tablet:pt-(--sizing--rem--6-5rem) max-landscape:pt-(--sizing--rem--4-5rem) max-portrait:pt-(--sizing--rem--3-5rem)">
                <div className="w-full max-w-240 ml-auto mr-auto max-tablet:w-[90%] max-tablet:max-w-none max-landscape:w-full max-portrait:w-full">
                  <div className="w-full max-w-184 ml-auto mr-auto max-tablet:w-[80%] max-tablet:max-w-none max-landscape:w-[92%] max-portrait:w-full">
                    <div className="container-flex vertical">
                      <h3 className="h3_v2 color_white text_center">
                        Read the latest insights from our experts
                      </h3>
                      <div className="w-full pt-(--sizing--rem--0-75rem) max-tablet:pt-[.65rem] max-portrait:pt-[.4rem]">
                        <div className="text-dek-s text_40_grey text_center">
                          Stay secure with expert, data-driven resources to strengthen your security knowledge and ensure compliance confidence.
                        </div>
                      </div>
                    </div>
                  </div>
                  <div className="w-full pt-(--sizing--rem--2-5rem) max-tablet:pt-(--sizing--rem--2rem) max-landscape:pt-(--sizing--rem--1-5rem) max-portrait:pt-(--sizing--rem--1rem)">
                    <div className="w-full pb-(--sizing--rem--6rem) max-tablet:pb-(--sizing--rem--5rem) max-landscape:pb-(--sizing--rem--3-5rem) max-portrait:pb-(--sizing--rem--2-5rem)">
                      <div className="container-flex space-between _3up_blog">
                        <div className="_3up-blog-wrapper w-dyn-list">
                          <div role="list" className="_3up-blog-grid w-dyn-items">
                            {productAuditAndComplianceCollection1Data.map((item, i) => (
                              <ProductAuditAndComplianceCollection1 item={item} key={i} />
                            ))}
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </section>
        </div>
        <ProductAuditAndComplianceSection5 />
        <CtaSection variant="lamp" />
      </main>
      <SiteFooter />
    </div>
  );
}
