import { TrustedBySection } from "@/app/_shared/LogoMarquee";
import { CtaSection } from "@/app/_shared/CtaSection";
import { ProductAuditAndComplianceCollection1 } from "./ProductAuditAndComplianceCollection1";
import { productAuditAndComplianceCollection1Data } from "./ProductAuditAndComplianceCollection1.data";
import { ButtonLarge } from "@/app/_shared/ButtonLarge";
import { SiteNav } from "../../../_shared/SiteNav";
import { SiteFooter } from "../../../_shared/SiteFooter";
import { ProductAuditAndComplianceSection1 } from "./ProductAuditAndComplianceSection1";
import { ProductAuditAndComplianceSection3 } from "./ProductAuditAndComplianceSection3";
import { ProductAuditAndComplianceSection4 } from "./ProductAuditAndComplianceSection4";
import { ProductAuditAndComplianceSection5 } from "./ProductAuditAndComplianceSection5";

/**
 * Faithful React port of the Webflow https://mycroft.io/product/audit-and-compliance page. DOM + classes mirror
 * the original 1:1; global styling is in webflow-shared.css, page CSS
 * in product-audit-and-compliance.css. Generated by the Webflow Cloner agent.
 */
export function ProductAuditAndComplianceSnapshot() {
  return (
    <div className="page-wrapper u-minh-100vh color_rg">
      <div className="styles__global-embed-code w-embed"></div>
      <SiteNav />
      <main id="main" className="page-content">
        <ProductAuditAndComplianceSection1 />
        <TrustedBySection btm="rg" />
        <ProductAuditAndComplianceSection3 />
        <div className="scroll-container-outer">
          <div className="scroll-container-inner">
            <section id="product-features" className="section_v2 split_background rg_40earlgrey">
              <div className="page-padding">
                <div className="container-xl">
                  <div className="padding-btm medium">
                    <div className="scroll-slider-outer">
                      <section id="audit-compliance" className="scroll-slider-inner">
                        <div className="enumeration-container">
                          <div className="enumeration-counter">
                            <div className="enumeration-absolute">
                              <div className="body-text-medium _75_rg enumeration1" style={{"willChange": "opacity", "opacity": "1"}}>
                                1
                                <br />
                              </div>
                            </div>
                            <div className="enumeration-absolute">
                              <div className="body-text-medium _75_rg enumeration2" style={{"willChange": "opacity", "opacity": "0"}}>
                                2
                                <br />
                              </div>
                            </div>
                            <div className="enumeration-absolute">
                              <div className="body-text-medium _75_rg enumeration3" style={{"willChange": "opacity", "opacity": "0"}}>
                                3
                              </div>
                            </div>
                          </div>
                          <div className="body-text-medium _75_rg">
                            /
                          </div>
                          <div className="body-text-medium _75_rg">
                            3
                          </div>
                        </div>
                        <div className="features-row static" style={{"willChange": "opacity", "opacity": "0"}}>
                          <div className="features-text">
                            <h4 className="h4_v2 color_rg">
                              Custom controls
                            </h4>
                            <div className="body-text-large smaller_tablet">
                              Our platform lets users create custom security controls with Mycroft AI, enabling GRC engineers to design unique security measures beyond standard compliance. This feature addresses your organization's specific risks, enhancing your security posture compared to competitors.
                            </div>
                          </div>
                          <div className="features-img-container">
                            <img src="/assets/product-frameworks.webp" loading="lazy" width="676" sizes="(max-width: 479px) 100vw, 676px" alt="" srcSet="/assets/product-frameworks-p-500.webp 500w, /assets/product-frameworks-p-800.webp 800w, /assets/product-frameworks-p-1080.webp 1080w, /assets/product-frameworks.webp 1352w" className="features-img" />
                          </div>
                        </div>
                        <div className="features-row absolute slide1">
                          <div className="features-text slide1" style={{"willChange": "transform, opacity", "transform": "translate3d(0px, 0px, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg)", "transformStyle": "preserve-3d", "opacity": "1"}}>
                            <h4 className="h4_v2 color_rg">
                              Frameworks dashboard
                            </h4>
                            <div className="body-text-large smaller_tablet">
                              Our security frameworks dashboard offers a clear view of various security frameworks and their completion statuses. Track progress across standards like SOC 2, GDPR, HIPAA, and ISO 27001 to ensure compliance with industry requirements.
                            </div>
                          </div>
                          <div className="features-img-container slide1" style={{"willChange": "transform, opacity", "transform": "translate3d(0px, 0px, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg)", "transformStyle": "preserve-3d", "opacity": "1"}}>
                            <img src="/assets/product-frameworks.webp" loading="lazy" width="676" sizes="(max-width: 479px) 100vw, 676px" alt="" srcSet="/assets/product-frameworks-p-500.webp 500w, /assets/product-frameworks-p-800.webp 800w, /assets/product-frameworks-p-1080.webp 1080w, /assets/product-frameworks.webp 1352w" className="features-img" />
                          </div>
                        </div>
                        <div className="features-row absolute slide2">
                          <div className="features-text slide2 wf-reveal" style={{"willChange": "transform, opacity", "transform": "translate3d(0px, 40px, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg)", "transformStyle": "preserve-3d", "opacity": "0", "--wf-op-dur": "1000ms", "--wf-op-delay": "0ms", "--wf-op-ease": "cubic-bezier(0.165,0.84,0.44,1)", "--wf-tr-dur": "1000ms", "--wf-tr-delay": "0ms", "--wf-tr-ease": "cubic-bezier(0.165,0.84,0.44,1)"}}>
                            <h4 className="h4_v2 color_rg">
                              Custom controls
                            </h4>
                            <div className="body-text-large smaller_tablet">
                              Our platform lets users create custom security controls with Mycroft AI, enabling GRC engineers to design unique security measures beyond standard compliance. This feature addresses your organization's specific risks, enhancing your security posture compared to competitors.
                            </div>
                          </div>
                          <div className="features-img-container slide2 wf-reveal" style={{"willChange": "transform, opacity", "transform": "translate3d(-40px, 0px, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg)", "transformStyle": "preserve-3d", "opacity": "0", "--wf-op-dur": "1000ms", "--wf-op-delay": "0ms", "--wf-op-ease": "cubic-bezier(0.165,0.84,0.44,1)", "--wf-tr-dur": "1000ms", "--wf-tr-delay": "0ms", "--wf-tr-ease": "cubic-bezier(0.165,0.84,0.44,1)"}}>
                            <img src="/assets/product-controls.webp" loading="lazy" width="676" sizes="(max-width: 479px) 100vw, 676px" alt="" srcSet="/assets/product-controls-p-500.webp 500w, /assets/product-controls-p-800.webp 800w, /assets/product-controls-p-1080.webp 1080w, /assets/product-controls.webp 1352w" className="features-img" />
                          </div>
                        </div>
                        <div className="features-row absolute slide3">
                          <div className="features-text slide3 wf-reveal" style={{"willChange": "transform, opacity", "transform": "translate3d(0px, 40px, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg)", "transformStyle": "preserve-3d", "opacity": "0", "--wf-op-dur": "1000ms", "--wf-op-delay": "0ms", "--wf-op-ease": "cubic-bezier(0.165,0.84,0.44,1)", "--wf-tr-dur": "1000ms", "--wf-tr-delay": "0ms", "--wf-tr-ease": "cubic-bezier(0.165,0.84,0.44,1)"}}>
                            <h4 className="h4_v2 color_rg">
                              Automated tests and evidence
                            </h4>
                            <div className="body-text-large smaller_tablet">
                              Our platform automatically generates tailored tests for your custom controls and seamlessly collects evidence, simplifying compliance validation and ensuring your controls are consistently verified without manual effort.
                            </div>
                          </div>
                          <div className="features-img-container slide3 wf-reveal" style={{"willChange": "transform, opacity", "transform": "translate3d(-40px, 0px, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg)", "transformStyle": "preserve-3d", "opacity": "0", "--wf-op-dur": "1000ms", "--wf-op-delay": "0ms", "--wf-op-ease": "cubic-bezier(0.165,0.84,0.44,1)", "--wf-tr-dur": "1000ms", "--wf-tr-delay": "0ms", "--wf-tr-ease": "cubic-bezier(0.165,0.84,0.44,1)"}}>
                            <img src="/assets/product-automation.webp" loading="lazy" width="676" sizes="(max-width: 479px) 100vw, 676px" alt="" srcSet="/assets/product-automation-p-500.webp 500w, /assets/product-automation-p-800.webp 800w, /assets/product-automation-p-1080.webp 1080w, /assets/product-automation.webp 1352w" className="features-img" />
                          </div>
                        </div>
                        <ButtonLarge href="/demo" velvet shine>
                          Book a demo
                        </ButtonLarge>
                      </section>
                      <div className="btm-tab">
                        <div className="shape-triangle _75_eg flipped mirrored smaller_mobile w-embed">
                          <svg version="1.1" baseProfile="basic" id="Triangle" xmlns="http://www.w3.org/2000/svg" xmlnsXlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 34 38" xmlSpace="preserve">
                            <path fill="currentColor" d="M0,0l34,38H0V0z"></path>
                          </svg>
                        </div>
                        <div className="tab-filler"></div>
                        <div className="shape-triangle _75_eg flipped smaller_mobile w-embed">
                          <svg version="1.1" baseProfile="basic" id="Triangle" xmlns="http://www.w3.org/2000/svg" xmlnsXlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 34 38" xmlSpace="preserve">
                            <path fill="currentColor" d="M0,0l34,38H0V0z"></path>
                          </svg>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </section>
            <section id="platform-features" className="section_v2 tint_40eg">
              <div className="page-padding">
                <div className="container-large">
                  <div className="padding-top small">
                    <div className="padding-btm large">
                      <div className="container-flex vertical center">
                        <div className="eyebrow-label-small product">
                          <div className="eyebrow-small color_rg">
                            Platform features
                          </div>
                        </div>
                        <div className="padding-btm small">
                          <div className="container-flex vertical center">
                            <div className="container-small">
                              <div className="narrow-text-container">
                                <div className="container-flex vertical center">
                                  <h4 className="h4_v2 color_rg">
                                    Accelerate your path to compliance with our advanced features
                                  </h4>
                                  <div className="padding-top xxxs">
                                    <div className="text-dek-m">
                                      Our platform accelerates compliance through customizable controls, real-time dashboards, and streamlined workflows – enabling efficient and rapid growth.
                                    </div>
                                  </div>
                                </div>
                              </div>
                            </div>
                            <div className="platform-grid">
                              <div className="platform-item">
                                <img src="/assets/features-img1.webp" loading="lazy" width="564" sizes="(max-width: 479px) 100vw, 564px" alt="" srcSet="/assets/features-img1-p-500.webp 500w, /assets/features-img1-p-800.webp 800w, /assets/features-img1-p-1080.webp 1080w, /assets/features-img1.webp 1128w" className="platform-img" />
                                <div className="platform-text">
                                  <h6 className="h6 larger_mobile">
                                    Integrations
                                  </h6>
                                  <div className="body-text-small">
                                    Connects with existing tools to automate data collection and speed up compliance efforts.
                                  </div>
                                </div>
                              </div>
                              <div className="platform-item">
                                <img src="/assets/features-img2.webp" loading="lazy" width="562.5" sizes="(max-width: 479px) 100vw, 563px" alt="" srcSet="/assets/features-img2-p-500.webp 500w, /assets/features-img2-p-800.webp 800w, /assets/features-img2-p-1080.webp 1080w, /assets/features-img2.webp 1125w" className="platform-img" />
                                <div className="platform-text">
                                  <h6 className="h6 larger_mobile">
                                    Monitoring
                                  </h6>
                                  <div className="body-text-small">
                                    Provides real-time alerts to identify and fix issues quickly, keeping you on track.
                                  </div>
                                </div>
                              </div>
                              <div className="platform-item">
                                <img src="/assets/features-img3.webp" loading="lazy" width="564" sizes="(max-width: 479px) 100vw, 564px" alt="" srcSet="/assets/features-img3-p-500.webp 500w, /assets/features-img3-p-800.webp 800w, /assets/features-img3-p-1080.webp 1080w, /assets/features-img3.webp 1128w" className="platform-img" />
                                <div className="platform-text">
                                  <h6 className="h6 larger_mobile">
                                    Remediation
                                  </h6>
                                  <div className="body-text-small">
                                    Automates issue resolution for fast, efficient compliance without delays.
                                  </div>
                                </div>
                              </div>
                            </div>
                            <ButtonLarge href="/demo" shine>
                              Book a demo
                            </ButtonLarge>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </section>
          </div>
        </div>
        <ProductAuditAndComplianceSection4 />
        <div className="negative-margin-wrapper reduce_top">
          <section id="Features" className="section_v2 color_smoke">
            <div className="page-padding">
              <div className="padding-top xl">
                <div className="container-medium">
                  <div className="container-small narrower_desktop">
                    <div className="container-flex vertical">
                      <h3 className="h3_v2 color_white text_center">
                        Read the latest insights from our experts
                      </h3>
                      <div className="padding-top xxxs">
                        <div className="text-dek-s text_40_grey text_center">
                          Stay secure with expert, data-driven resources to strengthen your security knowledge and ensure compliance confidence.
                        </div>
                      </div>
                    </div>
                  </div>
                  <div className="padding-top small">
                    <div className="padding-btm large">
                      <div className="container-flex space-between _3up_blog">
                        <div className="_3up-blog-wrapper w-dyn-list">
                          <div role="list" className="_3up-blog-grid w-dyn-items">
                            {productAuditAndComplianceCollection1Data.map((item, i) => (
                              <ProductAuditAndComplianceCollection1 item={item} key={i} />
                            ))}
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </section>
        </div>
        <ProductAuditAndComplianceSection5 />
        <CtaSection variant="lamp" />
      </main>
      <SiteFooter />
    </div>
  );
}
