/** Section 3 of /product/audit-and-compliance. Generated by the Webflow Cloner agent. */
export function ProductAuditAndComplianceSection3() {
  return (
    <section id="compliance" className="section_v2">
      <div className="section-overlap">
        <div className="page-padding">
          <div className="container-small">
            <div className="padding-top small">
              <div className="padding-btm medium">
                <div className="container-flex vertical center">
                  <div className="eyebrow-label-small compliance-margins">
                    <div className="eyebrow-small color_mint">
                      Compliance
                    </div>
                  </div>
                  <div className="padding-btm xsmall">
                    <div className="container-flex vertical">
                      <div className="narrow-text-container">
                        <div className="container-flex vertical center">
                          <h4 className="h4_v2 color_white">
                            Leverage enterprise security
                          </h4>
                          <div className="padding-top xxxs">
                            <div className="text-dek-s text_40_grey">
                              Mycroft’s integrated platform with its AI Agents is the platform for your entire security and compliance stack, so that you can focus on everything else.
                            </div>
                          </div>
                        </div>
                      </div>
                      <div className="compliance-slider-container">
                        <div data-delay="4000" data-animation="slide" className="compliance-slider w-slider" data-autoplay="true" data-easing="ease" data-hide-arrows="true" data-disable-swipe="false" data-autoplay-limit="0" data-nav-spacing="8" data-duration="500" data-infinite="true" id="compliance-slider" role="region" aria-label="carousel">
                          <div className="w-embed"></div>
                          <div className="compliance-slider-mask w-slider-mask" id="w-slider-mask-0">
                            <div className="compliance-slide w-slide" aria-label="1 of 3" role="group" style={{"transition": "all", "transform": "translateX(0px)", "opacity": "1"}}>
                              <div className="container-flex vertical center">
                                <img src="/assets/compliance-slide1.webp" loading="lazy" width="800" sizes="(max-width: 767px) 100vw, 800px" alt="" srcSet="/assets/compliance-slide1-p-500.webp 500w, /assets/compliance-slide1-p-800.webp 800w, /assets/compliance-slide1-p-1080.webp 1080w, /assets/compliance-slide1.webp 1600w" className="compliance-slide-img" />
                                <div className="compliance-slider-text smaller">
                                  Enable enterprise-grade security and compliance for all companies
                                </div>
                              </div>
                            </div>
                            <div className="compliance-slide w-slide" aria-label="2 of 3" role="group" aria-hidden="true" style={{"transition": "all", "transform": "translateX(0px)", "opacity": "1"}}>
                              <div className="container-flex vertical center" aria-hidden="true">
                                <img src="/assets/compliance-slide2-x2.webp" loading="lazy" width="800" sizes="(max-width: 767px) 100vw, 800px" alt="" srcSet="/assets/compliance-slide2-x2-p-500.webp 500w, /assets/compliance-slide2-x2-p-800.webp 800w, /assets/compliance-slide2-x2-p-1080.webp 1080w, /assets/compliance-slide2-x2.webp 1600w" className="compliance-slide-img" aria-hidden="true" />
                                <div className="compliance-slider-text smaller" aria-hidden="true">
                                  Achieve multiple certifications in the time it usually takes to acquire one
                                </div>
                              </div>
                            </div>
                            <div className="compliance-slide w-slide" aria-label="3 of 3" role="group" aria-hidden="true" style={{"transition": "all", "transform": "translateX(0px)", "opacity": "1"}}>
                              <div className="container-flex vertical center" aria-hidden="true">
                                <img src="/assets/compliance-slide3-x2.webp" loading="lazy" width="800" sizes="(max-width: 767px) 100vw, 800px" alt="" srcSet="/assets/compliance-slide3-x2-p-500.webp 500w, /assets/compliance-slide3-x2-p-800.webp 800w, /assets/compliance-slide3-x2-p-1080.webp 1080w, /assets/compliance-slide3-x2.webp 1600w" className="compliance-slide-img" aria-hidden="true" />
                                <div className="compliance-slider-text smaller" aria-hidden="true">
                                  Otherwise annoying audits
                                  <span className="no-break normal_mobile" aria-hidden="true">
                                    become effortless
                                  </span>
                                </div>
                              </div>
                            </div>
                            <div aria-live="off" aria-atomic="true" className="w-slider-aria-label" data-wf-ignore=""></div>
                          </div>
                          <div className="w-slider-nav w-round">
                            <div className="w-slider-dot w-active" data-wf-ignore="" aria-label="Show slide 1 of 3" aria-pressed="true" role="button" tabIndex={0} style={{"marginLeft": "8px", "marginRight": "8px"}}></div>
                            <div className="w-slider-dot" data-wf-ignore="" aria-label="Show slide 2 of 3" aria-pressed="false" role="button" tabIndex={-1} style={{"marginLeft": "8px", "marginRight": "8px"}}></div>
                            <div className="w-slider-dot" data-wf-ignore="" aria-label="Show slide 3 of 3" aria-pressed="false" role="button" tabIndex={-1} style={{"marginLeft": "8px", "marginRight": "8px"}}></div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
