import { ArrowTextLink } from "@/app/_shared/ArrowTextLink";

/** Section 2 of /frameworks/soc2. Generated by the Webflow Cloner agent. */
export function FrameworksSoc2Section2() {
  return (
    <section id="fw-features" className="section_v2 tint_60eg overflow_hidden">
      <div className="page-padding">
        <div className="container-small fw_features_hed">
          <div className="padding-top large">
            <div className="container-flex vertical">
              <div className="eyebrow-label-small product">
                <div className="eyebrow-small color_rg">
                  Features
                </div>
              </div>
              <h2 className="h2_v2 color_rg text_center">
                Mycroft’s AI platform solutions to
                <span className="no-wrap">
                  SOC 2
                </span>
              </h2>
              <div className="padding-top xxs">
                <div className="text-dek-l text_center">
                  A snapshot on how our platform features answer specific needs for
                  <span className="no-wrap">
                    SOC 2
                  </span>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div className="container-large">
          <div className="padding-top medium">
            <div className="padding-btm large">
              <div className="product-container">
                <section id="app-security" className="product-feature">
                  <div className="product-text wf-reveal" style={{"willChange": "opacity, transform", "opacity": "0", "transform": "translate3d(-100px, 0px, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg)", "transformStyle": "preserve-3d", "--wf-op-dur": "1000ms", "--wf-op-delay": "0ms", "--wf-op-ease": "cubic-bezier(0.165,0.84,0.44,1)", "--wf-tr-dur": "1000ms", "--wf-tr-delay": "0ms", "--wf-tr-ease": "cubic-bezier(0.165,0.84,0.44,1)"}}>
                    <h4 className="h4_v2 color_rg">
                      AI policy generator
                    </h4>
                    <div className="body-text-medium">
                      Generate tailored security and compliance policies in minutes using AI-powered automation designed to align with industry frameworks, reduce manual work, and accelerate audit readiness.
                    </div>
                    <ArrowTextLink href="/demo">
                      Book a demo
                    </ArrowTextLink>
                  </div>
                  <div className="product-feature-img wf-reveal" style={{"willChange": "opacity, transform", "opacity": "0", "transform": "translate3d(100px, 0px, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg)", "transformStyle": "preserve-3d", "--wf-op-dur": "1000ms", "--wf-op-delay": "0ms", "--wf-op-ease": "cubic-bezier(0.165,0.84,0.44,1)", "--wf-tr-dur": "1000ms", "--wf-tr-delay": "0ms", "--wf-tr-ease": "cubic-bezier(0.165,0.84,0.44,1)"}}>
                    <img src="/assets/ai-policy-generator.webp" loading="lazy" sizes="(max-width: 1360px) 100vw, 1360px" srcSet="/assets/ai-policy-generator-p-500.webp 500w, /assets/ai-policy-generator-p-800.webp 800w, /assets/ai-policy-generator-p-1080.webp 1080w, /assets/ai-policy-generator.webp 1360w" alt="" className="fw-features-img" />
                  </div>
                </section>
                <section id="threat-management" className="product-feature even-child">
                  <div className="product-feature-img img-left wf-reveal" style={{"willChange": "opacity, transform", "opacity": "0", "transform": "translate3d(-100px, 0px, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg)", "transformStyle": "preserve-3d", "--wf-op-dur": "1000ms", "--wf-op-delay": "0ms", "--wf-op-ease": "cubic-bezier(0.165,0.84,0.44,1)", "--wf-tr-dur": "1000ms", "--wf-tr-delay": "0ms", "--wf-tr-ease": "cubic-bezier(0.165,0.84,0.44,1)"}}>
                    <img src="/assets/custom-controls.webp" loading="lazy" sizes="(max-width: 1360px) 100vw, 1360px" srcSet="/assets/custom-controls-p-500.webp 500w, /assets/custom-controls-p-800.webp 800w, /assets/custom-controls-p-1080.webp 1080w, /assets/custom-controls.webp 1360w" alt="" className="fw-features-img" />
                  </div>
                  <div className="product-text text-right wf-reveal" style={{"willChange": "opacity, transform", "opacity": "0", "transform": "translate3d(100px, 0px, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg)", "transformStyle": "preserve-3d", "--wf-op-dur": "1000ms", "--wf-op-delay": "0ms", "--wf-op-ease": "cubic-bezier(0.165,0.84,0.44,1)", "--wf-tr-dur": "1000ms", "--wf-tr-delay": "0ms", "--wf-tr-ease": "cubic-bezier(0.165,0.84,0.44,1)"}}>
                    <h4 className="h4_v2 color_rg">
                      Custom controls
                    </h4>
                    <div className="body-text-medium">
                      Create and manage custom security controls tailored to your organization’s operational, regulatory, and customer requirements while simplifying compliance mapping across frameworks.
                    </div>
                    <ArrowTextLink href="/demo">
                      Book a demo
                    </ArrowTextLink>
                  </div>
                </section>
                <section id="agentic-ai" className="product-feature last-child">
                  <div className="product-text wf-reveal" style={{"willChange": "opacity, transform", "opacity": "0", "transform": "translate3d(-100px, 0px, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg)", "transformStyle": "preserve-3d", "--wf-op-dur": "1000ms", "--wf-op-delay": "0ms", "--wf-op-ease": "cubic-bezier(0.165,0.84,0.44,1)", "--wf-tr-dur": "1000ms", "--wf-tr-delay": "0ms", "--wf-tr-ease": "cubic-bezier(0.165,0.84,0.44,1)"}}>
                    <h4 className="h4_v2 color_rg">
                      Automatic evidence collection
                    </h4>
                    <div className="body-text-medium">
                      Automatically collect and organize audit evidence from your cloud infrastructure, apps, and systems to reduce manual tasks and maintain continuous compliance visibility.
                    </div>
                    <ArrowTextLink href="/demo">
                      Book a demo
                    </ArrowTextLink>
                  </div>
                  <div className="product-feature-img wf-reveal" style={{"willChange": "opacity, transform", "opacity": "0", "transform": "translate3d(100px, 0px, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg)", "transformStyle": "preserve-3d", "--wf-op-dur": "1000ms", "--wf-op-delay": "0ms", "--wf-op-ease": "cubic-bezier(0.165,0.84,0.44,1)", "--wf-tr-dur": "1000ms", "--wf-tr-delay": "0ms", "--wf-tr-ease": "cubic-bezier(0.165,0.84,0.44,1)"}}>
                    <img src="/assets/automatic-evidence-collection.webp" loading="lazy" sizes="100vw" srcSet="/assets/automatic-evidence-collection-p-500.webp 500w, /assets/automatic-evidence-collection-p-800.webp 800w, /assets/automatic-evidence-collection-p-1080.webp 1080w, /assets/automatic-evidence-collection.webp 1360w" alt="" className="fw-features-img" />
                  </div>
                </section>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
