/** Section 3 of /frameworks/soc2. Generated by the Webflow Cloner agent. */
export function FrameworksSoc2Section3() {
  return (
    <section className="section_v2 tint_60eg overflow_hidden">
      <div className="page-padding">
        <div className="container-small">
          <div className="container-flex vertical center text_center gap_xs">
            <h3 className="h3_v2 color_rg">
              Additional features for
              <span className="no-wrap">
                SOC 2
              </span>
            </h3>
            <div className="text-dek-s max_44rem">
              Mycroft’s Risk Operations Center provides the most integrated features that optimize your security and compliance posture.
            </div>
          </div>
        </div>
        <div className="container-large">
          <div style={{"opacity": "0"}} className="w-layout-grid fw-features-grid">
            <div className="fw-grid-tile">
              <h6 className="h6 color_mint">
                Risk assessment
              </h6>
              <div className="body-text-small color_mint">
                Identify and prioritize security risks
                <br />
              </div>
            </div>
            <div className="fw-grid-tile">
              <h6 className="h6 color_mint">
                Cloud security
              </h6>
              <div className="body-text-small color_mint">
                Protect cloud infrastructure
                <br />
                and services
              </div>
            </div>
            <div className="fw-grid-tile">
              <h6 className="h6 color_mint">
                Risk insight reports
              </h6>
              <div className="body-text-small color_mint">
                Delivers reports prioritizing risks, actioned by Mycroft Agents
              </div>
            </div>
            <div className="fw-grid-tile">
              <h6 className="h6 color_mint">
                App security
              </h6>
              <div className="body-text-small color_mint">
                Secure application code and runtime
              </div>
            </div>
            <div className="fw-grid-tile">
              <h6 className="h6 color_mint">
                Security questionnaires
              </h6>
              <div className="body-text-small color_mint">
                Streamline vendor security assessments
              </div>
            </div>
            <div className="fw-grid-tile">
              <h6 className="h6 color_mint">
                Support and live chat
              </h6>
              <div className="body-text-small color_mint">
                Real-time assistance for security issues
              </div>
            </div>
            <div className="fw-grid-tile">
              <h6 className="h6 color_mint">
                Third party risk management
              </h6>
              <div className="body-text-small color_mint">
                Assess and monitor vendor risk
              </div>
            </div>
            <div className="fw-grid-tile">
              <h6 className="h6 color_mint">
                Security training
              </h6>
              <div className="body-text-small color_mint">
                Interactive employee cybersecurity
                <br />
                education
              </div>
            </div>
            <div id="w-node-_656a9537-9b07-d16e-8808-2341370145db-6fca5e94" className="fw-grid-tile odd_last_child">
              <h6 className="h6 color_mint">
                Policy center
              </h6>
              <div className="body-text-small color_mint">
                Centralized, versioned compliance
                <br />
                policies
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
