import { CtaSection } from "@/app/_shared/CtaSection";
import { SiteNav } from "../../../_shared/SiteNav";
import { SiteFooter } from "../../../_shared/SiteFooter";
import { FrameworksSoc2Section1 } from "./FrameworksSoc2Section1";
import { FrameworksSoc2Section2 } from "./FrameworksSoc2Section2";
import { FrameworksSoc2Section3 } from "./FrameworksSoc2Section3";
import { FrameworksSoc2Section4 } from "./FrameworksSoc2Section4";
import { FrameworksSoc2Section5 } from "./FrameworksSoc2Section5";
import { UnlockFrameworksSection } from "@/app/_shared/UnlockFrameworksSection";

/**
 * Faithful React port of the Webflow https://mycroft.io/frameworks/soc2 page. DOM + classes mirror
 * the original 1:1; global styling is in webflow-shared.css, page CSS
 * in frameworks-soc2.css. Generated by the Webflow Cloner agent.
 */
export function FrameworksSoc2Snapshot() {
  return (
    <div className="page-wrapper u-minh-100vh color_rg">
      <div className="styles__global-embed-code w-embed"></div>
      <SiteNav />
      <main id="main" className="page-content">
        <FrameworksSoc2Section1 />
        <FrameworksSoc2Section2 />
        <FrameworksSoc2Section3 />
        <FrameworksSoc2Section4 />
        <UnlockFrameworksSection
          blurb="Achieve SOC 2 with Mycroft and take advantage of the head start gained in other industry frameworks."
          dials={[
            { href: "/frameworks/iso27001", label: "ISO 27001", lottie: "/lottie/69ebbfa0ca4351761bab59f1_Compliance-Dial_35.json" },
            { href: "/frameworks/hipaa", label: "HIPAA", lottie: "/lottie/69ebcb3ae646a22194c4af4d_Compliance-Dial_65.json" },
            { href: "/frameworks/fedramp", label: "FedRAMP", lottie: "/lottie/69ebcb579b02affc99069e64_Compliance-Dial_55.json" },
          ]}
        />
        <FrameworksSoc2Section5 />
        <CtaSection variant="lamp" />
      </main>
      <SiteFooter />
    </div>
  );
}
