import { CtaSection } from "@/app/_shared/CtaSection";
import { SiteNav } from "../../../_shared/SiteNav";
import { SiteFooter } from "../../../_shared/SiteFooter";
import { FrameworksIso42001Section1 } from "./FrameworksIso42001Section1";
import { FrameworksIso42001Section2 } from "./FrameworksIso42001Section2";
import { FrameworksIso42001Section3 } from "./FrameworksIso42001Section3";
import { FrameworksIso42001Section4 } from "./FrameworksIso42001Section4";
import { FrameworksIso42001Section5 } from "./FrameworksIso42001Section5";
import { UnlockFrameworksSection } from "@/app/_shared/UnlockFrameworksSection";

/**
 * Faithful React port of the Webflow https://mycroft.io/frameworks/iso42001 page. DOM + classes mirror
 * the original 1:1; global styling is in webflow-shared.css, page CSS
 * in frameworks-iso42001.css. Generated by the Webflow Cloner agent.
 */
export function FrameworksIso42001Snapshot() {
  return (
    <div className="page-wrapper u-minh-100vh color_rg">
      <div className="styles__global-embed-code w-embed"></div>
      <SiteNav />
      <main id="main" className="page-content">
        <FrameworksIso42001Section1 />
        <FrameworksIso42001Section2 />
        <FrameworksIso42001Section3 />
        <FrameworksIso42001Section4 />
        <UnlockFrameworksSection
          blurb={
            <>
              Achieve{" "}
              <span className="whitespace-nowrap">ISO 42001</span>{" "}
              compliance with Mycroft and take advantage of the head start gained in other industry frameworks.
            </>
          }
          dials={[
            { href: "/frameworks/iso27001", label: "ISO 27001", lottie: "/lottie/6a024deb018a84831eff1a49_Compliance-Dial_25.json" },
            { href: "/frameworks/gdpr", label: "GDPR", lottie: "/lottie/6a024deb9a47cda7c321c5a3_Compliance-Dial_45.json" },
            { href: "/frameworks/soc2", label: "SOC 2", lottie: "/lottie/6a024deb4cd221655fea0562_Compliance-Dial_70.json" },
          ]}
        />
        <FrameworksIso42001Section5 />
        <CtaSection variant="fireplace" />
      </main>
      <SiteFooter />
    </div>
  );
}
