/** Section 5 of /frameworks/iso42001. Generated by the Webflow Cloner agent. */
export function FrameworksIso42001Section5() {
  return (
    <section className="section_v2 color_smoke">
      <div className="page-padding">
        <div className="container-medium">
          <div className="padding-top medium">
            <div className="padding-btm large">
              <img src="/assets/faq-notchlabel-desktop.svg" loading="lazy" alt="" className="faq-notch-desktop" />
              <img src="/assets/faq-notchlabel-mobile.svg" loading="lazy" alt="" className="faq-notch-mobile" />
              <div className="container-flex faq_container">
                <div className="faq-hed-flex">
                  <h3 className="h3_v2 color_white">
                    Frequently asked questions
                  </h3>
                  <div className="text-dek-l text_40eg">
                    Answers that help customers with
                    <span className="no-wrap">
                      ISO 42001
                    </span>
                    compliance
                  </div>
                </div>
                <div className="faq-item first_child">
                  <div className="custom-dropdown">
                    <div className="top-row">
                      <div className="question-container">
                        <div className="h5 color_white">
                          What is
                          <span className="no-wrap">
                            ISO 42001?
                          </span>
                        </div>
                      </div>
                      <div className="state-toggle">
                        <div className="plus-container" style={{"width": "24px", "height": "24px"}}>
                          <div className="plus _75_mint"></div>
                        </div>
                        <div className="minus _75_mint"></div>
                      </div>
                    </div>
                  </div>
                  <div className="answer-container">
                    <div className="body-text-medium color_40eg faq_answer" style={{"height": "0px"}}>
                      <span className="no-wrap">
                        ISO 42001
                      </span>
                      is a framework for managing artificial intelligence systems responsibly, focusing on governance, risk, and transparency.
                    </div>
                  </div>
                  <div className="faq-spacer-expand no_opacity" style={{"height": "0px"}}></div>
                  <div className="faq-item-btm-hr"></div>
                </div>
                <div className="faq-item">
                  <div className="custom-dropdown">
                    <div className="top-row">
                      <div className="question-container">
                        <div className="h5 color_white">
                          Who needs
                          <span className="no-wrap">
                            ISO 42001?
                          </span>
                        </div>
                      </div>
                      <div className="state-toggle">
                        <div className="plus-container" style={{"width": "24px", "height": "24px"}}>
                          <div className="plus _75_mint"></div>
                        </div>
                        <div className="minus _75_mint"></div>
                      </div>
                    </div>
                  </div>
                  <div className="answer-container">
                    <div className="body-text-medium color_40eg faq_answer" style={{"height": "0px"}}>
                      Organizations developing or using AI systems that need to demonstrate responsible AI practices and prepare for emerging regulations.
                    </div>
                  </div>
                  <div className="faq-spacer-expand no_opacity" style={{"height": "0px"}}></div>
                  <div className="faq-item-btm-hr"></div>
                </div>
                <div className="faq-item">
                  <div className="custom-dropdown">
                    <div className="top-row">
                      <div className="question-container">
                        <div className="h5 color_white">
                          What does
                          <span className="no-wrap">
                            ISO 42001
                          </span>
                          cover?
                        </div>
                      </div>
                      <div className="state-toggle">
                        <div className="plus-container" style={{"width": "24px", "height": "24px"}}>
                          <div className="plus _75_mint"></div>
                        </div>
                        <div className="minus _75_mint"></div>
                      </div>
                    </div>
                  </div>
                  <div className="answer-container">
                    <div className="body-text-medium color_40eg faq_answer" style={{"height": "0px"}}>
                      It covers AI risk management, model governance, data usage, and oversight of AI systems.
                    </div>
                  </div>
                  <div className="faq-spacer-expand no_opacity" style={{"height": "0px"}}></div>
                  <div className="faq-item-btm-hr"></div>
                </div>
                <div className="faq-item">
                  <div className="custom-dropdown">
                    <div className="top-row">
                      <div className="question-container">
                        <div className="h5 color_white">
                          Is
                          <span className="no-wrap">
                            ISO 42001
                          </span>
                          required?
                        </div>
                      </div>
                      <div className="state-toggle">
                        <div className="plus-container" style={{"width": "24px", "height": "24px"}}>
                          <div className="plus _75_mint"></div>
                        </div>
                        <div className="minus _75_mint"></div>
                      </div>
                    </div>
                  </div>
                  <div className="answer-container">
                    <div className="body-text-medium color_40eg faq_answer" style={{"height": "0px"}}>
                      While not yet mandatory, it is becoming increasingly important as governments introduce AI regulations.
                    </div>
                  </div>
                  <div className="faq-spacer-expand no_opacity" style={{"height": "0px"}}></div>
                  <div className="faq-item-btm-hr"></div>
                </div>
                <div className="faq-item">
                  <div className="custom-dropdown">
                    <div className="top-row">
                      <div className="question-container">
                        <div className="h5 color_white">
                          How does Mycroft help with
                          <span className="no-wrap">
                            ISO 42001?
                          </span>
                        </div>
                      </div>
                      <div className="state-toggle">
                        <div className="plus-container" style={{"width": "24px", "height": "24px"}}>
                          <div className="plus _75_mint"></div>
                        </div>
                        <div className="minus _75_mint"></div>
                      </div>
                    </div>
                  </div>
                  <div className="answer-container">
                    <div className="body-text-medium color_40eg faq_answer" style={{"height": "0px"}}>
                      Mycroft helps operationalize AI governance by managing policies, controls, and evidence so your organization can demonstrate responsible AI practices.
                    </div>
                  </div>
                  <div className="faq-spacer-expand no_opacity" style={{"height": "0px"}}></div>
                  <div className="faq-item-btm-hr last_child"></div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
