import { ArrowTextLink } from "@/app/_shared/ArrowTextLink";

/** Section 2 of /frameworks/iso42001. Generated by the Webflow Cloner agent. */
export function FrameworksIso42001Section2() {
  return (
    <section id="fw-features" className="section_v2 tint_60eg overflow_hidden">
      <div className="page-padding">
        <div className="container-small fw_features_hed">
          <div className="padding-top large">
            <div className="container-flex vertical">
              <div className="eyebrow-label-small product">
                <div className="eyebrow-small color_rg">
                  Features
                </div>
              </div>
              <h2 className="h2_v2 color_rg text_center">
                Mycroft’s AI platform solutions for
                <span className="no-wrap">
                  ISO 42001
                </span>
              </h2>
              <div className="padding-top xxs">
                <div className="text-dek-l text_center">
                  A unified platform designed to operationalize AI governance requirements without adding internal workload.
                </div>
              </div>
            </div>
          </div>
        </div>
        <div className="container-large">
          <div className="padding-top medium">
            <div className="padding-btm large">
              <div className="product-container">
                <section id="app-security" className="product-feature">
                  <div className="product-text wf-reveal" style={{"willChange": "opacity, transform", "opacity": "0", "transform": "translate3d(-100px, 0px, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg)", "transformStyle": "preserve-3d", "--wf-op-dur": "1000ms", "--wf-op-delay": "0ms", "--wf-op-ease": "cubic-bezier(0.165,0.84,0.44,1)", "--wf-tr-dur": "1000ms", "--wf-tr-delay": "0ms", "--wf-tr-ease": "cubic-bezier(0.165,0.84,0.44,1)"}}>
                    <h4 className="h4_v2 color_rg">
                      App security
                    </h4>
                    <div className="body-text-medium">
                      Improve application security by identifying vulnerabilities, monitoring configurations, and supporting secure development practices across your software environment.
                    </div>
                    <ArrowTextLink href="/demo">
                      Book a demo
                    </ArrowTextLink>
                  </div>
                  <div className="product-feature-img wf-reveal" style={{"willChange": "opacity, transform", "opacity": "0", "transform": "translate3d(100px, 0px, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg)", "transformStyle": "preserve-3d", "--wf-op-dur": "1000ms", "--wf-op-delay": "0ms", "--wf-op-ease": "cubic-bezier(0.165,0.84,0.44,1)", "--wf-tr-dur": "1000ms", "--wf-tr-delay": "0ms", "--wf-tr-ease": "cubic-bezier(0.165,0.84,0.44,1)"}}>
                    <img src="/assets/app-security.webp" loading="lazy" width="680" sizes="(max-width: 479px) 100vw, 680px" alt="" srcSet="/assets/app-security-p-500.webp 500w, /assets/app-security-p-800.webp 800w, /assets/app-security-p-1080.webp 1080w, /assets/app-security.webp 1360w" className="fw-features-img" />
                  </div>
                </section>
                <section id="threat-management" className="product-feature even-child">
                  <div className="product-feature-img img-left wf-reveal" style={{"willChange": "opacity, transform", "opacity": "0", "transform": "translate3d(-100px, 0px, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg)", "transformStyle": "preserve-3d", "--wf-op-dur": "1000ms", "--wf-op-delay": "0ms", "--wf-op-ease": "cubic-bezier(0.165,0.84,0.44,1)", "--wf-tr-dur": "1000ms", "--wf-tr-delay": "0ms", "--wf-tr-ease": "cubic-bezier(0.165,0.84,0.44,1)"}}>
                    <img src="/assets/custom-controls.webp" loading="lazy" width="680" sizes="(max-width: 479px) 100vw, 680px" alt="" srcSet="/assets/custom-controls-p-500.webp 500w, /assets/custom-controls-p-800.webp 800w, /assets/custom-controls-p-1080.webp 1080w, /assets/custom-controls.webp 1360w" className="fw-features-img" />
                  </div>
                  <div className="product-text text-right wf-reveal" style={{"willChange": "opacity, transform", "opacity": "0", "transform": "translate3d(100px, 0px, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg)", "transformStyle": "preserve-3d", "--wf-op-dur": "1000ms", "--wf-op-delay": "0ms", "--wf-op-ease": "cubic-bezier(0.165,0.84,0.44,1)", "--wf-tr-dur": "1000ms", "--wf-tr-delay": "0ms", "--wf-tr-ease": "cubic-bezier(0.165,0.84,0.44,1)"}}>
                    <h4 className="h4_v2 color_rg">
                      Custom controls
                    </h4>
                    <div className="body-text-medium">
                      Create and manage custom security controls tailored to your organization’s operational, regulatory, and customer requirements while simplifying compliance mapping across frameworks.
                    </div>
                    <ArrowTextLink href="/demo">
                      Book a demo
                    </ArrowTextLink>
                  </div>
                </section>
                <section id="agentic-ai" className="product-feature last-child">
                  <div className="product-text wf-reveal" style={{"willChange": "opacity, transform", "opacity": "0", "transform": "translate3d(-100px, 0px, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg)", "transformStyle": "preserve-3d", "--wf-op-dur": "1000ms", "--wf-op-delay": "0ms", "--wf-op-ease": "cubic-bezier(0.165,0.84,0.44,1)", "--wf-tr-dur": "1000ms", "--wf-tr-delay": "0ms", "--wf-tr-ease": "cubic-bezier(0.165,0.84,0.44,1)"}}>
                    <h4 className="h4_v2 color_rg">
                      Policy center
                    </h4>
                    <div className="body-text-medium">
                      Centralize policies, approvals, procedures, and compliance documentation in one secure location with version control and employee acknowledgment tracking.
                    </div>
                    <ArrowTextLink href="/demo">
                      Book a demo
                    </ArrowTextLink>
                  </div>
                  <div className="product-feature-img wf-reveal" style={{"willChange": "opacity, transform", "opacity": "0", "transform": "translate3d(100px, 0px, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg)", "transformStyle": "preserve-3d", "--wf-op-dur": "1000ms", "--wf-op-delay": "0ms", "--wf-op-ease": "cubic-bezier(0.165,0.84,0.44,1)", "--wf-tr-dur": "1000ms", "--wf-tr-delay": "0ms", "--wf-tr-ease": "cubic-bezier(0.165,0.84,0.44,1)"}}>
                    <img src="/assets/policy-center.webp" loading="lazy" sizes="(max-width: 1360px) 100vw, 1360px" srcSet="/assets/policy-center-p-500.webp 500w, /assets/policy-center-p-800.webp 800w, /assets/policy-center-p-1080.webp 1080w, /assets/policy-center.webp 1360w" alt="" className="fw-features-img" />
                  </div>
                </section>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
