import type { Metadata } from "next";
import "./pricing.css";
import { PricingSnapshot } from "./_snapshot/PricingSnapshot";
import { WebflowInteractions } from "../_shared/WebflowInteractions";

export const metadata: Metadata = {
  title: "Mycroft Pricing | Find the right pricing package for your security program",
  description: "Mycroft offers pricing packages to help you achieve and maintain your security and compliance program with enterprise level standards across the board.",
  openGraph: {
    title: "Mycroft Pricing | Find the right pricing package for your security program",
    description: "Mycroft offers pricing packages to help you achieve and maintain your security and compliance program with enterprise level standards across the board.",
    type: "website",
    images: ["/assets/mycroft-meta-img-pricing.webp"],
  },
  twitter: {
    card: "summary_large_image",
    title: "Mycroft Pricing | Find the right pricing package for your security program",
    description: "Mycroft offers pricing packages to help you achieve and maintain your security and compliance program with enterprise level standards across the board.",
    images: ["/assets/mycroft-meta-img-pricing.webp"],
  },
};

/**
 * /pricing: a faithful React rebuild of the Webflow page.
 * Generated by the Webflow Cloner agent from https://www.mycroft.io/pricing.
 */
export default function PricingPage() {
  return (
    <>
      <PricingSnapshot />
      <WebflowInteractions />
    </>
  );
}
