import { TrustedBySection } from "@/app/_shared/LogoMarquee";
import { SiteNav } from "../../_shared/SiteNav";
import { SiteFooter } from "../../_shared/SiteFooter";
import { ProductSection1 } from "./ProductSection1";
import { ProductSection2 } from "./ProductSection2";
import { ProductSection4 } from "./ProductSection4";
import { ProductSection5 } from "./ProductSection5";

/**
 * Faithful React port of the Webflow https://www.mycroft.io/product page. DOM + classes mirror
 * the original 1:1; global styling is in webflow-shared.css, page CSS
 * in product.css. Generated by the Webflow Cloner agent.
 */
export function ProductSnapshot() {
  return (
    <div className="page-wrapper u-minh-100vh">
      <div className="styles__global-embed-code w-embed"></div>
      <SiteNav />
      <main id="main" className="page-content">
        <ProductSection1 />
        <ProductSection2 />
        <TrustedBySection btm="earlgrey40" />
        <ProductSection4 />
        <ProductSection5 />
      </main>
      <SiteFooter />
    </div>
  );
}
