import { SiteNav21 } from "../../_shared/SiteNav21";
import { SiteFooter } from "../../_shared/SiteFooter";
import { DemoSection1 } from "./DemoSection1";
import { DemoSection2 } from "./DemoSection2";

/**
 * Faithful React port of the Webflow https://www.mycroft.io/demo page. DOM + classes mirror
 * the original 1:1; global styling is in webflow-shared.css, page CSS
 * in demo.css. Generated by the Webflow Cloner agent.
 */
export function DemoSnapshot() {
  return (
    <div className="page-wrapper u-minh-100vh">
      <div className="styles__global-embed-code w-embed"></div>
      <SiteNav21 />
      <main id="main" className="page-content">
        <DemoSection1 />
        <DemoSection2 />
      </main>
      <SiteFooter />
    </div>
  );
}
