/** Section 2 of /demo. Generated by the Webflow Cloner agent. */
export function DemoSection2() {
  return (
    <section id="compliance" className="section_v2">
      <div className="overlap-top">
        <div className="overlap-block"></div>
        <div className="container-large">
          <div className="overlap-block top_block"></div>
        </div>
        <div className="overlap-block transparent"></div>
      </div>
      <div className="section-overlap stroke_btm">
        <div className="color-rg">
          <div className="page-padding">
            <div className="container-large">
              <div className="padding-top large">
                <div className="padding-btm large">
                  <div className="container-flex vertical">
                    <div className="compliance-col-left">
                      <div className="eyebrow-label-small compliance-margins">
                        <div className="eyebrow-small color_mint">
                          Compliance
                        </div>
                      </div>
                    </div>
                    <div className="padding-btm xsmall">
                      <div className="container-flex center_align_y-axis horizontal_tablet left_align_tablet">
                        <div className="compliance-col-left">
                          <div className="container-flex vertical mobile_portrait_center">
                            <h4 className="h4_v2 color_white">
                              Real enterprise security, compliance next.
                            </h4>
                            <div className="padding-top xxxs">
                              <div className="body-text-medium text_40earlgrey">
                                We help you navigate SOC 2, PIPEDA, GDPR, HIPAA, CMMC, FedRAMP, FedRAMP 20X and other frameworks that we stay on top of.
                              </div>
                            </div>
                          </div>
                        </div>
                        <div className="compliance-badges-container">
                          <div className="badge-grid">
                            <div id="w-node-c5775c98-62c7-c779-c723-9daca99683eb-a99683d7" className="badge-row">
                              <img loading="lazy" src="/assets/mycroft-soc2-badge.svg" alt="" className="compliance-badge-img" />
                              <img loading="lazy" src="/assets/mycroft-hipaa-badge.svg" alt="" className="compliance-badge-img" />
                            </div>
                            <div id="w-node-c5775c98-62c7-c779-c723-9daca99683ee-a99683d7" className="badge-row">
                              <img loading="lazy" src="/assets/mycroft-gdpr-badge.svg" alt="" className="compliance-badge-img" />
                              <img loading="lazy" src="/assets/mycroft-iso-badge.svg" alt="" className="compliance-badge-img" />
                            </div>
                            <img loading="lazy" src="/assets/mycroft-euai-badge.svg" alt="" className="compliance-badge-img last-child" />
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
