import { TrustedBySection } from "@/app/_shared/LogoMarquee";
import { CtaSection } from "@/app/_shared/CtaSection";
import { ProductDeviceManagementCollection1 } from "./ProductDeviceManagementCollection1";
import { productDeviceManagementCollection1Data } from "./ProductDeviceManagementCollection1.data";
import { ButtonLarge } from "@/app/_shared/ButtonLarge";
import { SiteNav } from "../../../_shared/SiteNav";
import { SiteFooter } from "../../../_shared/SiteFooter";
import { ProductDeviceManagementSection1 } from "./ProductDeviceManagementSection1";
import { ProductDeviceManagementSection3 } from "./ProductDeviceManagementSection3";
import { ProductDeviceManagementSection4 } from "./ProductDeviceManagementSection4";
import { ProductDeviceManagementSection5 } from "./ProductDeviceManagementSection5";
import { ScrollFeatureSlider, type ScrollFeatureSlide } from "@/app/_shared/ScrollFeatureSlider";

const deviceManagementSlides: ScrollFeatureSlide[] = [
  {
    heading: "Device dashboard",
    body: "Mycroft's platform feature offers a comprehensive dashboard with insights into each device, displaying specifications, status, and compliance. It conducts regular compliance checks to ensure all devices meet security standards.",
    image: {
      src: "/assets/product-devicedashboard.webp",
      srcSet:
        "/assets/product-devicedashboard-p-500.webp 500w, /assets/product-devicedashboard-p-800.webp 800w, /assets/product-devicedashboard-p-1080.webp 1080w, /assets/product-devicedashboard.webp 1352w",
      sizes: "(max-width: 767px) 100vw, 676px",
      width: 676,
    },
  },
  {
    heading: "Remote device locking",
    body: "Our platform lets you remotely lock a device in case of theft or security incidents, safeguarding sensitive data from unauthorized access. Quick remote lock actions help reduce data breach risks, protecting your company's information.",
    image: {
      src: "/assets/product-devicelocking.webp",
      srcSet:
        "/assets/product-devicelocking-p-500.webp 500w, /assets/product-devicelocking-p-800.webp 800w, /assets/product-devicelocking-p-1080.webp 1080w, /assets/product-devicelocking.webp 1352w",
      sizes: "(max-width: 767px) 100vw, 676px",
      width: 676,
    },
  },
  {
    heading: "Remote device wipe",
    body: "Mycroft's platform feature allows users to  erase sensitive data from lost or stolen devices, ensuring data protection and regulatory compliance, while minimizing data breach risks. This tool empowers businesses to maintain control over mobile assets and enhance overall security.",
    image: {
      src: "/assets/product-devicewipe.webp",
      srcSet:
        "/assets/product-devicewipe-p-500.webp 500w, /assets/product-devicewipe-p-800.webp 800w, /assets/product-devicewipe-p-1080.webp 1080w, /assets/product-devicewipe.webp 1352w",
      sizes: "(max-width: 767px) 100vw, 676px",
      width: 676,
    },
  },
];

/**
 * Faithful React port of the Webflow https://mycroft.io/product/device-management page. DOM + classes mirror
 * the original 1:1; global styling is in webflow-shared.css, page CSS
 * in product-device-management.css. Generated by the Webflow Cloner agent.
 */
export function ProductDeviceManagementSnapshot() {
  return (
    <div className="page-wrapper u-minh-100vh color_rg">
      <div className="styles__global-embed-code w-embed"></div>
      <SiteNav />
      <main id="main" className="page-content">
        <ProductDeviceManagementSection1 />
        <TrustedBySection btm="rg" />
        <ProductDeviceManagementSection3 />
        <div className="scroll-container-outer">
          <div className="scroll-container-inner">
            <section id="product-features" className="section_v2 split_background rg_40earlgrey">
              <div className="pr-(--sizing--rem--2rem) pl-(--sizing--rem--2rem) ml-auto mr-auto relative max-portrait:pr-(--sizing--rem--1-25rem) max-portrait:pl-(--sizing--rem--1-25rem)">
                <div className="container-xl">
                  <div className="w-full pb-(--sizing--rem--4-5rem) max-tablet:pb-(--sizing--rem--3-5rem) max-landscape:pb-(--sizing--rem--2-5rem) max-portrait:pb-(--sizing--rem--1-5rem)">
                    <div className="scroll-slider-outer">
                      <ScrollFeatureSlider id="audit-compliance" slides={deviceManagementSlides}>
                        <ButtonLarge href="/demo" velvet shine>
                          Book a demo
                        </ButtonLarge>
                      </ScrollFeatureSlider>
                      <div className="btm-tab">
                        <div className="shape-triangle _75_eg flipped mirrored smaller_mobile w-embed">
                          <svg version="1.1" baseProfile="basic" id="Triangle" xmlns="http://www.w3.org/2000/svg" xmlnsXlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 34 38" xmlSpace="preserve">
                            <path fill="currentColor" d="M0,0l34,38H0V0z"></path>
                          </svg>
                        </div>
                        <div className="tab-filler"></div>
                        <div className="shape-triangle _75_eg flipped smaller_mobile w-embed">
                          <svg version="1.1" baseProfile="basic" id="Triangle" xmlns="http://www.w3.org/2000/svg" xmlnsXlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 34 38" xmlSpace="preserve">
                            <path fill="currentColor" d="M0,0l34,38H0V0z"></path>
                          </svg>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </section>
            <section id="platform-features" className="section_v2 tint_40eg">
              <div className="pr-(--sizing--rem--2rem) pl-(--sizing--rem--2rem) ml-auto mr-auto relative max-portrait:pr-(--sizing--rem--1-25rem) max-portrait:pl-(--sizing--rem--1-25rem)">
                <div className="w-full max-w-300 ml-auto mr-auto">
                  <div className="w-full pt-(--sizing--rem--2-5rem) max-tablet:pt-(--sizing--rem--2rem) max-landscape:pt-(--sizing--rem--1-5rem) max-portrait:pt-(--sizing--rem--1rem)">
                    <div className="w-full pb-(--sizing--rem--6rem) max-tablet:pb-(--sizing--rem--5rem) max-landscape:pb-(--sizing--rem--3-5rem) max-portrait:pb-(--sizing--rem--2-5rem)">
                      <div className="container-flex vertical center">
                        <div className="eyebrow-label-small product">
                          <div className="eyebrow-small color_rg">
                            Platform features
                          </div>
                        </div>
                        <div className="w-full pb-(--sizing--rem--2-5rem) max-tablet:pb-(--sizing--rem--2rem) max-landscape:pb-(--sizing--rem--1-5rem) max-portrait:pb-(--sizing--rem--1rem)">
                          <div className="container-flex vertical center">
                            <div className="w-full max-w-200 ml-auto mr-auto max-tablet:w-[80%] max-tablet:max-w-none max-landscape:w-[92%] max-portrait:w-full">
                              <div className="narrow-text-container">
                                <div className="container-flex vertical center">
                                  <h4 className="h4_v2 color_rg">
                                    Secure your data with our comprehensive mobile device management solution
                                  </h4>
                                  <div className="w-full pt-(--sizing--rem--0-75rem) max-tablet:pt-[.65rem] max-portrait:pt-[.4rem]">
                                    <div className="text-dek-m">
                                      Our platform empowers organizations to safeguard sensitive information through strong encryption, remote wipe capabilities, and stringent policy enforcement
                                    </div>
                                  </div>
                                </div>
                              </div>
                            </div>
                            <div className="platform-grid">
                              <div className="platform-item">
                                <img src="/assets/feature-dataencryption-v1.webp" loading="lazy" width="564" sizes="(max-width: 767px) 100vw, 564px" alt="" srcSet="/assets/feature-dataencryption-v1-p-500.webp 500w, /assets/feature-dataencryption-v1-p-800.webp 800w, /assets/feature-dataencryption-v1-p-1080.webp 1080w, /assets/feature-dataencryption-v1.webp 1128w" className="platform-img" />
                                <div className="platform-text">
                                  <h6 className="h6 larger_mobile">
                                    Data Encryption
                                  </h6>
                                  <div className="body-text-small">
                                    Ensures all sensitive data on devices are encrypted, protecting them from unauthorized access, even in the event of theft or loss.
                                  </div>
                                </div>
                              </div>
                              <div className="platform-item">
                                <img src="/assets/features-img2.webp" loading="lazy" width="562.5" sizes="(max-width: 767px) 100vw, 563px" alt="" srcSet="/assets/features-img2-p-500.webp 500w, /assets/features-img2-p-800.webp 800w, /assets/features-img2-p-1080.webp 1080w, /assets/features-img2.webp 1125w" className="platform-img" />
                                <div className="platform-text">
                                  <h6 className="h6 larger_mobile">
                                    Monitoring
                                  </h6>
                                  <div className="body-text-small">
                                    Provides real-time alerts to identify and fix issues quickly, keeping you on track.
                                  </div>
                                </div>
                              </div>
                              <div className="platform-item">
                                <img src="/assets/feature-policyenforcement-v1.webp" loading="lazy" width="564" sizes="(max-width: 767px) 100vw, 564px" alt="" srcSet="/assets/feature-policyenforcement-v1-p-500.webp 500w, /assets/feature-policyenforcement-v1-p-800.webp 800w, /assets/feature-policyenforcement-v1-p-1080.webp 1080w, /assets/feature-policyenforcement-v1.webp 1128w" className="platform-img" />
                                <div className="platform-text">
                                  <h6 className="h6 larger_mobile">
                                    Policy enforcement
                                  </h6>
                                  <div className="body-text-small">
                                    Mitigate risks associated with human error, unauthorized access, and potential data breaches.
                                  </div>
                                </div>
                              </div>
                            </div>
                            <ButtonLarge href="/demo" shine>
                              Book a demo
                            </ButtonLarge>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </section>
          </div>
        </div>
        <ProductDeviceManagementSection4 />
        <div className="negative-margin-wrapper reduce_top">
          <section id="Features" className="section_v2 color_smoke">
            <div className="pr-(--sizing--rem--2rem) pl-(--sizing--rem--2rem) ml-auto mr-auto relative max-portrait:pr-(--sizing--rem--1-25rem) max-portrait:pl-(--sizing--rem--1-25rem)">
              <div className="w-full pt-(--sizing--rem--8-5rem) max-tablet:pt-(--sizing--rem--6-5rem) max-landscape:pt-(--sizing--rem--4-5rem) max-portrait:pt-(--sizing--rem--3-5rem)">
                <div className="w-full max-w-240 ml-auto mr-auto max-tablet:w-[90%] max-tablet:max-w-none max-landscape:w-full max-portrait:w-full">
                  <div className="w-full max-w-184 ml-auto mr-auto max-tablet:w-[80%] max-tablet:max-w-none max-landscape:w-[92%] max-portrait:w-full">
                    <div className="container-flex vertical">
                      <h3 className="h3_v2 color_white text_center">
                        Read the latest insights from our experts
                      </h3>
                      <div className="w-full pt-(--sizing--rem--0-75rem) max-tablet:pt-[.65rem] max-portrait:pt-[.4rem]">
                        <div className="text-dek-s text_40_grey text_center">
                          Stay secure with expert, data-driven resources to strengthen your security knowledge and ensure compliance confidence.
                        </div>
                      </div>
                    </div>
                  </div>
                  <div className="w-full pt-(--sizing--rem--2-5rem) max-tablet:pt-(--sizing--rem--2rem) max-landscape:pt-(--sizing--rem--1-5rem) max-portrait:pt-(--sizing--rem--1rem)">
                    <div className="w-full pb-(--sizing--rem--6rem) max-tablet:pb-(--sizing--rem--5rem) max-landscape:pb-(--sizing--rem--3-5rem) max-portrait:pb-(--sizing--rem--2-5rem)">
                      <div className="container-flex space-between _3up_blog">
                        <div className="_3up-blog-wrapper w-dyn-list">
                          <div role="list" className="_3up-blog-grid w-dyn-items">
                            {productDeviceManagementCollection1Data.map((item, i) => (
                              <ProductDeviceManagementCollection1 item={item} key={i} />
                            ))}
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </section>
        </div>
        <ProductDeviceManagementSection5 />
        <CtaSection variant="fireplace" />
      </main>
      <SiteFooter />
    </div>
  );
}
