import { ProductDeviceManagementCollection1 } from "./ProductDeviceManagementCollection1";
import { productDeviceManagementCollection1Data } from "./ProductDeviceManagementCollection1.data";
import Link from "next/link";
import { SiteNav } from "../../../_shared/SiteNav";
import { SiteFooter } from "../../../_shared/SiteFooter";
import { ProductDeviceManagementSection1 } from "./ProductDeviceManagementSection1";
import { ProductDeviceManagementSection2 } from "./ProductDeviceManagementSection2";
import { ProductDeviceManagementSection3 } from "./ProductDeviceManagementSection3";
import { ProductDeviceManagementSection4 } from "./ProductDeviceManagementSection4";
import { ProductDeviceManagementSection5 } from "./ProductDeviceManagementSection5";
import { ProductDeviceManagementSection6 } from "./ProductDeviceManagementSection6";

/**
 * Faithful React port of the Webflow https://mycroft.io/product/device-management page. DOM + classes mirror
 * the original 1:1; global styling is in webflow-shared.css, page CSS
 * in product-device-management.css. Generated by the Webflow Cloner agent.
 */
export function ProductDeviceManagementSnapshot() {
  return (
    <div className="page-wrapper u-minh-100vh color_rg">
      <div className="styles__global-embed-code w-embed"></div>
      <SiteNav />
      <main id="main" className="page-content">
        <ProductDeviceManagementSection1 />
        <ProductDeviceManagementSection2 />
        <ProductDeviceManagementSection3 />
        <div className="scroll-container-outer">
          <div className="scroll-container-inner">
            <section id="product-features" className="section_v2 split_background rg_40earlgrey">
              <div className="page-padding">
                <div className="container-xl">
                  <div className="padding-btm medium">
                    <div className="scroll-slider-outer">
                      <section id="audit-compliance" className="scroll-slider-inner">
                        <div className="enumeration-container">
                          <div className="enumeration-counter">
                            <div className="enumeration-absolute">
                              <div className="body-text-medium _75_rg enumeration1" style={{"willChange": "opacity", "opacity": "1"}}>
                                1
                                <br />
                              </div>
                            </div>
                            <div className="enumeration-absolute">
                              <div className="body-text-medium _75_rg enumeration2" style={{"willChange": "opacity", "opacity": "0"}}>
                                2
                                <br />
                              </div>
                            </div>
                            <div className="enumeration-absolute">
                              <div className="body-text-medium _75_rg enumeration3" style={{"willChange": "opacity", "opacity": "0"}}>
                                3
                              </div>
                            </div>
                          </div>
                          <div className="body-text-medium _75_rg">
                            /
                          </div>
                          <div className="body-text-medium _75_rg">
                            3
                          </div>
                        </div>
                        <div className="features-row static" style={{"willChange": "opacity", "opacity": "0"}}>
                          <div className="features-text">
                            <h4 className="h4_v2 color_rg">
                              Remote device wipe
                            </h4>
                            <div className="body-text-large smaller_tablet">
                              Mycroft's platform feature allows users to  erase sensitive data from lost or stolen devices, ensuring data protection and regulatory compliance, while minimizing data breach risks. This tool empowers businesses to maintain control over mobile assets and enhance overall security.
                            </div>
                          </div>
                          <div className="features-img-container">
                            <img src="/assets/product-frameworks.webp" loading="lazy" width="676" sizes="(max-width: 767px) 100vw, 676px" alt="" srcSet="/assets/product-frameworks-p-500.webp 500w, /assets/product-frameworks-p-800.webp 800w, /assets/product-frameworks-p-1080.webp 1080w, /assets/product-frameworks.webp 1352w" className="features-img" />
                          </div>
                        </div>
                        <div className="features-row absolute slide1">
                          <div className="features-text slide1" style={{"willChange": "transform, opacity", "transform": "translate3d(0px, 0px, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg)", "transformStyle": "preserve-3d", "opacity": "1"}}>
                            <h4 className="h4_v2 color_rg">
                              Device dashboard
                            </h4>
                            <div className="body-text-large smaller_tablet">
                              Mycroft's platform feature offers a comprehensive dashboard with insights into each device, displaying specifications, status, and compliance. It conducts regular compliance checks to ensure all devices meet security standards.
                            </div>
                          </div>
                          <div className="features-img-container slide1" style={{"willChange": "transform, opacity", "transform": "translate3d(0px, 0px, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg)", "transformStyle": "preserve-3d", "opacity": "1"}}>
                            <img src="/assets/product-devicedashboard.webp" loading="lazy" width="676" sizes="(max-width: 767px) 100vw, 676px" alt="" srcSet="/assets/product-devicedashboard-p-500.webp 500w, /assets/product-devicedashboard-p-800.webp 800w, /assets/product-devicedashboard-p-1080.webp 1080w, /assets/product-devicedashboard.webp 1352w" className="features-img" />
                          </div>
                        </div>
                        <div className="features-row absolute slide2">
                          <div className="features-text slide2 wf-reveal" style={{"willChange": "transform, opacity", "transform": "translate3d(0px, 40px, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg)", "transformStyle": "preserve-3d", "opacity": "0", "--wf-op-dur": "1000ms", "--wf-op-delay": "0ms", "--wf-op-ease": "cubic-bezier(0.165,0.84,0.44,1)", "--wf-tr-dur": "1000ms", "--wf-tr-delay": "0ms", "--wf-tr-ease": "cubic-bezier(0.165,0.84,0.44,1)"}}>
                            <h4 className="h4_v2 color_rg">
                              Remote device locking
                            </h4>
                            <div className="body-text-large smaller_tablet">
                              Our platform lets you remotely lock a device in case of theft or security incidents, safeguarding sensitive data from unauthorized access. Quick remote lock actions help reduce data breach risks, protecting your company's information.
                            </div>
                          </div>
                          <div className="features-img-container slide2 wf-reveal" style={{"willChange": "transform, opacity", "transform": "translate3d(-40px, 0px, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg)", "transformStyle": "preserve-3d", "opacity": "0", "--wf-op-dur": "1000ms", "--wf-op-delay": "0ms", "--wf-op-ease": "cubic-bezier(0.165,0.84,0.44,1)", "--wf-tr-dur": "1000ms", "--wf-tr-delay": "0ms", "--wf-tr-ease": "cubic-bezier(0.165,0.84,0.44,1)"}}>
                            <img src="/assets/product-devicelocking.webp" loading="lazy" width="676" sizes="(max-width: 767px) 100vw, 676px" alt="" srcSet="/assets/product-devicelocking-p-500.webp 500w, /assets/product-devicelocking-p-800.webp 800w, /assets/product-devicelocking-p-1080.webp 1080w, /assets/product-devicelocking.webp 1352w" className="features-img" />
                          </div>
                        </div>
                        <div className="features-row absolute slide3">
                          <div className="features-text slide3 wf-reveal" style={{"willChange": "transform, opacity", "transform": "translate3d(0px, 40px, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg)", "transformStyle": "preserve-3d", "opacity": "0", "--wf-op-dur": "1000ms", "--wf-op-delay": "0ms", "--wf-op-ease": "cubic-bezier(0.165,0.84,0.44,1)", "--wf-tr-dur": "1000ms", "--wf-tr-delay": "0ms", "--wf-tr-ease": "cubic-bezier(0.165,0.84,0.44,1)"}}>
                            <h4 className="h4_v2 color_rg">
                              Remote device wipe
                            </h4>
                            <div className="body-text-large smaller_tablet">
                              Mycroft's platform feature allows users to  erase sensitive data from lost or stolen devices, ensuring data protection and regulatory compliance, while minimizing data breach risks. This tool empowers businesses to maintain control over mobile assets and enhance overall security.
                            </div>
                          </div>
                          <div className="features-img-container slide3 wf-reveal" style={{"willChange": "transform, opacity", "transform": "translate3d(-40px, 0px, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg)", "transformStyle": "preserve-3d", "opacity": "0", "--wf-op-dur": "1000ms", "--wf-op-delay": "0ms", "--wf-op-ease": "cubic-bezier(0.165,0.84,0.44,1)", "--wf-tr-dur": "1000ms", "--wf-tr-delay": "0ms", "--wf-tr-ease": "cubic-bezier(0.165,0.84,0.44,1)"}}>
                            <img src="/assets/product-devicewipe.webp" loading="lazy" width="676" sizes="(max-width: 767px) 100vw, 676px" alt="" srcSet="/assets/product-devicewipe-p-500.webp 500w, /assets/product-devicewipe-p-800.webp 800w, /assets/product-devicewipe-p-1080.webp 1080w, /assets/product-devicewipe.webp 1352w" className="features-img" />
                          </div>
                        </div>
                        <Link href="/demo" className="btn-large color_velvet w-inline-block">
                          <div className="btn-text-large color_mint">
                            Book a demo
                          </div>
                          <img src="/assets/arrow-icon-mint-v1.svg" loading="lazy" style={{"transform": "translate3d(0px, 0px, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg)", "transformStyle": "preserve-3d"}} alt="" className="btn-arrow-large" />
                          <div className="hero-btn-shine darker" style={{"transform": "translate3d(-100%, 0px, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg)", "transformStyle": "preserve-3d"}}></div>
                        </Link>
                      </section>
                      <div className="btm-tab">
                        <div className="shape-triangle _75_eg flipped mirrored smaller_mobile w-embed">
                          <svg version="1.1" baseProfile="basic" id="Triangle" xmlns="http://www.w3.org/2000/svg" xmlnsXlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 34 38" xmlSpace="preserve">
                            <path fill="currentColor" d="M0,0l34,38H0V0z"></path>
                          </svg>
                        </div>
                        <div className="tab-filler"></div>
                        <div className="shape-triangle _75_eg flipped smaller_mobile w-embed">
                          <svg version="1.1" baseProfile="basic" id="Triangle" xmlns="http://www.w3.org/2000/svg" xmlnsXlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 34 38" xmlSpace="preserve">
                            <path fill="currentColor" d="M0,0l34,38H0V0z"></path>
                          </svg>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </section>
            <section id="platform-features" className="section_v2 tint_40eg">
              <div className="page-padding">
                <div className="container-large">
                  <div className="padding-top small">
                    <div className="padding-btm large">
                      <div className="container-flex vertical center">
                        <div className="eyebrow-label-small product">
                          <div className="eyebrow-small color_rg">
                            Platform features
                          </div>
                        </div>
                        <div className="padding-btm small">
                          <div className="container-flex vertical center">
                            <div className="container-small">
                              <div className="narrow-text-container">
                                <div className="container-flex vertical center">
                                  <h4 className="h4_v2 color_rg">
                                    Secure your data with our comprehensive mobile device management solution
                                  </h4>
                                  <div className="padding-top xxxs">
                                    <div className="text-dek-m">
                                      Our platform empowers organizations to safeguard sensitive information through strong encryption, remote wipe capabilities, and stringent policy enforcement
                                    </div>
                                  </div>
                                </div>
                              </div>
                            </div>
                            <div className="platform-grid">
                              <div className="platform-item">
                                <img src="/assets/feature-dataencryption-v1.webp" loading="lazy" width="564" sizes="(max-width: 767px) 100vw, 564px" alt="" srcSet="/assets/feature-dataencryption-v1-p-500.webp 500w, /assets/feature-dataencryption-v1-p-800.webp 800w, /assets/feature-dataencryption-v1-p-1080.webp 1080w, /assets/feature-dataencryption-v1.webp 1128w" className="platform-img" />
                                <div className="platform-text">
                                  <h6 className="h6 larger_mobile">
                                    Data Encryption
                                  </h6>
                                  <div className="body-text-small">
                                    Ensures all sensitive data on devices are encrypted, protecting them from unauthorized access, even in the event of theft or loss.
                                  </div>
                                </div>
                              </div>
                              <div className="platform-item">
                                <img src="/assets/features-img2.webp" loading="lazy" width="562.5" sizes="(max-width: 767px) 100vw, 563px" alt="" srcSet="/assets/features-img2-p-500.webp 500w, /assets/features-img2-p-800.webp 800w, /assets/features-img2-p-1080.webp 1080w, /assets/features-img2.webp 1125w" className="platform-img" />
                                <div className="platform-text">
                                  <h6 className="h6 larger_mobile">
                                    Monitoring
                                  </h6>
                                  <div className="body-text-small">
                                    Provides real-time alerts to identify and fix issues quickly, keeping you on track.
                                  </div>
                                </div>
                              </div>
                              <div className="platform-item">
                                <img src="/assets/feature-policyenforcement-v1.webp" loading="lazy" width="564" sizes="(max-width: 767px) 100vw, 564px" alt="" srcSet="/assets/feature-policyenforcement-v1-p-500.webp 500w, /assets/feature-policyenforcement-v1-p-800.webp 800w, /assets/feature-policyenforcement-v1-p-1080.webp 1080w, /assets/feature-policyenforcement-v1.webp 1128w" className="platform-img" />
                                <div className="platform-text">
                                  <h6 className="h6 larger_mobile">
                                    Policy enforcement
                                  </h6>
                                  <div className="body-text-small">
                                    Mitigate risks associated with human error, unauthorized access, and potential data breaches.
                                  </div>
                                </div>
                              </div>
                            </div>
                            <Link href="/demo" className="btn-large w-inline-block">
                              <div className="btn-text-large">
                                Book a demo
                              </div>
                              <img src="/assets/arrow-icon-v2.svg" loading="lazy" style={{"transform": "translate3d(0px, 0px, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg)", "transformStyle": "preserve-3d"}} alt="" className="btn-arrow-large" />
                              <div style={{"transform": "translate3d(-100%, 0px, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg)", "transformStyle": "preserve-3d"}} className="hero-btn-shine"></div>
                            </Link>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </section>
          </div>
        </div>
        <ProductDeviceManagementSection4 />
        <div className="negative-margin-wrapper reduce_top">
          <section id="Features" className="section_v2 color_smoke">
            <div className="page-padding">
              <div className="padding-top xl">
                <div className="container-medium">
                  <div className="container-small narrower_desktop">
                    <div className="container-flex vertical">
                      <h3 className="h3_v2 color_white text_center">
                        Read the latest insights from our experts
                      </h3>
                      <div className="padding-top xxxs">
                        <div className="text-dek-s text_40_grey text_center">
                          Stay secure with expert, data-driven resources to strengthen your security knowledge and ensure compliance confidence.
                        </div>
                      </div>
                    </div>
                  </div>
                  <div className="padding-top small">
                    <div className="padding-btm large">
                      <div className="container-flex space-between _3up_blog">
                        <div className="_3up-blog-wrapper w-dyn-list">
                          <div role="list" className="_3up-blog-grid w-dyn-items">
                            {productDeviceManagementCollection1Data.map((item, i) => (
                              <ProductDeviceManagementCollection1 item={item} key={i} />
                            ))}
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </section>
        </div>
        <ProductDeviceManagementSection5 />
        <ProductDeviceManagementSection6 />
      </main>
      <SiteFooter />
    </div>
  );
}
