import { SubscribeCollection1 } from "./SubscribeCollection1";
import { subscribeCollection1Data } from "./SubscribeCollection1.data";
import { SiteNav22 } from "../../_shared/SiteNav22";
import { SiteFooter } from "../../_shared/SiteFooter";
import { SubscribeSection1 } from "./SubscribeSection1";
import { SubscribeSection2 } from "./SubscribeSection2";

/**
 * Faithful React port of the Webflow https://www.mycroft.io/subscribe page. DOM + classes mirror
 * the original 1:1; global styling is in webflow-shared.css, page CSS
 * in subscribe.css. Generated by the Webflow Cloner agent.
 */
export function SubscribeSnapshot() {
  return (
    <div className="page-wrapper u-minh-100vh">
      <div className="styles__global-embed-code w-embed"></div>
      <SiteNav22 />
      <main id="main" className="page-content">
        <SubscribeSection1 />
        <SubscribeSection2 />
        <div className="negative-margin-wrapper reduce_top">
          <section id="Features" className="section_v2 color_smoke">
            <div className="page-padding">
              <div className="padding-top xl">
                <div className="container-medium">
                  <div className="container-small narrower_desktop">
                    <div className="container-flex vertical">
                      <h3 className="h3_v2 color_white text_center">
                        Read the latest insights from our experts
                      </h3>
                      <div className="padding-top xxxs">
                        <div className="text-dek-s text_40_grey text_center">
                          Stay secure with expert, data-driven resources to strengthen your security knowledge and ensure compliance confidence.
                        </div>
                      </div>
                    </div>
                  </div>
                  <div className="padding-top small">
                    <div className="padding-btm large">
                      <div className="container-flex space-between _3up_blog">
                        <div className="_3up-blog-wrapper w-dyn-list">
                          <div role="list" className="_3up-blog-grid w-dyn-items">
                            {subscribeCollection1Data.map((item, i) => (
                              <SubscribeCollection1 item={item} key={i} />
                            ))}
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </section>
        </div>
      </main>
      <SiteFooter />
    </div>
  );
}
