import Link from "next/link";

/** Section 2 of /frameworks/cmmc. Generated by the Webflow Cloner agent. */
export function FrameworksCmmcSection2() {
  return (
    <section id="fw-features" className="section_v2 tint_60eg overflow_hidden">
      <div className="page-padding">
        <div className="container-small fw_features_hed">
          <div className="padding-top large">
            <div className="container-flex vertical">
              <div className="eyebrow-label-small product">
                <div className="eyebrow-small color_rg">
                  Features
                </div>
              </div>
              <h2 className="h2_v2 color_rg text_center">
                Mycroft’s AI platform solutions for CMMC
              </h2>
              <div className="padding-top xxs">
                <div className="text-dek-l text_center">
                  A unified platform designed to operationalize CMMC requirements without adding internal workload.
                </div>
              </div>
            </div>
          </div>
        </div>
        <div className="container-large">
          <div className="padding-top medium">
            <div className="padding-btm large">
              <div className="product-container">
                <section id="app-security" className="product-feature">
                  <div className="product-text wf-reveal" style={{"willChange": "opacity, transform", "opacity": "0", "transform": "translate3d(-100px, 0px, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg)", "transformStyle": "preserve-3d", "--wf-op-dur": "1000ms", "--wf-op-delay": "0ms", "--wf-op-ease": "cubic-bezier(0.165,0.84,0.44,1)", "--wf-tr-dur": "1000ms", "--wf-tr-delay": "0ms", "--wf-tr-ease": "cubic-bezier(0.165,0.84,0.44,1)"}}>
                    <h4 className="h4_v2 color_rg">
                      Risk assessment
                    </h4>
                    <div className="body-text-medium">
                      Identify, evaluate, and track organizational risks through a centralized platform designed to simplify remediation planning, ownership tracking, and ongoing risk management.
                    </div>
                    <Link href="/demo" className="text-link link_embed w-inline-block">
                      <div className="body-text-small color_aubergine text-500 link_underline">
                        Book a demo
                      </div>
                      <div style={{"transform": "translate3d(0px, 0px, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg)", "transformStyle": "preserve-3d"}} className="arrow-icon-small w-embed">
                        <svg id="a" data-name="mycroft-arrow_icon" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 10">
                          <path d="M14.04,3.46c-1.33-1-2.19-2.62-2.58-3.46l-1.49.54c.39.92,1.17,2.46,2.5,3.69H0v1.54h12.48c-1.33,1.15-2.11,2.77-2.5,3.69l1.49.54c.39-.92,1.25-2.46,2.58-3.46.39-.31,1.17-.77,1.96-.92v-1.23c-.78-.15-1.57-.54-1.96-.92Z" style={{"fill": "currentColor"}}></path>
                        </svg>
                      </div>
                    </Link>
                  </div>
                  <div className="product-feature-img wf-reveal" style={{"willChange": "opacity, transform", "opacity": "0", "transform": "translate3d(100px, 0px, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg)", "transformStyle": "preserve-3d", "--wf-op-dur": "1000ms", "--wf-op-delay": "0ms", "--wf-op-ease": "cubic-bezier(0.165,0.84,0.44,1)", "--wf-tr-dur": "1000ms", "--wf-tr-delay": "0ms", "--wf-tr-ease": "cubic-bezier(0.165,0.84,0.44,1)"}}>
                    <img src="/assets/risk-assessment.webp" loading="lazy" width="680" sizes="(max-width: 479px) 100vw, 680px" alt="" srcSet="/assets/risk-assessment-p-500.webp 500w, /assets/risk-assessment-p-800.webp 800w, /assets/risk-assessment-p-1080.webp 1080w, /assets/risk-assessment.webp 1360w" className="fw-features-img" />
                  </div>
                </section>
                <section id="threat-management" className="product-feature even-child">
                  <div className="product-feature-img img-left wf-reveal" style={{"willChange": "opacity, transform", "opacity": "0", "transform": "translate3d(-100px, 0px, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg)", "transformStyle": "preserve-3d", "--wf-op-dur": "1000ms", "--wf-op-delay": "0ms", "--wf-op-ease": "cubic-bezier(0.165,0.84,0.44,1)", "--wf-tr-dur": "1000ms", "--wf-tr-delay": "0ms", "--wf-tr-ease": "cubic-bezier(0.165,0.84,0.44,1)"}}>
                    <img src="/assets/cloud-security.webp" loading="lazy" width="680" sizes="(max-width: 479px) 100vw, 680px" alt="" srcSet="/assets/cloud-security-p-500.webp 500w, /assets/cloud-security-p-800.webp 800w, /assets/cloud-security-p-1080.webp 1080w, /assets/cloud-security.webp 1360w" className="fw-features-img" />
                  </div>
                  <div className="product-text text-right wf-reveal" style={{"willChange": "opacity, transform", "opacity": "0", "transform": "translate3d(100px, 0px, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg)", "transformStyle": "preserve-3d", "--wf-op-dur": "1000ms", "--wf-op-delay": "0ms", "--wf-op-ease": "cubic-bezier(0.165,0.84,0.44,1)", "--wf-tr-dur": "1000ms", "--wf-tr-delay": "0ms", "--wf-tr-ease": "cubic-bezier(0.165,0.84,0.44,1)"}}>
                    <h4 className="h4_v2 color_rg">
                      Cloud Security
                    </h4>
                    <div className="body-text-medium">
                      Monitor cloud environments for security gaps, compliance risks, and misconfigurations with continuous visibility designed to strengthen your overall cloud security posture.
                    </div>
                    <Link href="/demo" className="text-link link_embed w-inline-block">
                      <div className="body-text-small color_aubergine text-500 link_underline">
                        Book a demo
                      </div>
                      <div style={{"transform": "translate3d(0px, 0px, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg)", "transformStyle": "preserve-3d"}} className="arrow-icon-small w-embed">
                        <svg id="a" data-name="mycroft-arrow_icon" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 10">
                          <path d="M14.04,3.46c-1.33-1-2.19-2.62-2.58-3.46l-1.49.54c.39.92,1.17,2.46,2.5,3.69H0v1.54h12.48c-1.33,1.15-2.11,2.77-2.5,3.69l1.49.54c.39-.92,1.25-2.46,2.58-3.46.39-.31,1.17-.77,1.96-.92v-1.23c-.78-.15-1.57-.54-1.96-.92Z" style={{"fill": "currentColor"}}></path>
                        </svg>
                      </div>
                    </Link>
                  </div>
                </section>
                <section id="agentic-ai" className="product-feature last-child">
                  <div className="product-text wf-reveal" style={{"willChange": "opacity, transform", "opacity": "0", "transform": "translate3d(-100px, 0px, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg)", "transformStyle": "preserve-3d", "--wf-op-dur": "1000ms", "--wf-op-delay": "0ms", "--wf-op-ease": "cubic-bezier(0.165,0.84,0.44,1)", "--wf-tr-dur": "1000ms", "--wf-tr-delay": "0ms", "--wf-tr-ease": "cubic-bezier(0.165,0.84,0.44,1)"}}>
                    <h4 className="h4_v2 color_rg">
                      Security training
                    </h4>
                    <div className="body-text-medium">
                      Deliver security awareness and compliance training programs that help employees reduce human risk while supporting audit and regulatory requirements.
                    </div>
                    <Link href="/demo" className="text-link link_embed w-inline-block">
                      <div className="body-text-small color_aubergine text-500 link_underline">
                        Book a demo
                      </div>
                      <div style={{"transform": "translate3d(0px, 0px, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg)", "transformStyle": "preserve-3d"}} className="arrow-icon-small w-embed">
                        <svg id="a" data-name="mycroft-arrow_icon" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 10">
                          <path d="M14.04,3.46c-1.33-1-2.19-2.62-2.58-3.46l-1.49.54c.39.92,1.17,2.46,2.5,3.69H0v1.54h12.48c-1.33,1.15-2.11,2.77-2.5,3.69l1.49.54c.39-.92,1.25-2.46,2.58-3.46.39-.31,1.17-.77,1.96-.92v-1.23c-.78-.15-1.57-.54-1.96-.92Z" style={{"fill": "currentColor"}}></path>
                        </svg>
                      </div>
                    </Link>
                  </div>
                  <div className="product-feature-img wf-reveal" style={{"willChange": "opacity, transform", "opacity": "0", "transform": "translate3d(100px, 0px, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg)", "transformStyle": "preserve-3d", "--wf-op-dur": "1000ms", "--wf-op-delay": "0ms", "--wf-op-ease": "cubic-bezier(0.165,0.84,0.44,1)", "--wf-tr-dur": "1000ms", "--wf-tr-delay": "0ms", "--wf-tr-ease": "cubic-bezier(0.165,0.84,0.44,1)"}}>
                    <img src="/assets/security-training.webp" loading="lazy" width="680" sizes="(max-width: 479px) 100vw, 680px" alt="" srcSet="/assets/security-training-p-500.webp 500w, /assets/security-training-p-800.webp 800w, /assets/security-training-p-1080.webp 1080w, /assets/security-training.webp 1360w" className="fw-features-img" />
                  </div>
                </section>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
