import { CtaSection } from "@/app/_shared/CtaSection";
import { SiteNav } from "../../../_shared/SiteNav";
import { SiteFooter } from "../../../_shared/SiteFooter";
import { FrameworksCmmcSection1 } from "./FrameworksCmmcSection1";
import { FrameworksCmmcSection2 } from "./FrameworksCmmcSection2";
import { FrameworksCmmcSection3 } from "./FrameworksCmmcSection3";
import { FrameworksCmmcSection4 } from "./FrameworksCmmcSection4";
import { FrameworksCmmcSection5 } from "./FrameworksCmmcSection5";
import { UnlockFrameworksSection } from "@/app/_shared/UnlockFrameworksSection";

/**
 * Faithful React port of the Webflow https://mycroft.io/frameworks/cmmc page. DOM + classes mirror
 * the original 1:1; global styling is in webflow-shared.css, page CSS
 * in frameworks-cmmc.css. Generated by the Webflow Cloner agent.
 */
export function FrameworksCmmcSnapshot() {
  return (
    <div className="page-wrapper u-minh-100vh color_rg">
      <div className="styles__global-embed-code w-embed"></div>
      <SiteNav />
      <main id="main" className="page-content">
        <FrameworksCmmcSection1 />
        <FrameworksCmmcSection2 />
        <FrameworksCmmcSection3 />
        <FrameworksCmmcSection4 />
        <UnlockFrameworksSection
          blurb="Achieve CMMC compliance with Mycroft and take advantage of the head start gained in other industry frameworks."
          dials={[
            { href: "/frameworks/fedramp", label: "FedRAMP", lottie: "/lottie/6a024deb9a47cda7c321c5a3_Compliance-Dial_45.json" },
            { href: "/frameworks/iso27001", label: "ISO 27001", lottie: "/lottie/6a024deb01ab375d7de27c3b_Compliance-Dial_85.json" },
            { href: "/frameworks/soc2", label: "SOC 2", lottie: "/lottie/6a024deb473b0519f94adf43_Compliance-Dial_20.json" },
          ]}
        />
        <FrameworksCmmcSection5 />
        <CtaSection variant="fireplace" />
      </main>
      <SiteFooter />
    </div>
  );
}
