import { FaqItem } from "@/app/_shared/Accordion";

/** Section 5 of /frameworks/cmmc. Generated by the Webflow Cloner agent. */
export function FrameworksCmmcSection5() {
  return (
    <section className="section_v2 color_smoke">
      <div className="pr-(--sizing--rem--2rem) pl-(--sizing--rem--2rem) ml-auto mr-auto relative max-portrait:pr-(--sizing--rem--1-25rem) max-portrait:pl-(--sizing--rem--1-25rem)">
        <div className="w-full max-w-240 ml-auto mr-auto max-tablet:w-[90%] max-tablet:max-w-none max-landscape:w-full max-portrait:w-full">
          <div className="w-full pt-(--sizing--rem--4-5rem) max-tablet:pt-(--sizing--rem--3-5rem) max-landscape:pt-(--sizing--rem--2-5rem) max-portrait:pt-(--sizing--rem--1-5rem)">
            <div className="w-full pb-(--sizing--rem--6rem) max-tablet:pb-(--sizing--rem--5rem) max-landscape:pb-(--sizing--rem--3-5rem) max-portrait:pb-(--sizing--rem--2-5rem)">
              <img src="/assets/faq-notchlabel-desktop.svg" loading="lazy" alt="" className="faq-notch-desktop" />
              <img src="/assets/faq-notchlabel-mobile.svg" loading="lazy" alt="" className="faq-notch-mobile" />
              <div className="container-flex faq_container">
                <div className="faq-hed-flex">
                  <h3 className="h3_v2 color_white">
                    Frequently asked questions
                  </h3>
                  <div className="text-dek-l text_40eg">
                    Answers that help customers with CMMC compliance
                  </div>
                </div>
                <FaqItem question="What is CMMC?" first>
                  CMMC (Cybersecurity Maturity Model Certification) is a framework required by the U.S. Department of Defense to ensure contractors protect federal contract information and controlled unclassified information.
                </FaqItem>
                <FaqItem question="What are the CMMC levels?">
                  CMMC has three levels:
                      <br />
                      Level 1 focuses on basic safeguarding of federal contract information
                      <br />
                      Level 2 aligns with NIST SP 800-171 for controlled unclassified information
                      <br />
                      Level 3 adds advanced security requirements for higher-risk environments
                </FaqItem>
                <FaqItem question="Do we need CMMC certification?">
                  If you work with the Department of Defense or its contractors, you must achieve the required CMMC level to bid on or maintain contracts.
                </FaqItem>
                <FaqItem question="How long does CMMC certification take?">
                  Timelines vary by level and readiness, but most organizations take several months. With the right approach, timelines can be significantly reduced.
                </FaqItem>
                <FaqItem question="How does Mycroft help with CMMC?" last>
                  Mycroft supports compliance across Levels 1, 2, and 3 by handling policy creation, control implementation, and evidence collection so your team is not burdened with execution.
                </FaqItem>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
