import type { Metadata } from "next";
import { ProductAuditAndComplianceSnapshot } from "./_snapshot/ProductAuditAndComplianceSnapshot";
import { WebflowInteractions } from "../../_shared/WebflowInteractions";

export const metadata: Metadata = {
  title: "Audit and compliance",
  description: "Explore how Mycroft’s platform can get you compliant fast.",
  openGraph: {
    title: "Audit and compliance",
    description: "Explore how Mycroft’s platform can get you compliant fast.",
    type: "website",
    images: ["/assets/audit-compliance-meta-img-v1.jpg"],
  },
  twitter: {
    card: "summary_large_image",
    title: "Audit and compliance",
    description: "Explore how Mycroft’s platform can get you compliant fast.",
    images: ["/assets/audit-compliance-meta-img-v1.jpg"],
  },
};

/**
 * /product/audit-and-compliance: a faithful React rebuild of the Webflow page.
 * Generated by the Webflow Cloner agent from https://mycroft.io/product/audit-and-compliance.
 */
export default function ProductAuditAndCompliancePage() {
  return (
    <>
      <ProductAuditAndComplianceSnapshot />
      <WebflowInteractions />
    </>
  );
}
