import type { Metadata } from "next";
import { HomePageContent } from "./_sections/HomePageContent";
import { WebflowInteractions } from "./_shared/WebflowInteractions";

export const metadata: Metadata = {
  title: "Mycroft | Security automated for enterprise standards",
  description: "Mycroft is the platform that serves as your virtual Security and Compliance officer, consolidating all your security needs, supported by experts.",
  alternates: { canonical: "https://www.mycroft.io" },
  openGraph: {
    title: "Mycroft | Security automated for enterprise standards",
    description: "Mycroft is the platform that serves as your virtual Security and Compliance officer, consolidating all your security needs, supported by experts.",
    type: "website",
    images: ["/assets/meta/mycroft-meta-img-home.webp"],
  },
  twitter: {
    card: "summary_large_image",
    title: "Mycroft | Security automated for enterprise standards",
    description: "Mycroft is the platform that serves as your virtual Security and Compliance officer, consolidating all your security needs, supported by experts.",
    images: ["/assets/meta/mycroft-meta-img-home.webp"],
  },
};

/**
 * /home: a faithful React rebuild of the Webflow page.
 * Generated by the Webflow Cloner agent from https://www.mycroft.io.
 */
export default function HomePage() {
  return (
    <>
      <HomePageContent />
      <WebflowInteractions />
    </>
  );
}
