import type { MetadataRoute } from "next";
import { SITE_URL } from "@/lib/site-url";

/**
 * Mirrors the original site's sitemap.xml 1:1.
 */

export default function sitemap(): MetadataRoute.Sitemap {
  return [
    { url: `${SITE_URL}/` },
    { url: `${SITE_URL}/product` },
    { url: `${SITE_URL}/pricing` },
    { url: `${SITE_URL}/demo` },
    { url: `${SITE_URL}/integrations` },
    { url: `${SITE_URL}/privacy` },
    { url: `${SITE_URL}/security` },
    { url: `${SITE_URL}/terms` },
    { url: `${SITE_URL}/about` },
    { url: `${SITE_URL}/thank-you` },
    { url: `${SITE_URL}/resources` },
    { url: `${SITE_URL}/faqs` },
    { url: `${SITE_URL}/product/audit-and-compliance` },
    { url: `${SITE_URL}/subscribe` },
    { url: `${SITE_URL}/partnerships` },
    { url: `${SITE_URL}/product/cloud-security` },
    { url: `${SITE_URL}/product/app-security` },
    { url: `${SITE_URL}/product/device-management` },
    { url: `${SITE_URL}/product/third-party-risk-management` },
    { url: `${SITE_URL}/frameworks/soc2` },
    { url: `${SITE_URL}/frameworks/gdpr` },
    { url: `${SITE_URL}/frameworks/pipeda` },
    { url: `${SITE_URL}/frameworks/cmmc` },
    { url: `${SITE_URL}/frameworks/fedramp` },
    { url: `${SITE_URL}/frameworks/iso27001` },
    { url: `${SITE_URL}/frameworks/hipaa` },
    { url: `${SITE_URL}/frameworks/cpra` },
    { url: `${SITE_URL}/frameworks/iso42001` },
    { url: `${SITE_URL}/blog/ai-security-platform-buyers-guide` },
    { url: `${SITE_URL}/blog/automate-user-acces-reviews` },
    { url: `${SITE_URL}/blog/cmmc-compliance-platform` },
    { url: `${SITE_URL}/blog/compliance-automation-for-startups` },
    { url: `${SITE_URL}/blog/continuous-compliance-monitoring-the-complete-guide` },
    { url: `${SITE_URL}/blog/how-long-does-soc-2-take-a-realistic-breakdown-for-startups-and-saas` },
    { url: `${SITE_URL}/blog/how-to-eliminate-security-tool-sprawl` },
    { url: `${SITE_URL}/blog/iso-27001-vs-cmmc` },
    { url: `${SITE_URL}/blog/iso-27001-vs-soc-2-startups` },
    { url: `${SITE_URL}/blog/managed-compliance-services` },
    { url: `${SITE_URL}/blog/security-audits-guide-2026` },
    { url: `${SITE_URL}/blog/security-orchestration-automation` },
    { url: `${SITE_URL}/blog/soc-2-automation` },
    { url: `${SITE_URL}/blog/soc-2-compliance` },
    { url: `${SITE_URL}/blog/stealth-to-seed-mycrofts-ai-security-compliance-platform-backed-by-3-5m-led-by-luge-capital` },
    { url: `${SITE_URL}/blog/third-party-risk-management-for-enterprise-why-current-approaches-just-dont-work-anymore` },
    { url: `${SITE_URL}/blog/third-party-vendor-risk-management` },
    { url: `${SITE_URL}/blog/understanding-cloud-security-in-the-ai-era-how-to-succeed-in-2026-and-beyond` },
    { url: `${SITE_URL}/blog/vendor-risk-management-software` },
    { url: `${SITE_URL}/blog/whats-the-most-efficient-way-to-handle-cmmc-compliance-assessments` },
    { url: `${SITE_URL}/case-studies/smashsend` },
    { url: `${SITE_URL}/case-studies/unified` },
    { url: `${SITE_URL}/case-studies/weave` },
    { url: `${SITE_URL}/case-studies/wisedocs` },
  ];
}
