/** Section 2 of /faqs. Generated by the Webflow Cloner agent. */
export function FaqsSection2() {
  return (
    <section id="about-mycroft" className="section_v2 earl40">
      <div className="page-padding">
        <div className="container-large">
          <div className="padding-top medium">
            <div className="padding-btm xl">
              <div className="blog-container">
                <div className="content-wrapper slim w-container">
                  <div className="accordion-wrapper">
                    <div className="accordion-item">
                      <div id="q1" className="accordion-item-trigger">
                        <h4 className="accordion-heading">
                          <strong>
                            What is Mycroft?
                          </strong>
                        </h4>
                        <img src="/assets/arrow-icon.svg" loading="lazy" width="25" style={{"transform": "translate3d(0px, 0px, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(180deg) skew(0deg, 0deg)", "transformStyle": "preserve-3d"}} alt="" />
                      </div>
                      <div className="accordion-item-content" style={{"height": "0px"}}>
                        <p>
                          Mycroft is an AI-powered security and compliance platform that consolidates essential cybersecurity and compliance functions into a unified system, helping organizations achieve certifications and maintain ongoing protection with minimal effort.
                        </p>
                      </div>
                    </div>
                    <div className="accordion-item">
                      <div id="q1" className="accordion-item-trigger">
                        <h4 className="accordion-heading">
                          <strong>
                            What makes Mycroft unique?
                          </strong>
                        </h4>
                        <img src="/assets/arrow-icon.svg" loading="lazy" width="25" alt="" />
                      </div>
                      <div className="accordion-item-content" style={{"height": "0px"}}>
                        <p>
                          Mycroft combines five essential functions — security monitoring, compliance automation, risk management, device management, and AI-driven analysis — into a single platform. It acts as an autonomous AI Security and Compliance Officer for modern organizations.
                        </p>
                      </div>
                    </div>
                    <div className="accordion-item">
                      <div id="q1" className="accordion-item-trigger">
                        <h4 className="accordion-heading">
                          <strong>
                            What problem does Mycroft solve?
                          </strong>
                        </h4>
                        <img src="/assets/arrow-icon.svg" loading="lazy" width="25" alt="" />
                      </div>
                      <div className="accordion-item-content" style={{"height": "0px"}}>
                        <p>
                          Most growing companies juggle multiple fragmented tools to stay compliant and secure. Mycroft eliminates this complexity by providing a centralized, AI-driven system that automates compliance, monitors threats, and ensures continuous audit readiness.
                        </p>
                      </div>
                    </div>
                    <div className="accordion-item">
                      <div id="q1" className="accordion-item-trigger">
                        <h4 className="accordion-heading">
                          <strong>
                            How does Mycroft automate compliance and security?
                          </strong>
                        </h4>
                        <img src="/assets/arrow-icon.svg" loading="lazy" width="25" alt="" />
                      </div>
                      <div className="accordion-item-content" style={{"height": "0px"}}>
                        <p>
                          Mycroft uses AI Agents to continuously monitor compliance across frameworks such as SOC 2, ISO 27001, and HIPAA, collect evidence automatically, and manage security incidents in real time.
                        </p>
                      </div>
                    </div>
                    <div className="accordion-item">
                      <div id="q1" className="accordion-item-trigger">
                        <h4 className="accordion-heading">
                          <strong>
                            What certifications and frameworks does Mycroft support?
                          </strong>
                        </h4>
                        <img src="/assets/arrow-icon.svg" loading="lazy" width="25" alt="" />
                      </div>
                      <div className="accordion-item-content" style={{"height": "0px"}}>
                        <p>
                          Mycroft supports major standards including SOC 2, ISO 27001, GDPR, CMMC , FedRAMP, FedRAMP 20X and HIPAA. Its architecture enables organizations to achieve and maintain multiple certifications simultaneously through automation and continuous monitoring.
                        </p>
                      </div>
                    </div>
                    <div className="accordion-item">
                      <div id="q1" className="accordion-item-trigger">
                        <h4 className="accordion-heading">
                          <strong>
                            Why choose Mycroft over other solutions?
                          </strong>
                        </h4>
                        <img src="/assets/arrow-icon.svg" loading="lazy" width="25" alt="" />
                      </div>
                      <div className="accordion-item-content" style={{"height": "0px"}}>
                        <p>
                          Mycroft uniquely consolidates the entire security stack while automating workflows powered by AI Agents, combining compliance, security, and device management for a comprehensive solution.
                        </p>
                      </div>
                    </div>
                    <div className="accordion-item">
                      <div id="q1" className="accordion-item-trigger">
                        <h4 className="accordion-heading">
                          <strong>
                            What role do AI Agents play in Mycroft’s platform?
                          </strong>
                        </h4>
                        <img src="/assets/arrow-icon.svg" loading="lazy" width="25" alt="" />
                      </div>
                      <div className="accordion-item-content" style={{"height": "0px"}}>
                        <p>
                          AI Agents function as virtual Security and Compliance Officers, autonomously managing monitoring, audit prep, and remediation tasks — reducing the need for large internal teams.
                        </p>
                      </div>
                    </div>
                    <div className="accordion-item">
                      <div id="q1" className="accordion-item-trigger">
                        <h4 className="accordion-heading">
                          <strong>
                            How does Mycroft help with audits?
                          </strong>
                        </h4>
                        <img src="/assets/arrow-icon.svg" loading="lazy" width="25" alt="" />
                      </div>
                      <div className="accordion-item-content" style={{"height": "0px"}}>
                        <p>
                          Mycroft maintains audit-ready documentation, continuously gathers evidence, and generates auditor exports, enabling organizations to complete audits faster and with higher first-time pass rates.
                        </p>
                      </div>
                    </div>
                    <div className="accordion-item">
                      <div id="q1" className="accordion-item-trigger">
                        <h4 className="accordion-heading">
                          <strong>
                            What are Mycroft's core features?
                          </strong>
                        </h4>
                        <img src="/assets/arrow-icon.svg" loading="lazy" width="25" alt="" />
                      </div>
                      <div className="accordion-item-content" style={{"height": "0px"}}>
                        <p>
                          Its core features include integrated security and compliance, automated evidence collection, and 24/7 expert support through a dedicated Risk Operations Center.
                        </p>
                      </div>
                    </div>
                    <div className="accordion-item">
                      <div id="q1" className="accordion-item-trigger">
                        <h4 className="accordion-heading">
                          <strong>
                            How does Mycroft ensure continuous compliance?
                          </strong>
                        </h4>
                        <img src="/assets/arrow-icon.svg" loading="lazy" width="25" alt="" />
                      </div>
                      <div className="accordion-item-content" style={{"height": "0px"}}>
                        <p>
                          Mycroft uses AI Agents to autonomously manage and monitor compliance status, proactively keeping organizations ahead of requirements without manual checks.
                        </p>
                      </div>
                    </div>
                    <div className="accordion-item">
                      <div id="q1" className="accordion-item-trigger">
                        <h4 className="accordion-heading">
                          <strong>
                            What makes Mycroft's reporting system superior?
                          </strong>
                        </h4>
                        <img src="/assets/arrow-icon.svg" loading="lazy" width="25" alt="" />
                      </div>
                      <div className="accordion-item-content" style={{"height": "0px"}}>
                        <p>
                          Mycroft’s integrated reporting provides real-time insights through its AI Security and Compliance Officer, allowing businesses to adapt quickly and make informed strategic decisions.
                        </p>
                      </div>
                    </div>
                    <div className="accordion-item">
                      <div id="q1" className="accordion-item-trigger">
                        <h4 className="accordion-heading">
                          <strong>
                            What are the benefits of bundling a pen test with Mycroft?
                          </strong>
                        </h4>
                        <img src="/assets/arrow-icon.svg" loading="lazy" width="25" alt="" />
                      </div>
                      <div className="accordion-item-content" style={{"height": "0px"}}>
                        <p>
                          Bundling a penetration test with Mycroft is faster, often cheaper, and improves the efficiency of evidence handling. By using Mycroft's all-in-one platform, organizations streamline their security and compliance processes while ensuring comprehensive coverage for their cybersecurity needs.
                        </p>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
