import { CtaSection } from "@/app/_shared/CtaSection";
import { SiteNav } from "../../_shared/SiteNav";
import { SiteFooter } from "../../_shared/SiteFooter";
import { FaqsSection1 } from "./FaqsSection1";
import { FaqsSection2 } from "./FaqsSection2";
import { FaqsSection3 } from "./FaqsSection3";

/**
 * Faithful React port of the Webflow https://www.mycroft.io/faqs page. DOM + classes mirror
 * the original 1:1; global styling is in webflow-shared.css, page CSS
 * in faqs.css. Generated by the Webflow Cloner agent.
 */
export function FaqsSnapshot() {
  return (
    <div className="page-wrapper u-minh-100vh">
      <div className="styles__global-embed-code w-embed"></div>
      <SiteNav />
      <main id="main" className="page-content">
        <FaqsSection1 />
        <FaqsSection2 />
        <div className="overlap-top">
          <div className="overlap-block"></div>
          <div className="w-full max-w-300 ml-auto mr-auto">
            <div className="overlap-block top_block"></div>
          </div>
          <div className="overlap-block transparent"></div>
        </div>
        <FaqsSection3 />
        <CtaSection variant="fireplace" />
      </main>
      <SiteFooter />
    </div>
  );
}
