import { ComplianceSection } from "../../_shared/ComplianceSection";

/** Section 3 of /faqs. Generated by the Webflow Cloner agent. */
export function FaqsSection3() {
  return (
    <div className="section-overlap">
      <ComplianceSection />
    </div>
  );
}
