import { SiteNav22 } from "../../_shared/SiteNav22";
import { SiteFooter } from "../../_shared/SiteFooter";
import { FaqsSection1 } from "./FaqsSection1";
import { FaqsSection2 } from "./FaqsSection2";
import { FaqsSection3 } from "./FaqsSection3";
import { FaqsSection4 } from "./FaqsSection4";

/**
 * Faithful React port of the Webflow https://www.mycroft.io/faqs page. DOM + classes mirror
 * the original 1:1; global styling is in webflow-shared.css, page CSS
 * in faqs.css. Generated by the Webflow Cloner agent.
 */
export function FaqsSnapshot() {
  return (
    <div className="page-wrapper u-minh-100vh">
      <div className="styles__global-embed-code w-embed"></div>
      <SiteNav22 />
      <main id="main" className="page-content">
        <FaqsSection1 />
        <FaqsSection2 />
        <div className="overlap-top">
          <div className="overlap-block"></div>
          <div className="container-large">
            <div className="overlap-block top_block"></div>
          </div>
          <div className="overlap-block transparent"></div>
        </div>
        <FaqsSection3 />
        <FaqsSection4 />
      </main>
      <SiteFooter />
    </div>
  );
}
