/** Section 1 of /faqs. Generated by the Webflow Cloner agent. */
export function FaqsSection1() {
  return (
    <section id="hero" className="section-hero">
      <div className="page-padding">
        <div className="container-medium">
          <div className="container-flex hero_resources">
            <div className="hero-copy text_center">
              <h1 className="h1_v2 color_rg">
                Frequently asked questions
              </h1>
              <div className="padding-top xxxs">
                <div className="text-dek-l">
                  Get answers to commonly asked GRC questions
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div className="cursor-glow green_background"></div>
      <div className="hero-background color_integrations"></div>
      <div className="hero-background color_overlay_green"></div>
      <div className="hero-background pattern_pixels extra_bright"></div>
      <div className="overlap-top">
        <div className="overlap-block earl40"></div>
        <div className="container-large">
          <div className="overlap-block top_block _50percent earl40"></div>
        </div>
        <div className="overlap-block transparent"></div>
      </div>
    </section>
  );
}
