import { TrustedBySection } from "@/app/_shared/LogoMarquee";
import { CtaSection } from "@/app/_shared/CtaSection";
import { ProductThirdPartyRiskManagementCollection1 } from "./ProductThirdPartyRiskManagementCollection1";
import { productThirdPartyRiskManagementCollection1Data } from "./ProductThirdPartyRiskManagementCollection1.data";
import { ButtonLarge } from "@/app/_shared/ButtonLarge";
import { SiteNav } from "../../../_shared/SiteNav";
import { SiteFooter } from "../../../_shared/SiteFooter";
import { ProductThirdPartyRiskManagementSection1 } from "./ProductThirdPartyRiskManagementSection1";
import { ProductThirdPartyRiskManagementSection3 } from "./ProductThirdPartyRiskManagementSection3";
import { ProductThirdPartyRiskManagementSection4 } from "./ProductThirdPartyRiskManagementSection4";
import { ProductThirdPartyRiskManagementSection5 } from "./ProductThirdPartyRiskManagementSection5";
import { ScrollFeatureSlider, type ScrollFeatureSlide } from "@/app/_shared/ScrollFeatureSlider";

const thirdPartyRiskSlides: ScrollFeatureSlide[] = [
  {
    heading: "TPRM dashboard",
    body: "Our dashboard provides an overview of assessment statuses, showing the number of completed versus incomplete evaluations and includes a breakdown of vendor criticality to prioritize your focus –helping you efficiently monitor, prioritize, and manage third-party risks.",
    image: {
      src: "/assets/product-dashboard.webp",
      srcSet:
        "/assets/product-dashboard-p-500.webp 500w, /assets/product-dashboard-p-800.webp 800w, /assets/product-dashboard-p-1080.webp 1080w, /assets/product-dashboard.webp 1352w",
      sizes: "(max-width: 767px) 100vw, 676px",
      width: 676,
    },
  },
  {
    heading: "Assessment checklist",
    body: "Our platform allows users to select a vendor and access a tailored checklist of actionable steps. Completing these actions ensures the vendor meets your security and compliance standards, streamlining the onboarding and risk mitigation processes.",
    image: {
      src: "/assets/product-checklist.webp",
      srcSet:
        "/assets/product-checklist-p-500.webp 500w, /assets/product-checklist-p-800.webp 800w, /assets/product-checklist-p-1080.webp 1080w, /assets/product-checklist.webp 1352w",
      sizes: "(max-width: 767px) 100vw, 676px",
      width: 676,
    },
  },
];

/**
 * Faithful React port of the Webflow https://mycroft.io/product/third-party-risk-management page. DOM + classes mirror
 * the original 1:1; global styling is in webflow-shared.css, page CSS
 * in product-third-party-risk-management.css. Generated by the Webflow Cloner agent.
 */
export function ProductThirdPartyRiskManagementSnapshot() {
  return (
    <div className="page-wrapper u-minh-100vh color_rg">
      <div className="styles__global-embed-code w-embed"></div>
      <SiteNav />
      <main id="main" className="page-content">
        <ProductThirdPartyRiskManagementSection1 />
        <TrustedBySection btm="rg" />
        <ProductThirdPartyRiskManagementSection3 />
        <div className="scroll-container-outer _2_features">
          <div className="scroll-container-inner">
            <section id="product-features" className="section_v2 split_background rg_40earlgrey">
              <div className="pr-(--sizing--rem--2rem) pl-(--sizing--rem--2rem) ml-auto mr-auto relative max-portrait:pr-(--sizing--rem--1-25rem) max-portrait:pl-(--sizing--rem--1-25rem)">
                <div className="container-xl">
                  <div className="w-full pb-(--sizing--rem--4-5rem) max-tablet:pb-(--sizing--rem--3-5rem) max-landscape:pb-(--sizing--rem--2-5rem) max-portrait:pb-(--sizing--rem--1-5rem)">
                    <div className="scroll-slider-outer">
                      <ScrollFeatureSlider id="audit-compliance" slides={thirdPartyRiskSlides}>
                        <ButtonLarge href="/demo" velvet shine>
                          Book a demo
                        </ButtonLarge>
                      </ScrollFeatureSlider>
                      <div className="btm-tab">
                        <div className="shape-triangle _75_eg flipped mirrored smaller_mobile w-embed">
                          <svg version="1.1" baseProfile="basic" id="Triangle" xmlns="http://www.w3.org/2000/svg" xmlnsXlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 34 38" xmlSpace="preserve">
                            <path fill="currentColor" d="M0,0l34,38H0V0z"></path>
                          </svg>
                        </div>
                        <div className="tab-filler"></div>
                        <div className="shape-triangle _75_eg flipped smaller_mobile w-embed">
                          <svg version="1.1" baseProfile="basic" id="Triangle" xmlns="http://www.w3.org/2000/svg" xmlnsXlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 34 38" xmlSpace="preserve">
                            <path fill="currentColor" d="M0,0l34,38H0V0z"></path>
                          </svg>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </section>
            <section id="platform-features" className="section_v2 tint_40eg">
              <div className="pr-(--sizing--rem--2rem) pl-(--sizing--rem--2rem) ml-auto mr-auto relative max-portrait:pr-(--sizing--rem--1-25rem) max-portrait:pl-(--sizing--rem--1-25rem)">
                <div className="w-full max-w-300 ml-auto mr-auto">
                  <div className="w-full pt-(--sizing--rem--2-5rem) max-tablet:pt-(--sizing--rem--2rem) max-landscape:pt-(--sizing--rem--1-5rem) max-portrait:pt-(--sizing--rem--1rem)">
                    <div className="w-full pb-(--sizing--rem--6rem) max-tablet:pb-(--sizing--rem--5rem) max-landscape:pb-(--sizing--rem--3-5rem) max-portrait:pb-(--sizing--rem--2-5rem)">
                      <div className="container-flex vertical center">
                        <div className="eyebrow-label-small product">
                          <div className="eyebrow-small color_rg">
                            Platform features
                          </div>
                        </div>
                        <div className="w-full pb-(--sizing--rem--2-5rem) max-tablet:pb-(--sizing--rem--2rem) max-landscape:pb-(--sizing--rem--1-5rem) max-portrait:pb-(--sizing--rem--1rem)">
                          <div className="container-flex vertical center">
                            <div className="w-full max-w-200 ml-auto mr-auto max-tablet:w-[80%] max-tablet:max-w-none max-landscape:w-[92%] max-portrait:w-full">
                              <div className="narrow-text-container">
                                <div className="container-flex vertical center">
                                  <h4 className="h4_v2 color_rg">
                                    Manage TPRM risks effectively with our platform
                                  </h4>
                                  <div className="w-full pt-(--sizing--rem--0-75rem) max-tablet:pt-[.65rem] max-portrait:pt-[.4rem]">
                                    <div className="text-dek-m">
                                      Prioritize your high-risk relationships with our platform by providing clear insights into vendor assessment statuses, criticality levels, and compliance metrics.
                                    </div>
                                  </div>
                                </div>
                              </div>
                            </div>
                            <div className="platform-grid">
                              <div className="platform-item">
                                <img src="/assets/features-img2.webp" loading="lazy" width="562.5" sizes="(max-width: 767px) 100vw, 563px" alt="" srcSet="/assets/features-img2-p-500.webp 500w, /assets/features-img2-p-800.webp 800w, /assets/features-img2-p-1080.webp 1080w, /assets/features-img2.webp 1125w" className="platform-img" />
                                <div className="platform-text">
                                  <h6 className="h6 larger_mobile">
                                    Monitoring
                                  </h6>
                                  <div className="body-text-small">
                                    Real-time signals from your vendor ecosystem—security, compliance, access, and changes that matter—without manual check-ins.
                                  </div>
                                </div>
                              </div>
                              <div className="platform-item">
                                <img src="/assets/feature-risktriage-v1.webp" loading="lazy" width="564" sizes="(max-width: 767px) 100vw, 564px" alt="" srcSet="/assets/feature-risktriage-v1-p-500.webp 500w, /assets/feature-risktriage-v1-p-800.webp 800w, /assets/feature-risktriage-v1-p-1080.webp 1080w, /assets/feature-risktriage-v1.webp 1128w" className="platform-img" />
                                <div className="platform-text">
                                  <h6 className="h6 larger_mobile">
                                    Risk triage & prioritization
                                  </h6>
                                  <div className="body-text-small">
                                    A clear view of your highest-risk vendors, why they’re risky, and what to do next—ranked by impact and criticality.
                                  </div>
                                </div>
                              </div>
                              <div className="platform-item">
                                <img src="/assets/feature-automatedworkflows-v1.webp" loading="lazy" width="564" sizes="(max-width: 767px) 100vw, 564px" alt="" srcSet="/assets/feature-automatedworkflows-v1-p-500.webp 500w, /assets/feature-automatedworkflows-v1-p-800.webp 800w, /assets/feature-automatedworkflows-v1-p-1080.webp 1080w, /assets/feature-automatedworkflows-v1.webp 1128w" className="platform-img" />
                                <div className="platform-text">
                                  <h6 className="h6 larger_mobile">
                                    Automated workflows
                                  </h6>
                                  <div className="body-text-small">
                                    Kick off reviews, collect evidence, request attestations, and track remediation with automated tasks, reminders, and approvals.
                                  </div>
                                </div>
                              </div>
                            </div>
                            <ButtonLarge href="/demo" shine>
                              Book a demo
                            </ButtonLarge>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </section>
          </div>
        </div>
        <ProductThirdPartyRiskManagementSection4 />
        <div className="negative-margin-wrapper reduce_top">
          <section id="Features" className="section_v2 color_smoke">
            <div className="pr-(--sizing--rem--2rem) pl-(--sizing--rem--2rem) ml-auto mr-auto relative max-portrait:pr-(--sizing--rem--1-25rem) max-portrait:pl-(--sizing--rem--1-25rem)">
              <div className="w-full pt-(--sizing--rem--8-5rem) max-tablet:pt-(--sizing--rem--6-5rem) max-landscape:pt-(--sizing--rem--4-5rem) max-portrait:pt-(--sizing--rem--3-5rem)">
                <div className="w-full max-w-240 ml-auto mr-auto max-tablet:w-[90%] max-tablet:max-w-none max-landscape:w-full max-portrait:w-full">
                  <div className="w-full max-w-184 ml-auto mr-auto max-tablet:w-[80%] max-tablet:max-w-none max-landscape:w-[92%] max-portrait:w-full">
                    <div className="container-flex vertical">
                      <h3 className="h3_v2 color_white text_center">
                        Read the latest insights from our experts
                      </h3>
                      <div className="w-full pt-(--sizing--rem--0-75rem) max-tablet:pt-[.65rem] max-portrait:pt-[.4rem]">
                        <div className="text-dek-s text_40_grey text_center">
                          Stay secure with expert, data-driven resources to strengthen your security knowledge and ensure compliance confidence.
                        </div>
                      </div>
                    </div>
                  </div>
                  <div className="w-full pt-(--sizing--rem--2-5rem) max-tablet:pt-(--sizing--rem--2rem) max-landscape:pt-(--sizing--rem--1-5rem) max-portrait:pt-(--sizing--rem--1rem)">
                    <div className="w-full pb-(--sizing--rem--6rem) max-tablet:pb-(--sizing--rem--5rem) max-landscape:pb-(--sizing--rem--3-5rem) max-portrait:pb-(--sizing--rem--2-5rem)">
                      <div className="container-flex space-between _3up_blog">
                        <div className="_3up-blog-wrapper w-dyn-list">
                          <div role="list" className="_3up-blog-grid w-dyn-items">
                            {productThirdPartyRiskManagementCollection1Data.map((item, i) => (
                              <ProductThirdPartyRiskManagementCollection1 item={item} key={i} />
                            ))}
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </section>
        </div>
        <ProductThirdPartyRiskManagementSection5 />
        <CtaSection variant="lamp" />
      </main>
      <SiteFooter />
    </div>
  );
}
