import { ProductThirdPartyRiskManagementCollection1 } from "./ProductThirdPartyRiskManagementCollection1";
import { productThirdPartyRiskManagementCollection1Data } from "./ProductThirdPartyRiskManagementCollection1.data";
import Link from "next/link";
import { SiteNav7 } from "../../../_shared/SiteNav7";
import { SiteFooter } from "../../../_shared/SiteFooter";
import { ProductThirdPartyRiskManagementSection1 } from "./ProductThirdPartyRiskManagementSection1";
import { ProductThirdPartyRiskManagementSection2 } from "./ProductThirdPartyRiskManagementSection2";
import { ProductThirdPartyRiskManagementSection3 } from "./ProductThirdPartyRiskManagementSection3";
import { ProductThirdPartyRiskManagementSection4 } from "./ProductThirdPartyRiskManagementSection4";
import { ProductThirdPartyRiskManagementSection5 } from "./ProductThirdPartyRiskManagementSection5";
import { ProductThirdPartyRiskManagementSection6 } from "./ProductThirdPartyRiskManagementSection6";

/**
 * Faithful React port of the Webflow https://mycroft.io/product/third-party-risk-management page. DOM + classes mirror
 * the original 1:1; global styling is in webflow-shared.css, page CSS
 * in product-third-party-risk-management.css. Generated by the Webflow Cloner agent.
 */
export function ProductThirdPartyRiskManagementSnapshot() {
  return (
    <div className="page-wrapper u-minh-100vh color_rg">
      <div className="styles__global-embed-code w-embed"></div>
      <SiteNav7 />
      <main id="main" className="page-content">
        <ProductThirdPartyRiskManagementSection1 />
        <ProductThirdPartyRiskManagementSection2 />
        <ProductThirdPartyRiskManagementSection3 />
        <div className="scroll-container-outer _2_features">
          <div className="scroll-container-inner">
            <section id="product-features" className="section_v2 split_background rg_40earlgrey">
              <div className="page-padding">
                <div className="container-xl">
                  <div className="padding-btm medium">
                    <div className="scroll-slider-outer">
                      <section id="audit-compliance" className="scroll-slider-inner">
                        <div className="enumeration-container">
                          <div className="enumeration-counter">
                            <div className="enumeration-absolute">
                              <div className="body-text-medium _75_rg enumeration1" style={{"willChange": "opacity", "opacity": "1"}}>
                                1
                                <br />
                              </div>
                            </div>
                            <div className="enumeration-absolute">
                              <div className="body-text-medium _75_rg enumeration2" style={{"willChange": "opacity", "opacity": "0"}}>
                                2
                                <br />
                              </div>
                            </div>
                          </div>
                          <div className="body-text-medium _75_rg">
                            /
                          </div>
                          <div className="body-text-medium _75_rg">
                            2
                          </div>
                        </div>
                        <div className="features-row static" style={{"willChange": "opacity", "opacity": "0"}}>
                          <div className="features-text">
                            <h4 className="h4_v2 color_rg">
                              Assessment checklist
                            </h4>
                            <div className="body-text-large smaller_tablet">
                              Our dashboard provides an overview of assessment statuses, showing the number of completed versus incomplete evaluations and includes a breakdown of vendor criticality to prioritize your focus –helping you efficiently monitor, prioritize, and manage third-party risks.
                            </div>
                          </div>
                          <div className="features-img-container">
                            <img src="/assets/product-frameworks.webp" loading="lazy" width="676" sizes="(max-width: 767px) 100vw, 676px" alt="" srcSet="/assets/product-frameworks-p-500.webp 500w, /assets/product-frameworks-p-800.webp 800w, /assets/product-frameworks-p-1080.webp 1080w, /assets/product-frameworks.webp 1352w" className="features-img" />
                          </div>
                        </div>
                        <div className="features-row absolute slide1">
                          <div className="features-text slide1" style={{"willChange": "transform, opacity", "transform": "translate3d(0px, 0px, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg)", "transformStyle": "preserve-3d", "opacity": "1"}}>
                            <h4 className="h4_v2 color_rg">
                              TPRM dashboard
                            </h4>
                            <div className="body-text-large smaller_tablet">
                              Our dashboard provides an overview of assessment statuses, showing the number of completed versus incomplete evaluations and includes a breakdown of vendor criticality to prioritize your focus –helping you efficiently monitor, prioritize, and manage third-party risks.
                            </div>
                          </div>
                          <div className="features-img-container slide1" style={{"willChange": "transform, opacity", "transform": "translate3d(0px, 0px, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg)", "transformStyle": "preserve-3d", "opacity": "1"}}>
                            <img src="/assets/product-dashboard.webp" loading="lazy" width="676" sizes="(max-width: 767px) 100vw, 676px" alt="" srcSet="/assets/product-dashboard-p-500.webp 500w, /assets/product-dashboard-p-800.webp 800w, /assets/product-dashboard-p-1080.webp 1080w, /assets/product-dashboard.webp 1352w" className="features-img" />
                          </div>
                        </div>
                        <div className="features-row absolute slide2">
                          <div className="features-text slide2 wf-reveal" style={{"willChange": "transform, opacity", "transform": "translate3d(0px, 40px, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg)", "transformStyle": "preserve-3d", "opacity": "0", "--wf-op-dur": "1000ms", "--wf-op-delay": "0ms", "--wf-op-ease": "cubic-bezier(0.165,0.84,0.44,1)", "--wf-tr-dur": "1000ms", "--wf-tr-delay": "0ms", "--wf-tr-ease": "cubic-bezier(0.165,0.84,0.44,1)"}}>
                            <h4 className="h4_v2 color_rg">
                              Assessment checklist
                            </h4>
                            <div className="body-text-large smaller_tablet">
                              Our platform allows users to select a vendor and access a tailored checklist of actionable steps. Completing these actions ensures the vendor meets your security and compliance standards, streamlining the onboarding and risk mitigation processes.
                            </div>
                          </div>
                          <div className="features-img-container slide2 wf-reveal" style={{"willChange": "transform, opacity", "transform": "translate3d(-40px, 0px, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg)", "transformStyle": "preserve-3d", "opacity": "0", "--wf-op-dur": "1000ms", "--wf-op-delay": "0ms", "--wf-op-ease": "cubic-bezier(0.165,0.84,0.44,1)", "--wf-tr-dur": "1000ms", "--wf-tr-delay": "0ms", "--wf-tr-ease": "cubic-bezier(0.165,0.84,0.44,1)"}}>
                            <img src="/assets/product-checklist.webp" loading="lazy" width="676" sizes="(max-width: 767px) 100vw, 676px" alt="" srcSet="/assets/product-checklist-p-500.webp 500w, /assets/product-checklist-p-800.webp 800w, /assets/product-checklist-p-1080.webp 1080w, /assets/product-checklist.webp 1352w" className="features-img" />
                          </div>
                        </div>
                        <Link href="/demo" className="btn-large color_velvet w-inline-block">
                          <div className="btn-text-large color_mint">
                            Book a demo
                          </div>
                          <img src="/assets/arrow-icon-mint-v1.svg" loading="lazy" style={{"transform": "translate3d(0px, 0px, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg)", "transformStyle": "preserve-3d"}} alt="" className="btn-arrow-large" />
                          <div className="hero-btn-shine darker" style={{"transform": "translate3d(-100%, 0px, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg)", "transformStyle": "preserve-3d"}}></div>
                        </Link>
                      </section>
                      <div className="btm-tab">
                        <div className="shape-triangle _75_eg flipped mirrored smaller_mobile w-embed">
                          <svg version="1.1" baseProfile="basic" id="Triangle" xmlns="http://www.w3.org/2000/svg" xmlnsXlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 34 38" xmlSpace="preserve">
                            <path fill="currentColor" d="M0,0l34,38H0V0z"></path>
                          </svg>
                        </div>
                        <div className="tab-filler"></div>
                        <div className="shape-triangle _75_eg flipped smaller_mobile w-embed">
                          <svg version="1.1" baseProfile="basic" id="Triangle" xmlns="http://www.w3.org/2000/svg" xmlnsXlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 34 38" xmlSpace="preserve">
                            <path fill="currentColor" d="M0,0l34,38H0V0z"></path>
                          </svg>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </section>
            <section id="platform-features" className="section_v2 tint_40eg">
              <div className="page-padding">
                <div className="container-large">
                  <div className="padding-top small">
                    <div className="padding-btm large">
                      <div className="container-flex vertical center">
                        <div className="eyebrow-label-small product">
                          <div className="eyebrow-small color_rg">
                            Platform features
                          </div>
                        </div>
                        <div className="padding-btm small">
                          <div className="container-flex vertical center">
                            <div className="container-small">
                              <div className="narrow-text-container">
                                <div className="container-flex vertical center">
                                  <h4 className="h4_v2 color_rg">
                                    Manage TPRM risks effectively with our platform
                                  </h4>
                                  <div className="padding-top xxxs">
                                    <div className="text-dek-m">
                                      Prioritize your high-risk relationships with our platform by providing clear insights into vendor assessment statuses, criticality levels, and compliance metrics.
                                    </div>
                                  </div>
                                </div>
                              </div>
                            </div>
                            <div className="platform-grid">
                              <div className="platform-item">
                                <img src="/assets/features-img2.webp" loading="lazy" width="562.5" sizes="(max-width: 767px) 100vw, 563px" alt="" srcSet="/assets/features-img2-p-500.webp 500w, /assets/features-img2-p-800.webp 800w, /assets/features-img2-p-1080.webp 1080w, /assets/features-img2.webp 1125w" className="platform-img" />
                                <div className="platform-text">
                                  <h6 className="h6 larger_mobile">
                                    Monitoring
                                  </h6>
                                  <div className="body-text-small">
                                    Real-time signals from your vendor ecosystem—security, compliance, access, and changes that matter—without manual check-ins.
                                  </div>
                                </div>
                              </div>
                              <div className="platform-item">
                                <img src="/assets/feature-risktriage-v1.webp" loading="lazy" width="564" sizes="(max-width: 767px) 100vw, 564px" alt="" srcSet="/assets/feature-risktriage-v1-p-500.webp 500w, /assets/feature-risktriage-v1-p-800.webp 800w, /assets/feature-risktriage-v1-p-1080.webp 1080w, /assets/feature-risktriage-v1.webp 1128w" className="platform-img" />
                                <div className="platform-text">
                                  <h6 className="h6 larger_mobile">
                                    Risk triage & prioritization
                                  </h6>
                                  <div className="body-text-small">
                                    A clear view of your highest-risk vendors, why they’re risky, and what to do next—ranked by impact and criticality.
                                  </div>
                                </div>
                              </div>
                              <div className="platform-item">
                                <img src="/assets/feature-automatedworkflows-v1.webp" loading="lazy" width="564" sizes="(max-width: 767px) 100vw, 564px" alt="" srcSet="/assets/feature-automatedworkflows-v1-p-500.webp 500w, /assets/feature-automatedworkflows-v1-p-800.webp 800w, /assets/feature-automatedworkflows-v1-p-1080.webp 1080w, /assets/feature-automatedworkflows-v1.webp 1128w" className="platform-img" />
                                <div className="platform-text">
                                  <h6 className="h6 larger_mobile">
                                    Automated workflows
                                  </h6>
                                  <div className="body-text-small">
                                    Kick off reviews, collect evidence, request attestations, and track remediation with automated tasks, reminders, and approvals.
                                  </div>
                                </div>
                              </div>
                            </div>
                            <Link href="/demo" className="btn-large w-inline-block">
                              <div className="btn-text-large">
                                Book a demo
                              </div>
                              <img src="/assets/arrow-icon-v2.svg" loading="lazy" style={{"transform": "translate3d(0px, 0px, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg)", "transformStyle": "preserve-3d"}} alt="" className="btn-arrow-large" />
                              <div style={{"transform": "translate3d(-100%, 0px, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg)", "transformStyle": "preserve-3d"}} className="hero-btn-shine"></div>
                            </Link>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </section>
          </div>
        </div>
        <ProductThirdPartyRiskManagementSection4 />
        <div className="negative-margin-wrapper reduce_top">
          <section id="Features" className="section_v2 color_smoke">
            <div className="page-padding">
              <div className="padding-top xl">
                <div className="container-medium">
                  <div className="container-small narrower_desktop">
                    <div className="container-flex vertical">
                      <h3 className="h3_v2 color_white text_center">
                        Read the latest insights from our experts
                      </h3>
                      <div className="padding-top xxxs">
                        <div className="text-dek-s text_40_grey text_center">
                          Stay secure with expert, data-driven resources to strengthen your security knowledge and ensure compliance confidence.
                        </div>
                      </div>
                    </div>
                  </div>
                  <div className="padding-top small">
                    <div className="padding-btm large">
                      <div className="container-flex space-between _3up_blog">
                        <div className="_3up-blog-wrapper w-dyn-list">
                          <div role="list" className="_3up-blog-grid w-dyn-items">
                            {productThirdPartyRiskManagementCollection1Data.map((item, i) => (
                              <ProductThirdPartyRiskManagementCollection1 item={item} key={i} />
                            ))}
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </section>
        </div>
        <ProductThirdPartyRiskManagementSection5 />
        <ProductThirdPartyRiskManagementSection6 />
      </main>
      <SiteFooter />
    </div>
  );
}
