import Image, { type StaticImageData } from "next/image";
import type { ComponentProps } from "react";
import dimensions from "@/lib/image-dimensions.json";

const DIMS: Record<string, { w: number; h: number }> = dimensions;

/**
 * Turns a width or height from the page into a plain number — but only when it
 * really is one.
 *
 * These images came over from Webflow, where the sizes were written
 * inconsistently: some have a real number like "100", some say "Auto", and some
 * have nothing at all. Size calculations only work with a real number, so
 * anything else (like "Auto") is treated as "no size was given".
 */
const toPx = (value: string | number | undefined): number | undefined => {
  if (typeof value === "number") return value;
  if (typeof value === "string" && /^\d+$/.test(value.trim())) return Number(value);
  return undefined;
};

/**
 * Works out the width and height to hand to `next/image`, which *requires* both
 * (that's how it reserves space and prevents layout shift). The page markup
 * can't be trusted to supply them, so we pick the most reliable source in
 * priority order:
 *
 *   1. Markup gives BOTH width and height → use them as-is.
 *      (e.g. the logo marquee, sized only by these attributes, with no CSS.)
 *   2. Markup gives width ONLY → keep that width and derive the height from the
 *      file's real proportions, so the image is never stretched.
 *      (e.g. the @2x product-hero art, whose display width is half the file.)
 *   3. Markup gives neither (or "Auto") → use the file's true pixel size and
 *      let the page's CSS decide how big it appears.
 *
 * `intrinsic` is the file's real on-disk size. It comes from the static-import
 * object when the call site passed one, or from `image-dimensions.json`
 * (generated by `scripts/build-image-manifest.mjs`) for a string `src`.
 */
function resolveDimensions(
  intrinsic: { w: number; h: number } | undefined,
  width: ComponentProps<"img">["width"],
  height: ComponentProps<"img">["height"],
): { w: number | undefined; h: number | undefined } {
  const markupWidth = toPx(width);
  const markupHeight = toPx(height);

  if (markupWidth !== undefined && markupHeight !== undefined) {
    return { w: markupWidth, h: markupHeight };
  }
  if (markupWidth !== undefined && intrinsic) {
    return { w: markupWidth, h: Math.round((markupWidth * intrinsic.h) / intrinsic.w) };
  }
  return { w: intrinsic?.w, h: intrinsic?.h };
}

/**
 * The site's image element.
 *
 * Most images are local raster files (JPG/PNG/WebP). For those it renders
 * `next/image`, which serves optimized AVIF/WebP, resizes per device, and
 * builds its own responsive sizing.  This improves load performance. 
 * 
 * The `srcSet` prop that was used on Webflow and width hints these images carried over from
 * Webflow are intentionally ignored on this path — `next/image` builds its
 * own, so the old ones aren't needed.
 *
 * Anything `next/image` can't optimize falls back to a plain `<img>`:
 *   • SVGs (icons, logos, arrows) — not a raster format, nothing to optimize.
 *   • Images with no recorded dimensions (a dynamic or remote `src`).
 *
 * That fallback is the only place in the app a raw `<img>` is allowed, which is
 * why the `@next/next/no-img-element` lint rule can stay on everywhere else.
 *
 * Call sites pass the same props they'd pass to a normal `<img>`; this
 * component decides which of the two to render.
 */
export function OptimizedImage({
  src,
  srcSet,
  width,
  height,
  alt,
  sizes,
  ...rest
}: Omit<ComponentProps<"img">, "src"> & { src?: string | StaticImageData }) {
  // Intrinsic size comes from the static-import object when the call site passed
  // one, otherwise from the manifest for a string `src`.
  const intrinsic =
    src && typeof src === "object"
      ? { w: src.width, h: src.height }
      : typeof src === "string"
        ? DIMS[src]
        : undefined;

  const { w, h } = resolveDimensions(intrinsic, width, height);

  // Static imports always carry their dimensions → always optimized.
  if (src && typeof src === "object") {
    return (
      <Image
        {...rest}
        src={src}
        width={w}
        height={h}
        sizes={sizes}
        quality={90}
        alt={alt ?? ""}
      />
    );
  }

  // String srcs: optimize local raster images we have dimensions for; SVGs and
  // dynamic/remote sources fall through to the plain <img> below.
  if (typeof src === "string" && !src.endsWith(".svg") && w && h) {
    return (
      <Image
        {...rest}
        src={src}
        width={w}
        height={h}
        sizes={sizes}
        quality={90}
        alt={alt ?? ""}
      />
    );
  }

  return (
    // eslint-disable-next-line @next/next/no-img-element
    <img
      {...rest}
      src={src}
      srcSet={srcSet}
      width={width}
      height={height}
      sizes={sizes}
      alt={alt ?? ""}
    />
  );
}
