/** Section 4 of /product/app-security. Generated by the Webflow Cloner agent. */
export function ProductAppSecuritySection4() {
  return (
    <section id="Testimonial" className="section_v2 split_background _40eg_smoke">
      <div className="pr-(--sizing--rem--2rem) pl-(--sizing--rem--2rem) ml-auto mr-auto relative max-portrait:pr-(--sizing--rem--1-25rem) max-portrait:pl-(--sizing--rem--1-25rem)">
        <div className="w-full max-w-300 ml-auto mr-auto">
          <div className="pullquote-container">
            <div className="container-flex align-top">
              <div className="slant-label pullquote tint_50bw">
                <div className="eyebrow-large whitespace-nowrap max-portrait:whitespace-nowrap">
                  Client Testimonial
                </div>
              </div>
              <div className="shape-triangle tint_50bw w-embed">
                <svg version="1.1" baseProfile="basic" id="Triangle" xmlns="http://www.w3.org/2000/svg" xmlnsXlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 34 38" xmlSpace="preserve">
                  <path fill="currentColor" d="M0,0l34,38H0V0z"></path>
                </svg>
              </div>
            </div>
            <div className="pullquote-content tint_50bw">
              <div className="container-flex pullquote_container">
                <div className="pullquote-img-container tint_75mint">
                  <img width="215" loading="lazy" alt="" src="/assets/adam-cropped-mono-img.webp" sizes="(max-width: 479px) 100vw, 215px" srcSet="/assets/adam-cropped-mono-img-p-500.webp 500w, /assets/adam-cropped-mono-img.webp 600w" className="pullquote-img" />
                </div>
                <div className="container-flex pullquote_right">
                  <div className="pullquote-text hanging_quote">
                    “
                  </div>
                  <div className="container-flex vertical">
                    <div className="pullquote-text">
                      Mycroft's 5-in-1 platform seamlessly consolidated our entire security stack, eliminating the need for multiple point solutions and endless checklists.”
                    </div>
                    <div className="pullquote-name">
                      Adam Cohen
                    </div>
                    <div className="pullquote-title">
                      CEO of WEAVE
                    </div>
                    <img width="114" loading="lazy" alt="" src="/assets/weave-logo.svg" />
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
