import type { Metadata } from "next";
import { ProductSnapshot } from "./_snapshot/ProductSnapshot";
import { WebflowInteractions } from "../_shared/WebflowInteractions";

export const metadata: Metadata = {
  title: "Mycroft Product | A fully integrated Security stack",
  description: "Learn more about Mycroft’s automated platform and how our robust stack of security products will save precious engineering time.",
  openGraph: {
    title: "Mycroft Product | A fully integrated Security stack",
    description: "Learn more about Mycroft’s automated platform and how our robust stack of security products will save precious engineering time.",
    type: "website",
    images: ["/assets/mycroft-meta-img-product.webp"],
  },
  twitter: {
    card: "summary_large_image",
    title: "Mycroft Product | A fully integrated Security stack",
    description: "Learn more about Mycroft’s automated platform and how our robust stack of security products will save precious engineering time.",
    images: ["/assets/mycroft-meta-img-product.webp"],
  },
};

/**
 * /product: a faithful React rebuild of the Webflow page.
 * Generated by the Webflow Cloner agent from https://www.mycroft.io/product.
 */
export default function ProductPage() {
  return (
    <>
      <ProductSnapshot />
      <WebflowInteractions />
    </>
  );
}
