import { CtaSection } from "@/app/_shared/CtaSection";
import { SiteNav } from "../../../_shared/SiteNav";
import { SiteFooter } from "../../../_shared/SiteFooter";
import { FrameworksFedrampSection1 } from "./FrameworksFedrampSection1";
import { FrameworksFedrampSection2 } from "./FrameworksFedrampSection2";
import { FrameworksFedrampSection3 } from "./FrameworksFedrampSection3";
import { FrameworksFedrampSection4 } from "./FrameworksFedrampSection4";
import { FrameworksFedrampSection5 } from "./FrameworksFedrampSection5";
import { UnlockFrameworksSection } from "@/app/_shared/UnlockFrameworksSection";

/**
 * Faithful React port of the Webflow https://mycroft.io/frameworks/fedramp page. DOM + classes mirror
 * the original 1:1; global styling is in webflow-shared.css, page CSS
 * in frameworks-fedramp.css. Generated by the Webflow Cloner agent.
 */
export function FrameworksFedrampSnapshot() {
  return (
    <div className="page-wrapper u-minh-100vh color_rg">
      <div className="styles__global-embed-code w-embed"></div>
      <SiteNav />
      <main id="main" className="page-content">
        <FrameworksFedrampSection1 />
        <FrameworksFedrampSection2 />
        <FrameworksFedrampSection3 />
        <FrameworksFedrampSection4 />
        <UnlockFrameworksSection
          blurb="Achieve FedRAMP compliance with Mycroft and take advantage of the head start gained in other industry frameworks."
          dials={[
            { href: "/frameworks/cmmc", label: "CMMC", lottie: "/lottie/6a024debf8f4c2f14b879e15_Compliance-Dial_60.json" },
            { href: "/frameworks/iso27001", label: "ISO 27001", lottie: "/lottie/6a024deb018a84831eff1a49_Compliance-Dial_25.json" },
            { href: "/frameworks/soc2", label: "SOC 2", lottie: "/lottie/6a024deb1effe22026547e2f_Compliance-Dial_15.json" },
          ]}
        />
        <FrameworksFedrampSection5 />
        <CtaSection variant="lamp" />
      </main>
      <SiteFooter />
    </div>
  );
}
