import { ArrowTextLink } from "@/app/_shared/ArrowTextLink";

/** Section 2 of /frameworks/fedramp. Generated by the Webflow Cloner agent. */
export function FrameworksFedrampSection2() {
  return (
    <section id="fw-features" className="section_v2 tint_60eg overflow_hidden">
      <div className="page-padding">
        <div className="container-small fw_features_hed">
          <div className="padding-top large">
            <div className="container-flex vertical">
              <div className="eyebrow-label-small product">
                <div className="eyebrow-small color_rg">
                  Features
                </div>
              </div>
              <h2 className="h2_v2 color_rg text_center">
                Mycroft’s AI platform solutions for FedRAMP
              </h2>
              <div className="padding-top xxs">
                <div className="text-dek-l text_center">
                  A unified platform designed to operationalize FedRAMP requirements without adding internal workload.
                </div>
              </div>
            </div>
          </div>
        </div>
        <div className="container-large">
          <div className="padding-top medium">
            <div className="padding-btm large">
              <div className="product-container">
                <section id="app-security" className="product-feature">
                  <div className="product-text wf-reveal" style={{"willChange": "opacity, transform", "opacity": "0", "transform": "translate3d(-100px, 0px, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg)", "transformStyle": "preserve-3d", "--wf-op-dur": "1000ms", "--wf-op-delay": "0ms", "--wf-op-ease": "cubic-bezier(0.165,0.84,0.44,1)", "--wf-tr-dur": "1000ms", "--wf-tr-delay": "0ms", "--wf-tr-ease": "cubic-bezier(0.165,0.84,0.44,1)"}}>
                    <h4 className="h4_v2 color_rg">
                      Third party risk management
                    </h4>
                    <div className="body-text-medium">
                      Manage third-party vendor risk assessments, documentation, and ongoing monitoring through a centralized platform built to improve visibility and reduce risk exposure.
                    </div>
                    <ArrowTextLink href="/demo">
                      Book a demo
                    </ArrowTextLink>
                  </div>
                  <div className="product-feature-img wf-reveal" style={{"willChange": "opacity, transform", "opacity": "0", "transform": "translate3d(100px, 0px, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg)", "transformStyle": "preserve-3d", "--wf-op-dur": "1000ms", "--wf-op-delay": "0ms", "--wf-op-ease": "cubic-bezier(0.165,0.84,0.44,1)", "--wf-tr-dur": "1000ms", "--wf-tr-delay": "0ms", "--wf-tr-ease": "cubic-bezier(0.165,0.84,0.44,1)"}}>
                    <img src="/assets/tprm.webp" loading="lazy" width="680" sizes="(max-width: 479px) 100vw, 680px" alt="" srcSet="/assets/tprm-p-500.webp 500w, /assets/tprm-p-800.webp 800w, /assets/tprm-p-1080.webp 1080w, /assets/tprm.webp 1360w" className="fw-features-img" />
                  </div>
                </section>
                <section id="threat-management" className="product-feature even-child">
                  <div className="product-feature-img img-left wf-reveal" style={{"willChange": "opacity, transform", "opacity": "0", "transform": "translate3d(-100px, 0px, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg)", "transformStyle": "preserve-3d", "--wf-op-dur": "1000ms", "--wf-op-delay": "0ms", "--wf-op-ease": "cubic-bezier(0.165,0.84,0.44,1)", "--wf-tr-dur": "1000ms", "--wf-tr-delay": "0ms", "--wf-tr-ease": "cubic-bezier(0.165,0.84,0.44,1)"}}>
                    <img src="/assets/policy-center.webp" loading="lazy" width="680" sizes="(max-width: 479px) 100vw, 680px" alt="" srcSet="/assets/policy-center-p-500.webp 500w, /assets/policy-center-p-800.webp 800w, /assets/policy-center-p-1080.webp 1080w, /assets/policy-center.webp 1360w" className="fw-features-img" />
                  </div>
                  <div className="product-text text-right wf-reveal" style={{"willChange": "opacity, transform", "opacity": "0", "transform": "translate3d(100px, 0px, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg)", "transformStyle": "preserve-3d", "--wf-op-dur": "1000ms", "--wf-op-delay": "0ms", "--wf-op-ease": "cubic-bezier(0.165,0.84,0.44,1)", "--wf-tr-dur": "1000ms", "--wf-tr-delay": "0ms", "--wf-tr-ease": "cubic-bezier(0.165,0.84,0.44,1)"}}>
                    <h4 className="h4_v2 color_rg">
                      Policy center
                    </h4>
                    <div className="body-text-medium">
                      Centralize policies, approvals, procedures, and compliance documentation in one secure location with version control and employee acknowledgment tracking.
                    </div>
                    <ArrowTextLink href="/demo">
                      Book a demo
                    </ArrowTextLink>
                  </div>
                </section>
                <section id="agentic-ai" className="product-feature last-child">
                  <div className="product-text wf-reveal" style={{"willChange": "opacity, transform", "opacity": "0", "transform": "translate3d(-100px, 0px, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg)", "transformStyle": "preserve-3d", "--wf-op-dur": "1000ms", "--wf-op-delay": "0ms", "--wf-op-ease": "cubic-bezier(0.165,0.84,0.44,1)", "--wf-tr-dur": "1000ms", "--wf-tr-delay": "0ms", "--wf-tr-ease": "cubic-bezier(0.165,0.84,0.44,1)"}}>
                    <h4 className="h4_v2 color_rg">
                      Security questionnaires
                    </h4>
                    <div className="body-text-medium">
                      Streamline customer and vendor security questionnaire responses with centralized documentation, reusable answers, and faster collaboration across teams.
                    </div>
                    <ArrowTextLink href="/demo">
                      Book a demo
                    </ArrowTextLink>
                  </div>
                  <div className="product-feature-img wf-reveal" style={{"willChange": "opacity, transform", "opacity": "0", "transform": "translate3d(100px, 0px, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg)", "transformStyle": "preserve-3d", "--wf-op-dur": "1000ms", "--wf-op-delay": "0ms", "--wf-op-ease": "cubic-bezier(0.165,0.84,0.44,1)", "--wf-tr-dur": "1000ms", "--wf-tr-delay": "0ms", "--wf-tr-ease": "cubic-bezier(0.165,0.84,0.44,1)"}}>
                    <img src="/assets/security-questionnaires.webp" loading="lazy" width="680" sizes="(max-width: 479px) 100vw, 680px" alt="" srcSet="/assets/security-questionnaires-p-500.webp 500w, /assets/security-questionnaires-p-800.webp 800w, /assets/security-questionnaires-p-1080.webp 1080w, /assets/security-questionnaires.webp 1360w" className="fw-features-img" />
                  </div>
                </section>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
