import { CtaSection } from "@/app/_shared/CtaSection";
import { SiteNav } from "../../../_shared/SiteNav";
import { SiteFooter } from "../../../_shared/SiteFooter";
import { FrameworksGdprSection1 } from "./FrameworksGdprSection1";
import { FrameworksGdprSection2 } from "./FrameworksGdprSection2";
import { FrameworksGdprSection3 } from "./FrameworksGdprSection3";
import { FrameworksGdprSection4 } from "./FrameworksGdprSection4";
import { FrameworksGdprSection5 } from "./FrameworksGdprSection5";
import { UnlockFrameworksSection } from "@/app/_shared/UnlockFrameworksSection";

/**
 * Faithful React port of the Webflow https://mycroft.io/frameworks/gdpr page. DOM + classes mirror
 * the original 1:1; global styling is in webflow-shared.css, page CSS
 * in frameworks-gdpr.css. Generated by the Webflow Cloner agent.
 */
export function FrameworksGdprSnapshot() {
  return (
    <div className="page-wrapper u-minh-100vh color_rg">
      <div className="styles__global-embed-code w-embed"></div>
      <SiteNav />
      <main id="main" className="page-content">
        <FrameworksGdprSection1 />
        <FrameworksGdprSection2 />
        <FrameworksGdprSection3 />
        <FrameworksGdprSection4 />
        <UnlockFrameworksSection
          blurb="Achieve GDPR compliance with Mycroft and take advantage of the head start gained in other industry frameworks."
          dials={[
            { href: "/frameworks/iso27001", label: "ISO 27001", lottie: "/lottie/6a024debde8e8bdd03fd4005_Compliance-Dial_75.json" },
            { href: "/frameworks/soc2", label: "SOC 2", lottie: "/lottie/6a024debb2691dc79f35fad4_Compliance-Dial_50.json" },
            { href: "/frameworks/cmmc", label: "CMMC", lottie: "/lottie/6a024deb827e31fd875d4056_Compliance-Dial_40.json" },
          ]}
        />
        <FrameworksGdprSection5 />
        <CtaSection variant="fireplace" />
      </main>
      <SiteFooter />
    </div>
  );
}
