/** Section 3 of /frameworks/gdpr. Generated by the Webflow Cloner agent. */
export function FrameworksGdprSection3() {
  return (
    <section className="section_v2 tint_60eg overflow_hidden">
      <div className="page-padding">
        <div className="container-small">
          <div className="container-flex vertical center text_center gap_xs">
            <h3 className="h3_v2 color_rg">
              Additional features for GDPR
            </h3>
            <div className="text-dek-s max_44rem">
              Mycroft’s Risk Operations Center provides integrated capabilities to manage privacy, security, and compliance at scale.
            </div>
          </div>
        </div>
        <div className="container-large">
          <div style={{"opacity": "0"}} className="w-layout-grid fw-features-grid">
            <div className="fw-grid-tile">
              <h6 className="h6 color_mint">
                AI policy generator
              </h6>
              <div className="body-text-small color_mint">
                Produce and iterate clear, auditable policy documents
              </div>
            </div>
            <div className="fw-grid-tile">
              <h6 className="h6 color_mint">
                App security
              </h6>
              <div className="body-text-small color_mint">
                Secure application code and runtime
              </div>
            </div>
            <div className="fw-grid-tile">
              <h6 className="h6 color_mint">
                Risk insight reports
              </h6>
              <div className="body-text-small color_mint">
                Delivers reports prioritizing risks, actioned by Mycroft Agents
              </div>
            </div>
            <div className="fw-grid-tile">
              <h6 className="h6 color_mint">
                Custom controls
              </h6>
              <div className="body-text-small color_mint">
                Create controls and tests tailored to your journey
              </div>
            </div>
            <div className="fw-grid-tile">
              <h6 className="h6 color_mint">
                Security questionnaires
              </h6>
              <div className="body-text-small color_mint">
                Streamline vendor security assessments
              </div>
            </div>
            <div className="fw-grid-tile">
              <h6 className="h6 color_mint">
                Support and live chat
              </h6>
              <div className="body-text-small color_mint">
                Real-time assistance for security issues
              </div>
            </div>
            <div className="fw-grid-tile">
              <h6 className="h6 color_mint">
                Automatic evidence collection
              </h6>
              <div className="body-text-small color_mint">
                Gathers and stores evidence
              </div>
            </div>
            <div className="fw-grid-tile">
              <h6 className="h6 color_mint">
                Security training
              </h6>
              <div className="body-text-small color_mint">
                Interactive employee cybersecurity
                <br />
                education
              </div>
            </div>
            <div id="w-node-_4afd8643-4fd1-646b-2573-ed51cc410131-0667ae30" className="fw-grid-tile odd_last_child">
              <h6 className="h6 color_mint">
                Policy center
              </h6>
              <div className="body-text-small color_mint">
                Centralized, versioned compliance
                <br />
                policies
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
