import { FaqItem } from "@/app/_shared/Accordion";

/** Section 5 of /frameworks/gdpr. Generated by the Webflow Cloner agent. */
export function FrameworksGdprSection5() {
  return (
    <section className="section_v2 color_smoke">
      <div className="page-padding">
        <div className="container-medium">
          <div className="padding-top medium">
            <div className="padding-btm large">
              <img src="/assets/faq-notchlabel-desktop.svg" loading="lazy" alt="" className="faq-notch-desktop" />
              <img src="/assets/faq-notchlabel-mobile.svg" loading="lazy" alt="" className="faq-notch-mobile" />
              <div className="container-flex faq_container">
                <div className="faq-hed-flex">
                  <h3 className="h3_v2 color_white">
                    Frequently asked questions
                  </h3>
                  <div className="text-dek-l text_40eg">
                    Answers that help customers with GDPR compliance
                  </div>
                </div>
                <FaqItem question="What is GDPR?" first>
                  GDPR (General Data Protection Regulation) is a European Union law that governs how organizations collect, use, and protect personal data of EU residents.
                </FaqItem>
                <FaqItem question="Who needs to comply with GDPR?">
                  Any organization that processes personal data of individuals in the EU, regardless of where the company is located.
                </FaqItem>
                <FaqItem question="What are the key requirements of GDPR?">
                  GDPR requires lawful data processing, clear consent, data subject rights management, data protection by design, and strong security measures.
                </FaqItem>
                <FaqItem question="What are data subject rights under GDPR?">
                  Individuals have the right to access, correct, delete, and transfer their personal data, as well as restrict or object to its processing.
                </FaqItem>
                <FaqItem question="What are the penalties for non-compliance?">
                  GDPR fines can reach up to €20 million or 4% of global annual revenue, whichever is higher.
                </FaqItem>
                <FaqItem question="How long does it take to become GDPR compliant?">
                  Timelines vary based on your current data practices, but most organizations require several months to fully operationalize compliance.
                </FaqItem>
                <FaqItem question="How does Mycroft help with GDPR?" last>
                  Mycroft helps you manage data mapping, consent, policies, and data subject requests while automating evidence collection so your team stays compliant without added operational burden.
                </FaqItem>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
