import Link from "next/link";

/** Section 1 of /frameworks/gdpr. Generated by the Webflow Cloner agent. */
export function FrameworksGdprSection1() {
  return (
    <section id="fw-hero" className="section-hero white_background">
      <div className="page-padding">
        <div className="container-large">
          <div className="container-flex fw_hero">
            <div className="container-flex vertical fw_hero_left">
              <div className="eyebrow-label-medium">
                <div className="eyebrow-medium color_rg">
                  Compliance
                </div>
              </div>
              <div className="hero-copy hero_padding_med">
                <h1 className="h3_v2 color_rg">
                  GDPR compliance, built for real-world execution
                </h1>
                <div className="text-dek-m">
                  Mycroft’s Risk Operations Center removes the operational burden, helping you achieve and maintain GDPR compliance with confidence.
                </div>
              </div>
              <div className="padding-top xxs">
                <div className="container-flex center_mobile">
                  <Link href="/demo" className="btn-large w-inline-block">
                    <div className="btn-text-large">
                      Book a demo
                    </div>
                    <img src="/assets/arrow-icon-v2.svg" loading="lazy" style={{"transform": "translate3d(0px, 0px, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg)", "transformStyle": "preserve-3d"}} alt="" className="btn-arrow-large" />
                    <div style={{"transform": "translate3d(-100%, 0px, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg)", "transformStyle": "preserve-3d"}} className="hero-btn-shine"></div>
                  </Link>
                </div>
              </div>
            </div>
            <div className="fw-hero-circle">
              <img src="/assets/gdpr-badge-2.svg" loading="lazy" alt="" className="fw-hero-badge-img" style={{"willChange": "transform", "transform": "translate3d(8px, 8px, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg)", "transformStyle": "preserve-3d"}} />
              <div className="fw-hero-dots" style={{"willChange": "transform", "transform": "translate3d(-4px, -4px, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg)", "transformStyle": "preserve-3d"}}></div>
            </div>
          </div>
        </div>
      </div>
      <div className="split-background">
        <div className="page-padding">
          <div className="container-xl compliance_features">
            <div className="container-small">
              <div className="padding-top large">
                <div className="padding-btm small">
                  <div className="container-flex vertical center">
                    <div className="padding-btm xsmall">
                      <div className="container-flex vertical center text_center">
                        <h3 className="h3_v2 color_white">
                          Why GDPR matters to you
                        </h3>
                        <div className="padding-top xxs">
                          <div className="text-dek-m color_40eg">
                            GDPR compliance demonstrates your commitment to data privacy, reduces regulatory risk, and enables you to operate confidently in global markets.
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div className="container-large">
              <div className="w-layout-grid features-3up frameworks">
                <div className="feature-item frameworks" style={{"opacity": "0"}}>
                  <img src="/assets/warning-icon.svg" loading="lazy" width="38" alt="" className="feature-icon" />
                  <div className="container-flex vertical center text_center">
                    <div className="h6 color_mint">
                      Regulatory and financial risk
                    </div>
                    <div className="padding-top xxxs">
                      <div className="body-text-small color_mint smaller">
                        GDPR violations can result in fines of up to 4% of global annual revenue. Strong compliance reduces exposure and protects your business.
                      </div>
                    </div>
                  </div>
                </div>
                <div className="feature-item frameworks" style={{"opacity": "0"}}>
                  <img src="/assets/checkmark-icon.svg" loading="lazy" width="38" alt="" className="feature-icon" />
                  <div className="container-flex vertical center text_center">
                    <div className="h6 color_mint">
                      Customer trust and data protection
                    </div>
                    <div className="padding-top xxxs">
                      <div className="body-text-small color_mint smaller">
                        Customers expect transparency and control over their data. GDPR compliance strengthens trust and supports enterprise sales.
                      </div>
                    </div>
                  </div>
                </div>
                <div className="feature-item frameworks" style={{"opacity": "0"}}>
                  <img src="/assets/markets-icon.svg" loading="lazy" width="38" alt="" className="feature-icon" />
                  <div className="container-flex vertical center text_center">
                    <div className="h6 color_mint">
                      Global market access
                    </div>
                    <div className="padding-top xxxs">
                      <div className="body-text-small color_mint smaller">
                        GDPR is the standard for handling EU data. Compliance enables expansion into European markets and partnerships.
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div className="padding-btm xsmall">
                <div className="container-flex vertical center">
                  <Link href="/demo" className="btn-large w-inline-block">
                    <div className="btn-text-large">
                      Book a demo
                    </div>
                    <img src="/assets/arrow-icon-v2.svg" loading="lazy" style={{"transform": "translate3d(0px, 0px, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg)", "transformStyle": "preserve-3d"}} alt="" className="btn-arrow-large" />
                    <div style={{"transform": "translate3d(-100%, 0px, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg)", "transformStyle": "preserve-3d"}} className="hero-btn-shine"></div>
                  </Link>
                </div>
              </div>
            </div>
          </div>
          <div className="btm-tab narrower">
            <div className="shape-triangle color_rg flipped mirrored smaller_mobile w-embed">
              <svg version="1.1" baseProfile="basic" id="Triangle" xmlns="http://www.w3.org/2000/svg" xmlnsXlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 34 38" xmlSpace="preserve">
                <path fill="currentColor" d="M0,0l34,38H0V0z"></path>
              </svg>
            </div>
            <div className="tab-filler color_rg"></div>
            <div className="shape-triangle color_rg flipped smaller_mobile w-embed">
              <svg version="1.1" baseProfile="basic" id="Triangle" xmlns="http://www.w3.org/2000/svg" xmlnsXlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 34 38" xmlSpace="preserve">
                <path fill="currentColor" d="M0,0l34,38H0V0z"></path>
              </svg>
            </div>
          </div>
        </div>
      </div>
      <div className="hero-background fw_grid"></div>
      <div className="hero-background cs_noise"></div>
    </section>
  );
}
