import type { Metadata } from "next";
import { SubscribeSnapshot } from "./_snapshot/SubscribeSnapshot";
import { WebflowInteractions } from "../_shared/WebflowInteractions";

export const metadata: Metadata = {
  title: "Subscribe",
  description: "Subscribe to read in depth industry updates, deep dives, and Mike’s thoughts",
  openGraph: {
    title: "Subscribe",
    description: "Subscribe to read in depth industry updates, deep dives, and Mike’s thoughts",
    type: "website",
    images: ["/assets/mycroft-meta-img-subscribe.webp"],
  },
  twitter: {
    card: "summary_large_image",
    title: "Subscribe",
    description: "Subscribe to read in depth industry updates, deep dives, and Mike’s thoughts",
    images: ["/assets/mycroft-meta-img-subscribe.webp"],
  },
};

/**
 * /subscribe: a faithful React rebuild of the Webflow page.
 * Generated by the Webflow Cloner agent from https://www.mycroft.io/subscribe.
 */
export default function SubscribePage() {
  return (
    <>
      <SubscribeSnapshot />
      <WebflowInteractions />
    </>
  );
}
