import type { Metadata } from "next";
import "./privacy.css";
import { PrivacySnapshot } from "./_snapshot/PrivacySnapshot";
import { WebflowInteractions } from "../_shared/WebflowInteractions";

export const metadata: Metadata = {
  title: "Mycroft Privacy Policy | Our privacy policy details how we collect, use, and share information",
  description: "Mycroft is committed to protecting your privacy.",
  openGraph: {
    title: "Mycroft Privacy Policy | Our privacy policy details how we collect, use, and share information",
    description: "Mycroft is committed to protecting your privacy.",
    type: "website",
    images: ["/assets/mycroft-meta-img-privacy.webp"],
  },
  twitter: {
    card: "summary_large_image",
    title: "Mycroft Privacy Policy | Our privacy policy details how we collect, use, and share information",
    description: "Mycroft is committed to protecting your privacy.",
    images: ["/assets/mycroft-meta-img-privacy.webp"],
  },
};

/**
 * /privacy: a faithful React rebuild of the Webflow page.
 * Generated by the Webflow Cloner agent from https://www.mycroft.io/privacy.
 */
export default function PrivacyPage() {
  return (
    <>
      <PrivacySnapshot />
      <WebflowInteractions />
    </>
  );
}
