import { SiteNav } from "../../_shared/SiteNav";
import { SiteFooter } from "../../_shared/SiteFooter";
import { ComplianceSection } from "../../_shared/ComplianceSection";

/**
 * Faithful React port of the Webflow https://www.mycroft.io/thank-you page. DOM + classes mirror
 * the original 1:1; global styling is in webflow-shared.css, page CSS
 * in thank-you.css. Generated by the Webflow Cloner agent.
 */
export function ThankYouSnapshot() {
  return (
    <div className="page-wrapper u-minh-100vh">
      <div className="styles__global-embed-code w-embed"></div>
      <SiteNav />
      <main id="main" className="page-main nav_v2">
        <header style={{"transform": "translate3d(0px, 0px, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg)", "opacity": "1", "transformStyle": "preserve-3d"}} className="section u-bg-wallpaper nav_v2">
          <div className="w-layout-blockcontainer wf-container w-container">
            <div className="row row-justify-center">
              <div className="col u-text-center">
                <img src="/assets/chair.webp" loading="lazy" alt="" className="image-6" />
              </div>
            </div>
            <div className="row row-justify-center">
              <div className="col u-text-center">
                <h1 className="h1 u-text-white">
                  Your meeting is confirmed!
                </h1>
                <div className="paragraph-1-5 u-text-white">
                  Thank you for getting in touch.
                </div>
              </div>
            </div>
          </div>
        </header>
        <div className="color-rg">
          <ComplianceSection
            heading="Real enterprise security, compliance next."
            body="We help you navigate SOC 2, PIPEDA, GDPR, HIPAA, CMMC, FedRAMP, FedRAMP 20X and other frameworks that we stay on top of."
          />
        </div>
        <SiteFooter />
      </main>
    </div>
  );
}
