import { CtaSection } from "@/app/_shared/CtaSection";
import { SiteNav } from "../../_shared/SiteNav";
import { SiteFooter } from "../../_shared/SiteFooter";
import { PricingSection1 } from "./PricingSection1";
import { PricingSection2 } from "./PricingSection2";
import { PricingSection3 } from "./PricingSection3";
import { PricingSection4 } from "./PricingSection4";
import { PricingSection5 } from "./PricingSection5";

/**
 * Faithful React port of the Webflow https://www.mycroft.io/pricing page. DOM + classes mirror
 * the original 1:1; global styling is in webflow-shared.css, page CSS
 * in pricing.css. Generated by the Webflow Cloner agent.
 */
export function PricingSnapshot() {
  return (
    <div className="page-wrapper u-minh-100vh">
      <div className="styles__global-embed-code w-embed"></div>
      <SiteNav />
      <main id="main" className="page-content">
        <PricingSection1 />
        <PricingSection2 />
        <PricingSection3 />
        <PricingSection4 />
        <PricingSection5 />
        <CtaSection variant="fireplace" />
      </main>
      <SiteFooter />
    </div>
  );
}
