/** Section 5 of /pricing. Generated by the Webflow Cloner agent. */
export function PricingSection5() {
  return (
    <section id="Features" className="section_v2 color_sand">
      <div className="page-padding">
        <div className="padding-top xl features_small">
          <div className="container-xl">
            <div className="container-xs">
              <div className="container-flex vertical">
                <h3 className="h3_v2 color_rg text_center">
                  Skip the security grind
                </h3>
                <div className="padding-top xxxs">
                  <div className="text-dek-s text_center">
                    Mycroft eliminates the need for multiple solutions, everything you need is included.
                  </div>
                </div>
              </div>
            </div>
            <div className="padding-top medium">
              <div className="padding-btm xxxl features_small">
                <div className="container-flex space-between features">
                  <div className="features-grid">
                    <div id="w-node-_48b25d80-04a3-27e0-e07e-21aa47342e3f-521846c2" className="feature-tile-small-container wf-reveal" style={{"transform": "translate3d(0px, 50px, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg)", "transformStyle": "preserve-3d", "opacity": "0", "--wf-op-dur": "1000ms", "--wf-op-delay": "0ms", "--wf-op-ease": "cubic-bezier(0.165,0.84,0.44,1)", "--wf-tr-dur": "1000ms", "--wf-tr-delay": "0ms", "--wf-tr-ease": "cubic-bezier(0.165,0.84,0.44,1)"}}>
                      <div className="container-flex">
                        <div className="slant-label-small">
                          <div className="eyebrow-small small_feature">
                            PRIVACY & SECURITY
                          </div>
                        </div>
                        <img src="/assets/triangle-shape.svg" loading="lazy" alt="" className="triangle-shape small_feature" />
                      </div>
                      <div className="feature-tile-content-small">
                        <img src="/assets/mycroft-features1-v2.webp" loading="lazy" width="512" sizes="(max-width: 479px) 100vw, 512px" alt="" srcSet="/assets/mycroft-features1-v2-p-500.webp 500w, /assets/mycroft-features1-v2-p-800.webp 800w, /assets/mycroft-features1-v2.webp 1024w" className="feature-tile-img" />
                        <div className="feature-small-tile-label">
                          <img src="/assets/crest-icon.svg" loading="lazy" alt="" className="feature-tile-icon small_feature" />
                          <h6 className="h6 small_feature">
                            <strong>
                              No performative security
                            </strong>
                            <br />
                          </h6>
                        </div>
                        <div className="body-text-large small_feature">
                          No more security theater. Enhance your security and compliance posture to enterprise requirements with all the solutions you need – from your laptops to your policies.
                          <br />
                        </div>
                      </div>
                    </div>
                    <div className="feature-tile-small-container wf-reveal" style={{"transform": "translate3d(0px, 50px, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg)", "transformStyle": "preserve-3d", "opacity": "0", "--wf-op-dur": "1000ms", "--wf-op-delay": "0ms", "--wf-op-ease": "cubic-bezier(0.165,0.84,0.44,1)", "--wf-tr-dur": "1000ms", "--wf-tr-delay": "0ms", "--wf-tr-ease": "cubic-bezier(0.165,0.84,0.44,1)"}}>
                      <div className="container-flex">
                        <div className="slant-label-small">
                          <div className="eyebrow-small small_feature">
                            ARTIFICIAL INTELLIGENCE
                          </div>
                        </div>
                        <img src="/assets/triangle-shape.svg" loading="lazy" alt="" className="triangle-shape small_feature" />
                      </div>
                      <div className="feature-tile-content-small">
                        <img src="/assets/mycroft-features2-v1.webp" loading="lazy" width="512" sizes="(max-width: 479px) 100vw, 512px" alt="" srcSet="/assets/mycroft-features2-v1-p-500.webp 500w, /assets/mycroft-features2-v1-p-800.webp 800w, /assets/mycroft-features2-v1.webp 1024w" className="feature-tile-img" />
                        <div className="feature-small-tile-label">
                          <img src="/assets/gear-icon.svg" loading="lazy" alt="" className="feature-tile-icon small_feature" />
                          <h6 className="h6 small_feature">
                            Autonomous compliance
                          </h6>
                        </div>
                        <div className="body-text-large small_feature">
                          With Mycroft’s AI Agents, your security and compliance programs are managed autonomously — leveraging your integrations to respond, automate and scale seamlessly.
                          <br />
                        </div>
                      </div>
                    </div>
                    <div className="feature-tile-small-container wf-reveal" style={{"transform": "translate3d(0px, 50px, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg)", "transformStyle": "preserve-3d", "opacity": "0", "--wf-op-dur": "1000ms", "--wf-op-delay": "0ms", "--wf-op-ease": "cubic-bezier(0.165,0.84,0.44,1)", "--wf-tr-dur": "1000ms", "--wf-tr-delay": "0ms", "--wf-tr-ease": "cubic-bezier(0.165,0.84,0.44,1)"}}>
                      <div className="container-flex">
                        <div className="slant-label-small">
                          <div className="eyebrow-small small_feature">
                            MANAGED REMEDIATIONS
                          </div>
                        </div>
                        <img src="/assets/triangle-shape.svg" loading="lazy" alt="" className="triangle-shape small_feature" />
                      </div>
                      <div className="feature-tile-content-small">
                        <img src="/assets/mycroft-features3-v1.webp" loading="lazy" width="512" sizes="(max-width: 479px) 100vw, 512px" alt="" srcSet="/assets/mycroft-features3-v1-p-500.webp 500w, /assets/mycroft-features3-v1-p-800.webp 800w, /assets/mycroft-features3-v1.webp 1024w" className="feature-tile-img" />
                        <div className="feature-tile-label">
                          <img src="/assets/push-icon.svg" loading="lazy" alt="" className="feature-tile-icon" />
                          <h6 className="h6 small_feature">
                            <strong>
                              Time saved, time gained
                            </strong>
                          </h6>
                        </div>
                        <div className="body-text-large small_feature">
                          Mycroft contextualizes and can automatically remediate issues on your behalf, allowing you to spend your resources more efficiently.
                          <br />
                        </div>
                      </div>
                    </div>
                    <div className="feature-tile-small-container wf-reveal" style={{"transform": "translate3d(0px, 50px, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg)", "transformStyle": "preserve-3d", "opacity": "0", "--wf-op-dur": "1000ms", "--wf-op-delay": "0ms", "--wf-op-ease": "cubic-bezier(0.165,0.84,0.44,1)", "--wf-tr-dur": "1000ms", "--wf-tr-delay": "0ms", "--wf-tr-ease": "cubic-bezier(0.165,0.84,0.44,1)"}}>
                      <div className="container-flex">
                        <div className="slant-label-small">
                          <div className="eyebrow-small small_feature">
                            EXPERT-LED SUPPORT
                          </div>
                        </div>
                        <img src="/assets/triangle-shape.svg" loading="lazy" alt="" className="triangle-shape small_feature" />
                      </div>
                      <div className="feature-tile-content-small">
                        <img src="/assets/mycroft-features4-v1.webp" loading="lazy" width="512" sizes="(max-width: 479px) 100vw, 512px" alt="" srcSet="/assets/mycroft-features4-v1-p-500.webp 500w, /assets/mycroft-features4-v1-p-800.webp 800w, /assets/mycroft-features4-v1.webp 1024w" className="feature-tile-img" />
                        <div className="feature-tile-label">
                          <img src="/assets/star-icon.svg" loading="lazy" alt="" className="feature-tile-icon" />
                          <h6 className="h6 small_feature">
                            Real experts, always here
                          </h6>
                        </div>
                        <div className="body-text-large small_feature">
                          Mycroft's customer success team are made of security and compliance experts, watching your environment 24/7/365, supported by your AI Security and Compliance Officer.
                          <br />
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div className="overlap-top">
        <div className="overlap-block smoke"></div>
        <div className="container-large">
          <div className="overlap-block top_block _50percent smoke"></div>
        </div>
        <div className="overlap-block transparent"></div>
      </div>
    </section>
  );
}
