/** Section 2 of /pricing. Generated by the Webflow Cloner agent. */
export function PricingSection2() {
  return (
    <section id="pricing" className="section_v2 tint_40eg overflow_hidden">
      <div className="page-padding">
        <div className="container-large">
          <div className="padding-top small">
            <div className="padding-top xxxs">
              <div className="padding-btm xl">
                <div className="pricing-grid">
                  <div className="pricing-tile wf-scrub" data-wf-scrub="5,15" style={{"opacity": "0", "transform": "translate3d(50px, 0px, 0px)"}}>
                    <div className="pricing-tile-top">
                      <h5 className="h5 pricing_hed">
                        Platform
                      </h5>
                      <div className="pricing-dek-text _1st_child">
                        Everything you need to achieve and maintain your security and compliance yourself.
                      </div>
                    </div>
                    <div className="pricing-tile-btm">
                      <ul role="list" className="pricing-ul">
                        <li className="pricing-ul-item">
                          <div className="list-item-text">
                            Full GRC Platform for SOC 2, ISO 27001, GDPR, HIPAA, and more
                          </div>
                        </li>
                        <li className="pricing-ul-item">
                          <div className="list-item-text">
                            Cloud Native Application
                            <br />
                            Protection Platform (CNAPP)
                          </div>
                        </li>
                        <li className="pricing-ul-item">
                          <div className="list-item-text">
                            Security/AI/Privacy Awareness Training
                          </div>
                        </li>
                        <li className="pricing-ul-item">
                          <div className="list-item-text">
                            24/7/365 Threat Intelligence and Monitoring
                          </div>
                        </li>
                        <li className="pricing-ul-item">
                          <div className="list-item-text">
                            Trust Center
                          </div>
                        </li>
                        <li className="pricing-ul-item last-child">
                          <div className="list-item-text">
                            Basic Agentic AI workflows
                          </div>
                        </li>
                      </ul>
                      <div className="tile-indent">
                        <div className="indent-shape-triangle tint_40eg y-rotate w-embed">
                          <svg version="1.1" baseProfile="basic" id="Triangle" xmlns="http://www.w3.org/2000/svg" xmlnsXlink="http://www.w3.org/1999/xlink" viewBox="0 0 12 12
   " xmlSpace="preserve">
                            <path fill="currentColor" d="M0,0l34,38H0V0z"></path>
                          </svg>
                        </div>
                        <div className="indent-mid"></div>
                        <div className="indent-shape-triangle tint_40eg w-embed">
                          <svg version="1.1" baseProfile="basic" id="Triangle" xmlns="http://www.w3.org/2000/svg" xmlnsXlink="http://www.w3.org/1999/xlink" viewBox="0 0 12 12
   " xmlSpace="preserve">
                            <path fill="currentColor" d="M0,0l34,38H0V0z"></path>
                          </svg>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div className="pricing-tile wf-scrub" data-wf-scrub="10,20" style={{"opacity": "0", "transform": "translate3d(50px, 0px, 0px)"}}>
                    <div className="pricing-tile-top">
                      <h5 className="h5 pricing_hed">
                        Scale
                      </h5>
                      <div className="pricing-dek-text _2nd_child">
                        For the scaling organization with an expanding security and compliance need.
                      </div>
                    </div>
                    <div className="pricing-tile-btm">
                      <ul role="list" className="pricing-ul">
                        <li className="pricing-ul-item">
                          <div className="list-item-text">
                            Everything in Platform
                          </div>
                        </li>
                        <li className="pricing-ul-item">
                          <div className="list-item-text">
                            Penetration Testing
                          </div>
                        </li>
                        <li className="pricing-ul-item">
                          <div className="list-item-text">
                            Continuous Third-Party Risk Management
                          </div>
                        </li>
                        <li className="pricing-ul-item">
                          <div className="list-item-text">
                            Customer Success Manager
                          </div>
                        </li>
                        <li className="pricing-ul-item last-child">
                          <div className="list-item-text">
                            Expanded Agentic AI workflows
                          </div>
                        </li>
                      </ul>
                      <div className="tile-indent">
                        <div className="indent-shape-triangle tint_40eg y-rotate w-embed">
                          <svg version="1.1" baseProfile="basic" id="Triangle" xmlns="http://www.w3.org/2000/svg" xmlnsXlink="http://www.w3.org/1999/xlink" viewBox="0 0 12 12
   " xmlSpace="preserve">
                            <path fill="currentColor" d="M0,0l34,38H0V0z"></path>
                          </svg>
                        </div>
                        <div className="indent-mid"></div>
                        <div className="indent-shape-triangle tint_40eg w-embed">
                          <svg version="1.1" baseProfile="basic" id="Triangle" xmlns="http://www.w3.org/2000/svg" xmlnsXlink="http://www.w3.org/1999/xlink" viewBox="0 0 12 12
   " xmlSpace="preserve">
                            <path fill="currentColor" d="M0,0l34,38H0V0z"></path>
                          </svg>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div className="pricing-tile wf-scrub" data-wf-scrub="15,25" style={{"opacity": "0", "transform": "translate3d(50px, 0px, 0px)"}}>
                    <div className="pricing-tile-top">
                      <h5 className="h5 pricing_hed">
                        Managed
                      </h5>
                      <div className="pricing-dek-text _3rd-child">
                        Managed program with a dedicated security and compliance expert on-demand.
                      </div>
                    </div>
                    <div className="pricing-tile-btm">
                      <ul role="list" className="pricing-ul">
                        <li className="pricing-ul-item">
                          <div className="list-item-text">
                            Everything included from Scale
                          </div>
                        </li>
                        <li className="pricing-ul-item">
                          <div className="list-item-text">
                            Customized Frameworks
                          </div>
                        </li>
                        <li className="pricing-ul-item">
                          <div className="list-item-text">
                            Dedicated Chief Information Security Officer (CISO) as your Customer Success Manager
                          </div>
                        </li>
                        <li className="pricing-ul-item last-child">
                          <div className="list-item-text">
                            Customized Agentic AI workflows
                          </div>
                        </li>
                      </ul>
                      <div className="tile-indent">
                        <div className="indent-shape-triangle tint_40eg y-rotate w-embed">
                          <svg version="1.1" baseProfile="basic" id="Triangle" xmlns="http://www.w3.org/2000/svg" xmlnsXlink="http://www.w3.org/1999/xlink" viewBox="0 0 12 12
   " xmlSpace="preserve">
                            <path fill="currentColor" d="M0,0l34,38H0V0z"></path>
                          </svg>
                        </div>
                        <div className="indent-mid"></div>
                        <div className="indent-shape-triangle tint_40eg w-embed">
                          <svg version="1.1" baseProfile="basic" id="Triangle" xmlns="http://www.w3.org/2000/svg" xmlnsXlink="http://www.w3.org/1999/xlink" viewBox="0 0 12 12
   " xmlSpace="preserve">
                            <path fill="currentColor" d="M0,0l34,38H0V0z"></path>
                          </svg>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
