import { CtaSection } from "@/app/_shared/CtaSection";
import { SiteNav } from "../../_shared/SiteNav";
import { SiteFooter } from "../../_shared/SiteFooter";
import { IntegrationsSection1 } from "./IntegrationsSection1";
import { IntegrationsSection2 } from "./IntegrationsSection2";

/**
 * Faithful React port of the Webflow https://www.mycroft.io/integrations page. DOM + classes mirror
 * the original 1:1; global styling is in webflow-shared.css, page CSS
 * in integrations.css. Generated by the Webflow Cloner agent.
 */
export function IntegrationsSnapshot() {
  return (
    <div className="page-wrapper u-minh-100vh">
      <div className="styles__global-embed-code w-embed"></div>
      <SiteNav />
      <main id="main" className="page-content">
        <IntegrationsSection1 />
        <IntegrationsSection2 />
        <CtaSection variant="lamp" />
      </main>
      <SiteFooter />
    </div>
  );
}
