/** Section 1 of /integrations. Generated by the Webflow Cloner agent. */
export function IntegrationsSection1() {
  return (
    <section id="hero" className="section-hero">
      <div className="page-padding">
        <div className="container-large">
          <div className="container-flex hero_integrations">
            <div className="col-hero-left text_only">
              <div className="hero-copy">
                <h2 className="h3_v2 color_rg">
                  Integration-led. Built for the modern growing company.
                </h2>
              </div>
            </div>
            <div className="col-hero-right text_only">
              <div className="hero-copy">
                <div className="text-dek-l">
                  Over 250 integrations power Mycroft’s ability to meet you where you work. From AWS, Azure, and GCP to GitHub, GitLab, and Bitbucket—get the visibility and control you need to scale securely.
                  <br />
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div className="cursor-glow blue_background" style={{"willChange": "transform", "transform": "translate3d(0vw, -15.7141%, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg)", "transformStyle": "preserve-3d"}}></div>
      <div className="hero-background color_integrations"></div>
      <div className="hero-background color_overlay_blue"></div>
      <div className="hero-background pattern_pixels"></div>
    </section>
  );
}
