import Link from "next/link";

/** Section 3 of /integrations. Generated by the Webflow Cloner agent. */
export function IntegrationsSection3() {
  return (
    <section id="demo-cta" className="section_v2 color_smoke overflow-hidden">
      <div className="page-padding">
        <div className="container-large">
          <div className="padding-top xl">
            <div className="padding-btm xxl">
              <div className="container-flex space-between cta-custom">
                <div className="col-cta-left">
                  <div className="container-flex vertical mobile-center">
                    <h3 className="h3_v2 color_white">
                      Stop managing tools. Start automating security.
                    </h3>
                    <div className="padding-top xxs">
                      <div className="text-dek-m color_40eg">
                        Mycroft is the only platform that performs the full end-to-end delivery of your entire security and compliance requirements in a single platform powered by its AI Agents. Navigate security and compliance challenges without adding headcount.
                      </div>
                    </div>
                  </div>
                  <Link href="/demo" className="btn-large w-inline-block">
                    <div className="btn-text-large">
                      Get Started
                    </div>
                    <img src="/assets/arrow-icon-v2.svg" loading="lazy" alt="" className="btn-arrow-large" style={{"transform": "translate3d(0px, 0px, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg)", "transformStyle": "preserve-3d"}} />
                    <div className="hero-btn-shine" style={{"transform": "translate3d(-100%, 0px, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg)", "transformStyle": "preserve-3d"}}></div>
                  </Link>
                </div>
                <div className="col-cta-right">
                  <div className="cta-lamp-container">
                    <img src="/assets/lamp2.webp" loading="lazy" width="240" alt="" className="cta-lamp-img" />
                    <img src="/assets/glow2a.webp" loading="lazy" width="240" alt="" className="cta-glow2a-img" />
                    <img src="/assets/glow2a.webp" loading="lazy" width="240" alt="" className="cta-glow2b-img" style={{"opacity": "0"}} />
                  </div>
                  <img src="/assets/chair-v4.webp" loading="lazy" width="398.5" sizes="(max-width: 479px) 100vw, 399px" alt="" srcSet="/assets/chair-v4-p-500.webp 500w, /assets/chair-v4.webp 797w" className="cta-chair-img" />
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div className="cta-background smoke-pattern"></div>
    </section>
  );
}
