/** Section 3 of /about. Generated by the Webflow Cloner agent. */
export function AboutSection3() {
  return (
    <section id="leadership" className="section_v2 tint_75rg">
      <div className="page-padding">
        <div className="container-large">
          <div className="padding-top large">
            <h2 className="h2_v2 color_white text_center">
              Leadership
            </h2>
          </div>
          <div className="padding-btm xxl">
            <div className="founder-grid">
              <div className="founder-tile wf-scrub" data-wf-scrub="5,15" style={{"opacity": "0", "transform": "translate3d(50px, 0px, 0px)"}}>
                <div className="founder-tile-top">
                  <div className="founder-tile-mid">
                    <h6 className="h6 founder_hed">
                      Mike Kim
                    </h6>
                    <div className="eyebrow-small founder_subhed">
                      Co-founder, CEO
                    </div>
                  </div>
                  <img src="/assets/mike-2.webp" loading="lazy" width="280" sizes="(max-width: 479px) 100vw, 280px" alt="" srcSet="/assets/mike-2-p-500.webp 500w, /assets/mike-2-p-800.webp 800w, /assets/mike-2.webp 840w" className="founder-img" />
                </div>
                <div className="founder-tile-btm">
                  <div className="founder-body">
                    With 12+ years in cybersecurity, Mike (CISA) has roots as a practitioner with deep domain experience with a network following success scaling SaaS companies and professional service firms, from pre-seed to F500.
                    <br />
                  </div>
                  <div className="tile-indent">
                    <div className="indent-shape-triangle tint_75rg y-rotate w-embed">
                      <svg version="1.1" baseProfile="basic" id="Triangle" xmlns="http://www.w3.org/2000/svg" xmlnsXlink="http://www.w3.org/1999/xlink" viewBox="0 0 12 12
   " xmlSpace="preserve">
                        <path fill="currentColor" d="M0,0l34,38H0V0z"></path>
                      </svg>
                    </div>
                    <div className="indent-mid tint_75rg"></div>
                    <div className="indent-shape-triangle tint_75rg w-embed">
                      <svg version="1.1" baseProfile="basic" id="Triangle" xmlns="http://www.w3.org/2000/svg" xmlnsXlink="http://www.w3.org/1999/xlink" viewBox="0 0 12 12
   " xmlSpace="preserve">
                        <path fill="currentColor" d="M0,0l34,38H0V0z"></path>
                      </svg>
                    </div>
                  </div>
                </div>
              </div>
              <div className="founder-tile wf-scrub" data-wf-scrub="10,20" style={{"opacity": "0", "transform": "translate3d(50px, 0px, 0px)"}}>
                <div className="founder-tile-top">
                  <div className="founder-tile-mid">
                    <h6 className="h6 founder_hed">
                      Jon Mendes
                    </h6>
                    <div className="eyebrow-small founder_subhed">
                      Co-founder, PRODUCT & DESIGN
                    </div>
                  </div>
                  <img src="/assets/jon-2.webp" loading="lazy" width="280" sizes="(max-width: 479px) 100vw, 280px" alt="" srcSet="/assets/jon-2-p-500.webp 500w, /assets/jon-2-p-800.webp 800w, /assets/jon-2.webp 840w" className="founder-img" />
                </div>
                <div className="founder-tile-btm">
                  <div className="founder-body">
                    Jon has 12+ years of experience as a product and design leader. Formerly a co-founder of PartnerStack (YC S15), he helped scale the partner tech company to over $20M+ ARR to Series B.
                    <br />
                  </div>
                  <div className="tile-indent">
                    <div className="indent-shape-triangle tint_75rg y-rotate w-embed">
                      <svg version="1.1" baseProfile="basic" id="Triangle" xmlns="http://www.w3.org/2000/svg" xmlnsXlink="http://www.w3.org/1999/xlink" viewBox="0 0 12 12
   " xmlSpace="preserve">
                        <path fill="currentColor" d="M0,0l34,38H0V0z"></path>
                      </svg>
                    </div>
                    <div className="indent-mid tint_75rg"></div>
                    <div className="indent-shape-triangle tint_75rg w-embed">
                      <svg version="1.1" baseProfile="basic" id="Triangle" xmlns="http://www.w3.org/2000/svg" xmlnsXlink="http://www.w3.org/1999/xlink" viewBox="0 0 12 12
   " xmlSpace="preserve">
                        <path fill="currentColor" d="M0,0l34,38H0V0z"></path>
                      </svg>
                    </div>
                  </div>
                </div>
              </div>
              <div className="founder-tile wf-scrub" data-wf-scrub="15,25" style={{"opacity": "0", "transform": "translate3d(50px, 0px, 0px)"}}>
                <div className="founder-tile-top">
                  <div className="founder-tile-mid">
                    <h6 className="h6 founder_hed">
                      Jan Jedrasik
                    </h6>
                    <div className="eyebrow-small founder_subhed">
                      Co-founder, Engineering
                    </div>
                  </div>
                  <img src="/assets/jan-2.webp" loading="lazy" width="280" sizes="(max-width: 479px) 100vw, 280px" alt="" srcSet="/assets/jan-2-p-500.webp 500w, /assets/jan-2-p-800.webp 800w, /assets/jan-2.webp 840w" className="founder-img" />
                </div>
                <div className="founder-tile-btm">
                  <div className="founder-body">
                    Jan (CISSP) is an engineering leader with more than seven years of experience in application security/infrastructure. As a CISSP, he leads software architecture, having built out an AI Security Operations Center.
                  </div>
                  <div className="tile-indent">
                    <div className="indent-shape-triangle tint_75rg y-rotate w-embed">
                      <svg version="1.1" baseProfile="basic" id="Triangle" xmlns="http://www.w3.org/2000/svg" xmlnsXlink="http://www.w3.org/1999/xlink" viewBox="0 0 12 12
   " xmlSpace="preserve">
                        <path fill="currentColor" d="M0,0l34,38H0V0z"></path>
                      </svg>
                    </div>
                    <div className="indent-mid tint_75rg"></div>
                    <div className="indent-shape-triangle tint_75rg w-embed">
                      <svg version="1.1" baseProfile="basic" id="Triangle" xmlns="http://www.w3.org/2000/svg" xmlnsXlink="http://www.w3.org/1999/xlink" viewBox="0 0 12 12
   " xmlSpace="preserve">
                        <path fill="currentColor" d="M0,0l34,38H0V0z"></path>
                      </svg>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
