import { SiteNav } from "../../_shared/SiteNav";
import { SiteFooter } from "../../_shared/SiteFooter";
import { AboutSection1 } from "./AboutSection1";
import { AboutSection2 } from "./AboutSection2";
import { AboutSection3 } from "./AboutSection3";
import { AboutSection4 } from "./AboutSection4";
import { AboutSection5 } from "./AboutSection5";

/**
 * Faithful React port of the Webflow https://www.mycroft.io/about page. DOM + classes mirror
 * the original 1:1; global styling is in webflow-shared.css, page CSS
 * in about.css. Generated by the Webflow Cloner agent.
 */
export function AboutSnapshot() {
  return (
    <div className="page-wrapper u-minh-100vh">
      <div className="styles__global-embed-code w-embed"></div>
      <SiteNav />
      <main id="main" className="page-content">
        <AboutSection1 />
        <AboutSection2 />
        <AboutSection3 />
        <AboutSection4 />
        <AboutSection5 />
      </main>
      <SiteFooter />
    </div>
  );
}
