import { CtaSection } from "@/app/_shared/CtaSection";
import { SiteNav } from "../../../_shared/SiteNav";
import { SiteFooter } from "../../../_shared/SiteFooter";
import { FrameworksIso27001Section1 } from "./FrameworksIso27001Section1";
import { FrameworksIso27001Section2 } from "./FrameworksIso27001Section2";
import { FrameworksIso27001Section3 } from "./FrameworksIso27001Section3";
import { FrameworksIso27001Section4 } from "./FrameworksIso27001Section4";
import { FrameworksIso27001Section5 } from "./FrameworksIso27001Section5";
import { UnlockFrameworksSection } from "@/app/_shared/UnlockFrameworksSection";

/**
 * Faithful React port of the Webflow https://mycroft.io/frameworks/iso27001 page. DOM + classes mirror
 * the original 1:1; global styling is in webflow-shared.css, page CSS
 * in frameworks-iso27001.css. Generated by the Webflow Cloner agent.
 */
export function FrameworksIso27001Snapshot() {
  return (
    <div className="page-wrapper u-minh-100vh color_rg">
      <div className="styles__global-embed-code w-embed"></div>
      <SiteNav />
      <main id="main" className="page-content">
        <FrameworksIso27001Section1 />
        <FrameworksIso27001Section2 />
        <FrameworksIso27001Section3 />
        <FrameworksIso27001Section4 />
        <UnlockFrameworksSection
          blurb={
            <>
              Achieve{" "}
              <span className="no-wrap">ISO 27001</span>{" "}
              compliance with Mycroft and take advantage of the head start gained in other industry frameworks.
            </>
          }
          dials={[
            { href: "/frameworks/gdpr", label: "GDPR", lottie: "/lottie/69ebcb579b02affc99069e64_Compliance-Dial_55.json" },
            { href: "/frameworks/soc2", label: "SOC 2", lottie: "/lottie/6a024deb5cd92f1d32fe0c3d_Compliance-Dial_90.json" },
            { href: "/frameworks/fedramp", label: "FedRAMP", lottie: "/lottie/6a024debde8e8bdd03fd3fe5_Compliance-Dial_10.json" },
          ]}
        />
        <FrameworksIso27001Section5 />
        <CtaSection variant="fireplace" />
      </main>
      <SiteFooter />
    </div>
  );
}
