import { CtaSection } from "@/app/_shared/CtaSection";
import { ButtonLarge } from "@/app/_shared/ButtonLarge";
import Link from "next/link";
import { DotLottiePlayer } from "../../../_shared/DotLottiePlayer";
import { SiteNav } from "../../../_shared/SiteNav";
import { SiteFooter } from "../../../_shared/SiteFooter";
import { FrameworksIso27001Section1 } from "./FrameworksIso27001Section1";
import { FrameworksIso27001Section2 } from "./FrameworksIso27001Section2";
import { FrameworksIso27001Section3 } from "./FrameworksIso27001Section3";
import { FrameworksIso27001Section4 } from "./FrameworksIso27001Section4";
import { FrameworksIso27001Section5 } from "./FrameworksIso27001Section5";

/**
 * Faithful React port of the Webflow https://mycroft.io/frameworks/iso27001 page. DOM + classes mirror
 * the original 1:1; global styling is in webflow-shared.css, page CSS
 * in frameworks-iso27001.css. Generated by the Webflow Cloner agent.
 */
export function FrameworksIso27001Snapshot() {
  return (
    <div className="page-wrapper u-minh-100vh color_rg">
      <div className="styles__global-embed-code w-embed"></div>
      <SiteNav />
      <main id="main" className="page-content">
        <FrameworksIso27001Section1 />
        <FrameworksIso27001Section2 />
        <FrameworksIso27001Section3 />
        <FrameworksIso27001Section4 />
        <div className="negative-margin-wrapper reduce_top">
          <section id="Features" className="section_v2 color_smoke">
            <div className="page-padding">
              <div className="padding-top xl">
                <div className="container-medium tab_mob_100">
                  <div className="container-small narrower_desktop">
                    <div className="container-flex vertical">
                      <h2 className="h2_v2 color_white text_center">
                        Unlock other frameworks
                      </h2>
                      <div className="padding-top xxxs">
                        <div className="text-dek-m color_40eg text_center">
                          Achieve{" "}
                          <span className="no-wrap">
                            ISO 27001
                          </span>{" "}
                          compliance with Mycroft and take advantage of the head start gained in other industry frameworks.
                        </div>
                      </div>
                    </div>
                  </div>
                  <div className="padding-top small">
                    <div className="padding-btm large">
                      <div className="container-flex vertical">
                        <div className="w-layout-grid fw-dials-grid">
                          <Link href="/frameworks/gdpr" className="fw-tile-link w-inline-block">
                            <div className="fw-dial-tile">
                              <div className="fw-vertical-hr"></div>
                              <div style={{"opacity": "0"}} className="dial-tile-background"></div>
                              <div style={{"opacity": "0"}} className="dial-tile-stroke"></div>
                              <div data-is-ix2-target="1" className="fw-dial-lottie" data-animation-type="lottie" data-src="/lottie/69ebcb579b02affc99069e64_Compliance-Dial_55.json" data-loop="0" data-direction="1" data-autoplay="0" data-renderer="svg" data-default-duration="0" data-duration="0" data-loading="eager">
                                <DotLottiePlayer src="/lottie/69ebcb579b02affc99069e64_Compliance-Dial_55.json" loop={false} autoplay={false} width={500} height={500} playOnView={750} />
                              </div>
                              <div className="body-text-small color_white font_600 underline fw_dial">
                                GDPR →
                              </div>
                            </div>
                          </Link>
                          <Link href="/frameworks/soc2" className="fw-tile-link w-inline-block">
                            <div className="fw-dial-tile">
                              <div className="fw-vertical-hr"></div>
                              <div style={{"opacity": "0"}} className="dial-tile-background"></div>
                              <div style={{"opacity": "0"}} className="dial-tile-stroke"></div>
                              <div data-is-ix2-target="1" className="fw-dial-lottie" data-animation-type="lottie" data-src="/lottie/6a024deb5cd92f1d32fe0c3d_Compliance-Dial_90.json" data-loop="0" data-direction="1" data-autoplay="0" data-renderer="svg" data-default-duration="0" data-duration="0" data-loading="eager">
                                <DotLottiePlayer src="/lottie/6a024deb5cd92f1d32fe0c3d_Compliance-Dial_90.json" loop={false} autoplay={false} width={500} height={500} playOnView={1250} />
                              </div>
                              <div className="body-text-small color_white font_600 underline fw_dial">
                                SOC 2 →
                              </div>
                            </div>
                          </Link>
                          <Link href="/frameworks/fedramp" className="fw-tile-link w-inline-block">
                            <div className="fw-dial-tile">
                              <div style={{"opacity": "0"}} className="dial-tile-background"></div>
                              <div style={{"opacity": "0"}} className="dial-tile-stroke"></div>
                              <div data-is-ix2-target="1" className="fw-dial-lottie" data-animation-type="lottie" data-src="/lottie/6a024debde8e8bdd03fd3fe5_Compliance-Dial_10.json" data-loop="0" data-direction="1" data-autoplay="0" data-renderer="svg" data-default-duration="0" data-duration="0" data-loading="eager">
                                <DotLottiePlayer src="/lottie/6a024debde8e8bdd03fd3fe5_Compliance-Dial_10.json" loop={false} autoplay={false} width={500} height={500} playOnView={1750} />
                              </div>
                              <div className="body-text-small color_white font_600 underline fw_dial">
                                FedRAMP →
                              </div>
                            </div>
                          </Link>
                        </div>
                        <div className="container-flex vertical center">
                          <div className="padding-top small flex_center">
                            <ButtonLarge href="/demo" shine>
                              Book a demo
                            </ButtonLarge>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </section>
        </div>
        <FrameworksIso27001Section5 />
        <CtaSection variant="fireplace" />
      </main>
      <SiteFooter />
    </div>
  );
}
