import { FaqItem } from "@/app/_shared/Accordion";

/** Section 5 of /frameworks/iso27001. Generated by the Webflow Cloner agent. */
export function FrameworksIso27001Section5() {
  return (
    <section className="section_v2 color_smoke">
      <div className="page-padding">
        <div className="container-medium">
          <div className="padding-top medium">
            <div className="padding-btm large">
              <img src="/assets/faq-notchlabel-desktop.svg" loading="lazy" alt="" className="faq-notch-desktop" />
              <img src="/assets/faq-notchlabel-mobile.svg" loading="lazy" alt="" className="faq-notch-mobile" />
              <div className="container-flex faq_container">
                <div className="faq-hed-flex">
                  <h3 className="h3_v2 color_white">
                    Frequently asked questions
                  </h3>
                  <div className="text-dek-l text_40eg">
                    Answers that help customers with
                    <span className="no-wrap">
                      ISO 27001
                    </span>
                    compliance
                  </div>
                </div>
                <FaqItem question={<>What is
                          <span className="no-wrap">
                            ISO 27001?
                          </span></>} first>
                  <span className="no-wrap">
                        ISO 27001
                      </span>
                      is an international standard for information security management systems (ISMS), focused on managing and reducing risk.
                </FaqItem>
                <FaqItem question={<>Who needs
                          <span className="no-wrap">
                            ISO 27001
                          </span>
                          certification?</>}>
                  Organizations working with enterprise or global clients often require
                      <span className="no-wrap">
                        ISO 27001
                      </span>
                      to demonstrate strong security practices.
                </FaqItem>
                <FaqItem question="What is an ISMS?">
                  An ISMS is a structured system for managing sensitive information, including policies, controls, and risk management processes.
                </FaqItem>
                <FaqItem question={<>How long does
                          <span className="no-wrap">
                            ISO 27001
                          </span>
                          certification take?</>}>
                  Typically 3–9 months depending on organizational maturity and scope.
                </FaqItem>
                <FaqItem question={<>How does Mycroft help with
                          <span className="no-wrap">
                            ISO 27001?
                          </span></>} last>
                  Mycroft helps you build and operationalize your ISMS, manage controls, and maintain audit readiness without overwhelming internal teams.
                </FaqItem>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
