/** Section 5 of /frameworks/iso27001. Generated by the Webflow Cloner agent. */
export function FrameworksIso27001Section5() {
  return (
    <section className="section_v2 color_smoke">
      <div className="page-padding">
        <div className="container-medium">
          <div className="padding-top medium">
            <div className="padding-btm large">
              <img src="/assets/faq-notchlabel-desktop.svg" loading="lazy" alt="" className="faq-notch-desktop" />
              <img src="/assets/faq-notchlabel-mobile.svg" loading="lazy" alt="" className="faq-notch-mobile" />
              <div className="container-flex faq_container">
                <div className="faq-hed-flex">
                  <h3 className="h3_v2 color_white">
                    Frequently asked questions
                  </h3>
                  <div className="text-dek-l text_40eg">
                    Answers that help customers with
                    <span className="no-wrap">
                      ISO 27001
                    </span>
                    compliance
                  </div>
                </div>
                <div className="faq-item first_child">
                  <div className="custom-dropdown">
                    <div className="top-row">
                      <div className="question-container">
                        <div className="h5 color_white">
                          What is
                          <span className="no-wrap">
                            ISO 27001?
                          </span>
                        </div>
                      </div>
                      <div className="state-toggle">
                        <div className="plus-container" style={{"width": "24px", "height": "24px"}}>
                          <div className="plus _75_mint"></div>
                        </div>
                        <div className="minus _75_mint"></div>
                      </div>
                    </div>
                  </div>
                  <div className="answer-container">
                    <div className="body-text-medium color_40eg faq_answer" style={{"height": "0px"}}>
                      <span className="no-wrap">
                        ISO 27001
                      </span>
                      is an international standard for information security management systems (ISMS), focused on managing and reducing risk.
                    </div>
                  </div>
                  <div className="faq-spacer-expand no_opacity" style={{"height": "0px"}}></div>
                  <div className="faq-item-btm-hr"></div>
                </div>
                <div className="faq-item">
                  <div className="custom-dropdown">
                    <div className="top-row">
                      <div className="question-container">
                        <div className="h5 color_white">
                          Who needs
                          <span className="no-wrap">
                            ISO 27001
                          </span>
                          certification?
                        </div>
                      </div>
                      <div className="state-toggle">
                        <div className="plus-container" style={{"width": "24px", "height": "24px"}}>
                          <div className="plus _75_mint"></div>
                        </div>
                        <div className="minus _75_mint"></div>
                      </div>
                    </div>
                  </div>
                  <div className="answer-container">
                    <div className="body-text-medium color_40eg faq_answer" style={{"height": "0px"}}>
                      Organizations working with enterprise or global clients often require
                      <span className="no-wrap">
                        ISO 27001
                      </span>
                      to demonstrate strong security practices.
                    </div>
                  </div>
                  <div className="faq-spacer-expand no_opacity" style={{"height": "0px"}}></div>
                  <div className="faq-item-btm-hr"></div>
                </div>
                <div className="faq-item">
                  <div className="custom-dropdown">
                    <div className="top-row">
                      <div className="question-container">
                        <div className="h5 color_white">
                          What is an ISMS?
                        </div>
                      </div>
                      <div className="state-toggle">
                        <div className="plus-container" style={{"width": "24px", "height": "24px"}}>
                          <div className="plus _75_mint"></div>
                        </div>
                        <div className="minus _75_mint"></div>
                      </div>
                    </div>
                  </div>
                  <div className="answer-container">
                    <div className="body-text-medium color_40eg faq_answer" style={{"height": "0px"}}>
                      An ISMS is a structured system for managing sensitive information, including policies, controls, and risk management processes.
                    </div>
                  </div>
                  <div className="faq-spacer-expand no_opacity" style={{"height": "0px"}}></div>
                  <div className="faq-item-btm-hr"></div>
                </div>
                <div className="faq-item">
                  <div className="custom-dropdown">
                    <div className="top-row">
                      <div className="question-container">
                        <div className="h5 color_white">
                          How long does
                          <span className="no-wrap">
                            ISO 27001
                          </span>
                          certification take?
                        </div>
                      </div>
                      <div className="state-toggle">
                        <div className="plus-container" style={{"width": "24px", "height": "24px"}}>
                          <div className="plus _75_mint"></div>
                        </div>
                        <div className="minus _75_mint"></div>
                      </div>
                    </div>
                  </div>
                  <div className="answer-container">
                    <div className="body-text-medium color_40eg faq_answer" style={{"height": "0px"}}>
                      Typically 3–9 months depending on organizational maturity and scope.
                    </div>
                  </div>
                  <div className="faq-spacer-expand no_opacity" style={{"height": "0px"}}></div>
                  <div className="faq-item-btm-hr"></div>
                </div>
                <div className="faq-item">
                  <div className="custom-dropdown">
                    <div className="top-row">
                      <div className="question-container">
                        <div className="h5 color_white">
                          How does Mycroft help with
                          <span className="no-wrap">
                            ISO 27001?
                          </span>
                        </div>
                      </div>
                      <div className="state-toggle">
                        <div className="plus-container" style={{"width": "24px", "height": "24px"}}>
                          <div className="plus _75_mint"></div>
                        </div>
                        <div className="minus _75_mint"></div>
                      </div>
                    </div>
                  </div>
                  <div className="answer-container">
                    <div className="body-text-medium color_40eg faq_answer" style={{"height": "0px"}}>
                      Mycroft helps you build and operationalize your ISMS, manage controls, and maintain audit readiness without overwhelming internal teams.
                    </div>
                  </div>
                  <div className="faq-spacer-expand no_opacity" style={{"height": "0px"}}></div>
                  <div className="faq-item-btm-hr last_child"></div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
