/** Section 3 of /frameworks/iso27001. Generated by the Webflow Cloner agent. */
export function FrameworksIso27001Section3() {
  return (
    <section className="section_v2 tint_60eg overflow_hidden">
      <div className="page-padding">
        <div className="container-small">
          <div className="container-flex vertical center text_center gap_xs">
            <h3 className="h3_v2 color_rg">
              Additional features for
              <span className="no-wrap">
                ISO 27001
              </span>
            </h3>
            <div className="text-dek-s max_44rem">
              Integrated capabilities to support your information security management system.
            </div>
          </div>
        </div>
        <div className="container-large">
          <div style={{"opacity": "0"}} className="w-layout-grid fw-features-grid">
            <div className="fw-grid-tile">
              <h6 className="h6 color_mint">
                Risk assessment
              </h6>
              <div className="body-text-small color_mint">
                Identify and prioritize security risks
                <br />
              </div>
            </div>
            <div className="fw-grid-tile">
              <h6 className="h6 color_mint">
                Cloud security
              </h6>
              <div className="body-text-small color_mint">
                Protect cloud infrastructure
                <br />
                and services
              </div>
            </div>
            <div className="fw-grid-tile">
              <h6 className="h6 color_mint">
                Risk insight reports
              </h6>
              <div className="body-text-small color_mint">
                Delivers reports prioritizing risks, actioned by Mycroft Agents
              </div>
            </div>
            <div className="fw-grid-tile">
              <h6 className="h6 color_mint">
                Security questionnaires
              </h6>
              <div className="body-text-small color_mint">
                Streamline vendor security assessments
              </div>
            </div>
            <div className="fw-grid-tile">
              <h6 className="h6 color_mint">
                AI policy generator
              </h6>
              <div className="body-text-small color_mint">
                Produce and iterate clear, auditable policy documents
              </div>
            </div>
            <div className="fw-grid-tile">
              <h6 className="h6 color_mint">
                Automatic evidence collection
              </h6>
              <div className="body-text-small color_mint">
                Gathers and stores evidence
              </div>
            </div>
            <div className="fw-grid-tile">
              <h6 className="h6 color_mint">
                Third party risk management
              </h6>
              <div className="body-text-small color_mint">
                Assess and monitor vendor risk
              </div>
            </div>
            <div className="fw-grid-tile">
              <h6 className="h6 color_mint">
                Security training
              </h6>
              <div className="body-text-small color_mint">
                Interactive employee cybersecurity education
              </div>
            </div>
            <div id="w-node-_69496a4e-1d7b-f4fe-5c19-98e703066505-ea549414" className="fw-grid-tile odd_last_child">
              <h6 className="h6 color_mint">
                Policy center
              </h6>
              <div className="body-text-small color_mint">
                Centralized, versioned compliance policies
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
